### ISSUE TITLE
AWS profiles

### ISSUE THREAD

**Issue by tj** [apex/apex#10]
env is annoying

**Comment by NoumanSaleem** [comment]
Not sure if you're aware of the built in aws-sdk profile functionality.
Able to be set with `AWS_PROFILE ` and defaulting to `default`
http://docs.aws.amazon.com/sdk-for-go/api/aws/credentials/SharedCredentialsProvider.html

**Comment by tj** [comment]
ah perfect, thanks!

**Comment by tj** [comment]
seems like it doesn't pick up the region
