### ISSUE TITLE
Introduce Docker for handling cross-compilation & pre-build steps

### ISSUE THREAD

**Issue by pilwon** [apex/apex#100]
We can introduce standardized way to interact with `Docker` for handling cross-compilation for compiled languages as well as performing any required pre-build task for a function (ex: Run `webpack` for a `Node.js` function written in ES2015 to prepare babelified and optimized code for final `.zip`)

Then it should be much easier to add ever growing list of runtimes:
* Java (#4)
* Rust (#19)
* C (#72)
* Swift (#86)
* *and more yet to come...*

**Comment by tj** [comment]
What would Docker be used for? -1 for any Docker stuff in core for me, you can't deploy containers to Lambda, but if you just mean for computing the builds I think that's unnecessary, in most cases it's pretty simple, Docker wouldn't help there I don't think.

**Comment by pilwon** [comment]
@tj I came up with this Docker proposal while thinking about how to bring Swift support to Apex. Docker is completely out of the picture for runtimes we support today. However, once we get to the point where we support multiple compiled languages via shim, each of them having their own requirements, things can get complicated quickly. It can be far easier just telling users that setting up a Docker host somewhere is the only requirement and users being able to instantly deploy functions written in any programming language (while cross-compilations happen behind the scene via pre-built Docker containers) can be a truly magical experience. I know I'm overthinking this at this early stage though. Also, adding lots of languages may not be the goal of Apex.

**Comment by madushan1000** [comment]
Rather than adding support for docker(which might result in a somewhat large download, container + cross compilers + runtime), Maybe we can add support to spawn a new ec2 instance with Amazon Linux or point to an existing Amazon Linux instance for pre-deploy stuff. After all the code is only going to run on Amazon Lambda, which is running on Amazon Linux.

**Comment by mthenw** [comment]
Different projects have a different requirements in terms of building and packaging, and supporting it in `apex` can add unnecessary complexity.

**Comment by johannesboyne** [comment]
@pilwon maybe [`packer`](https://www.packer.io/) in combination with Atlas is better suited for this step?

**Comment by tj** [comment]
Hmm all sounds like too much work to me haha. Most languages let you cross-compile with a few options , I just think we shouldn't support the ones that can't, it's not worth it. If people really want that they could devise their own technique and just add the output to the zip and use `"shim": true` when we have that

**Comment by kapilt** [comment]
perhaps another way is a more generic runtime as plugin, ie. BYOB (binary ;-).

**Comment by tj** [comment]
```json
{
  "hooks": {
    "build": "make"
  }
}
```

should be enough to do whatever people want with ad-hock runtimes or builds now
