### ISSUE TITLE
Missing function description 

### ISSUE THREAD

**Issue by lpinca** [apex/apex#112]
Hi,
I've deployed the example included in this repo and I've noticed that the description for the function `baz` is missing:
![screen shot 2016-01-20 at 09 20 22](https://cloud.githubusercontent.com/assets/1443911/12443333/7037cfe4-bf57-11e5-84f2-f3f0ef5a9f12.png)
I think this is because the `baz` function does not have its own `function.json` configuration file, but when this happens I guess it should be grabbed from the `project.json` file like all other options.
Am I wrong?

**Comment by mthenw** [comment]
Based on wiki page https://github.com/apex/apex/wiki/function.json description is not inherited from `project.json`.

**Comment by lpinca** [comment]
Oh ok, I missed that, thank you.

**Comment by tj** [comment]
might not be a bad idea, beats being blank I suppose
