### ISSUE TITLE
context.succeed and context.fail missing

### ISSUE THREAD

**Issue by cleung2010** [apex/apex#118]
Though I am not deeply familiar with AWS lambda (other than creating some basic hello world style functions), it seems that the "Context Object Methods" as describe in [their doc](http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html) is missing in apex for go, namely `context.succeed()`, `context.fail()`, and `context.done()`. Is it assumed that all methods return `context.succeed()`, and if this is the case how can I return a `context.fail()`?

**Comment by tj** [comment]
The Go support doesn't use those methods because the `interface{}, error` signature takes its place. The Node.js shim uses the resulting JSON: https://github.com/apex/apex/blob/master/shim/index.js#L35

**Comment by cleung2010** [comment]
Gotcha, thanks for the quick response!
