### ISSUE TITLE
Apex website

### ISSUE THREAD

**Issue by farazfazli** [apex/apex#119]
"As a developer, I want to easily learn more about Apex on an easy resourceful webpage."

One page site (apex.github.io) which shows more info about what Apex does, which languages it supports, and how it works.

Let me know your thoughts guys.

**Comment by gelidus** [comment]
So basically, readme but on a subpage? Can't see the real plus of it

**Comment by tj** [comment]
I think we'll eventually have something, but it'll most likely be powered by the wiki. We just need some more docs there I think, first at least :D

**Comment by farazfazli** [comment]
Alright TJ, sounds good! :+1:

**Comment by pilwon** [comment]
+1 for Wiki-focused docs. Github repo with well-organized readme and wiki pages is self-explanatory in most cases. `apex wiki` command can potentially be a great resource for learning too.

**Comment by lpil** [comment]
I'd much rather have the documentation in a git repo than in a github wiki. This information can still be pulled by the client.

**Comment by pilwon** [comment]
@lpil Could you share your insights on why you think git repo is better than wiki? Why do you think we should consider making this switch?

**Comment by lpil** [comment]
I've just discovered that github wikis *are* repos.

https://github.com/apex/apex.wiki.git

I still prefer using a regular repo as it is easier to view the contents, make pull requests, etc. A nice interface for reading can be created with Jekyll or similar static site generator.

**Comment by tj** [comment]
In my experience it gets a little annoying having both in the same repo, if anything I'd rather have apex/docs or similar

**Comment by tj** [comment]
I'll move them over to apex/docs tonight and start a little iste

**Comment by lpil** [comment]
I was suggesting a different repo rather than the same one :)

**Comment by lpil** [comment]
Thanks TJ! :)

**Comment by webdesserts** [comment]
Main reason I like docs in the repo is that the docs are versioned. As long as you can find docs for previous releases though, I've never had too much of a preference. At the very least just make sure that the docs on master aren't ahead of the latest release, that's the worst!

**Comment by tj** [comment]
true true, we could do that in another repo but it would be harder to enforce

**Comment by tj** [comment]
almost ready, I'll move the docs right away and finish it up sometime soon

**Comment by lpil** [comment]
Thanks!

**Comment by tj** [comment]
No domain yet but it's a start: https://github.com/apex/web

**Comment by lpil** [comment]
Looking really nice!
