### ISSUE TITLE
Add contribution guidelines

### ISSUE THREAD

**Issue by farazfazli** [apex/apex#121]
Add ```CONTRIBUTING.md``` which lays out some simple guidelines for contributing, such as coding style, formatting, etc. Code should be formatted with ```gofmt -s``` and code style should be idiomatic as shown in [Effective Go](https://golang.org/doc/effective_go.html).

**Comment by tj** [comment]
yea gofmt is more or less implied with every project IMO but if there are other questions we can add something. I'm not sure if anyone really reads those files but hey! somewhere to point people.
