### ISSUE TITLE
Python dependancies

### ISSUE THREAD

**Issue by pfortin-urbn** [apex/apex#127]
@tj - If I have python libraries that my code requires is there a way in APEX to first declare them and then to get them package for deployment??  Maybe a small example as well would be helpful.

**Comment by lsorber** [comment]
+1

**Comment by pfortin-urbn** [comment]
I have a pull request, added code to the Python runtime for Build and Clean but I am not sure if I need anything else.  I tried to push my branch up but I was denied..

remote: Permission to apex/apex.git denied to pfortin-urbn.
fatal: unable to access 'https://github.com/apex/apex.git/': The requested URL returned error: 403

**Comment by tj** [comment]
closed by that one ^
