### ISSUE TITLE
Fix mock lint errors

### ISSUE THREAD

**Issue by tj** [apex/apex#133]
so we can enable linting in CI. It would also be nice to find a mocking generator/pkg that doesn't use `EXPECT` haha, not sure what they were thinking it looks super weird but that's pretty nitpicky ;D

**Comment by mthenw** [comment]
Can we just exclude mock_* packages from linting?

**Comment by tj** [comment]
might be able to rename them to `_mock` since the tooling ignores those

**Comment by mthenw** [comment]
Which tool you want to use?

**Comment by tj** [comment]
not sure I haven't looked around yet

**Comment by mthenw** [comment]
For sure there should be `go vet` and we can start with that as currently it returns no errors. `go lint` is only for advisory purpose (https://github.com/golang/lint/issues/65), it doesn't even return error code if there are any warnings.

**Comment by mthenw** [comment]
No need to fix that. `gometalinter` has `--skip` param.
https://github.com/apex/apex/issues/122
