### ISSUE TITLE
Add support for specifying the duration used for logs command

### ISSUE THREAD

**Issue by tj** [apex/apex#136]
`apex logs foo` returns the last minute currently, it would be nice to have `apex logs foo 5m`, `apex logs foo 5h` with time.ParseDuration

**Comment by johannesboyne** [comment]
I could implement it.
How about providing the possibility of `duration` or `time ranges`?
`apex/metrics` supports a time range as well and the command could look like:

```
  Print logs for a function with a specified duration, e.g. 5 minutes
  $ apex logs <name> 5m

  Print logs for a function for a customized time range
  $ apex logs <name> --start "18/01/2016 10:00" --end "19/01/2016 22:00"
```

**Comment by tj** [comment]
oops I referenced the wrong issue, ddc4124

**Comment by johannesboyne** [comment]
@tj it wasn't done, right? Haven't seen it in master and needed it myself, thus the PR ;-)
