### ISSUE TITLE
Env loading for nodejs

### ISSUE THREAD

**Issue by tj** [apex/apex#140]
Few options:

- rename to `env.json` so it's nicer to require()
- require that the users install and `require('apex')()` to bootstrap our runtime stuff
- inject the following script:

```js
try {
  var config = require('./.env.json');
  for (var key in config) {
    process.env[key] = config[key]
  }
} catch (err) {
  // ignore
}
```

I like the idea of it being transparent because I wouldn't be too surprised if AWS adds env support at some time, then we can just transition nicely to that.

**Comment by mthenw** [comment]
Also been thinking about that and I would also do injection :)

**Comment by tj** [comment]
I just realized if we inject for nodejs and the shim, we can remove it from the go runtime
