### ISSUE TITLE
Installing Node.js dependencies in node_modules can't be deployed

### ISSUE THREAD

**Issue by rowanu** [apex/apex#143]
Before Apex I have been installing my Node.js function's dependencies using `npm` (i.e. in `node_modules`).

If I try to deploy a function that has a `node_modules` directory in it, I get the following error:

```
⨯ error: open functions/ohai/node_modules/node-feedparser/node_modules/lodash/collection/select.js: too many open files
```

Is this something that should/will be possible? Or am I doing Apex wrong?

**Comment by mthenw** [comment]
Hey, thanks for reporting. Could run deploy with `--log-level=debug` and paste logs here?
