### ISSUE TITLE
CRON scheduled functions

### ISSUE THREAD

**Issue by tj** [apex/apex#147]
Seems like they don't provide an API for this yet which is a little weird, hopefully that's coming:
- http://docs.aws.amazon.com/lambda/latest/dg/with-scheduled-events.html

**Comment by kapilt** [comment]
there's sort of a usable shim for it in the events stuff which allows cron spec invocation of target lambda function

**Comment by johannesboyne** [comment]
Yep, should be possible https://github.com/aws/aws-sdk-go/blob/c4c1a1a2a076858fe18b2be674d833c796c45b09/service/cloudwatchevents/api.go#L804 can check it later

**Comment by johannesboyne** [comment]
@tj Ok, I've found a solution, checkout: https://github.com/johannesboyne/apex/commit/95d83838f166b3d57e7b36eb9211c3411f308dbd

```go
svcc := cloudwatchevents.New(session.New())
svcl := lambda.New(session.New())

cronEvent := &Cron{
	Name:              "CronTestLambda",
	Description:       "Test",
	Expression:        "rate(5 minutes)",
	FunctionName:      "<function-name>",
	FunctionArn:       "arn:aws:lambda:us-west-2:<...>",
	CloudWatchService: svcc,
	LambdaService:     svcl,
}

err := cronEvent.AddSchedule()
log.Println(err)
```

What do you think, where should this belong, how would the command invocation would look like?
I thought about sth. like

* `apex cron [functionname] "rate(5 minutes)"`
* `apex schedule [functionname] "rate(5 minutes)"`

**Comment by tj** [comment]
niceee! I was thinking just a property in the function.json might be cool, I think I'd maybe go with "schedule" as the property, but cron might be more familiar

**Comment by johannesboyne** [comment]
Oh yes, that's maybe even better! 
```json
{
  "name": "foo",
  "description": "pretty description",
  "runtime": "golang",
  "memory": 128,
  "timeout": 5,
  "role": "<...>",
  "schedule || cron": "rate(5 minutes)"
}
```

**Comment by johannesboyne** [comment]
IMHO `apex/event_sources/cron` should be the apex package, because cron is the "tool" that "schedules" and scheduling is an Event Source (AWS terminology):
kind of:

| who schedules | what is the schedule |
|--------------------|--------------------|
| cron | rate(5 minutes) |

But inside the `function.json` it is:
```json
"schedule": "rate(5 minutes)"
```

because it represents the schedule value.
Does this make any sense? :D

**Comment by tj** [comment]
`./sources/cron` skips the `_` :D 

I'd maybe put the bulk of the code in that package, and then call it in a "cron" plugin, similar to these: https://github.com/apex/apex/tree/master/plugins, using a `DeployHook`.

That way we keep most of these integrations out of Function methods.

I suppose we should think about config more now too:

```json
{
  "sources": {
    "schedule": "rate(5 minutes)"
  }
}
```

**Comment by johannesboyne** [comment]
Ok, so kind of this direction:
https://github.com/johannesboyne/apex/commit/35f831b5bb86bc2592860b16a136c56eea444690

**Comment by tj** [comment]
closing for now since I'm not sure it's the road we should be going down. In an ideal world we just supported all of AWS without a secondary tool but that's a ton of work and that is basically TF

**Comment by marwanhilmi** [comment]
Sorry to ping a closed issue, but is there anyway this is currently possible or are the TF changes required first? I'm assuming worst case scenario I can modify the function from the Lambda control panel to run on a schedule?

**Comment by tj** [comment]
@marwanhilmi I think the next release of TF adds it: https://github.com/hashicorp/terraform/pull/4986

**Comment by joelcox** [comment]
Looks like this feature [actually landed in terraform](https://www.terraform.io/docs/providers/aws/r/cloudwatch_event_rule.html). I don't have much experience with go nor terraform, but I might have a stab is this if somebody points me in the right direction :-)

**Comment by rv-rsouza** [comment]
Hey guys! Is there plan on implementing this in next release?
