### ISSUE TITLE
A command to clean-up old versions

### ISSUE THREAD

**Issue by pzurek** [apex/apex#148]
Apex makes deploying Go based lambdas so quick that all the binaries start adding up pretty quickly.
It would be nice to be able to clean up old versions or define in project settings that you only want to keep `n` last versions.

**Comment by tj** [comment]
Haha yeah definitely, open to feedback on it being a separate command or part of the deploy cycle, I think retaining N versions is what most people would want.

**Comment by mthenw** [comment]
Yeah, retaining N versions sounds good. Also we could provide new value in `project.json` to define number of retained versions.

**Comment by carlosrdrz** [comment]
+1

I'd love to see this in Apex.
Going through the old versions to clean them is a PITA :P

**Comment by mthenw** [comment]
I will take care of that after 0.6.0 release.
