### ISSUE TITLE
Environment vars cause different checksum for the same content

### ISSUE THREAD

**Issue by mthenw** [apex/apex#152]
Which causes that function is being deployed every time, no matter if changed.

**Comment by tj** [comment]
I noticed this with the CS example as well, I didn't look into the cause (might be the same) but the checksum was different on each deploy as well.

**Comment by mthenw** [comment]
creation date? :)

**Comment by tj** [comment]
yea probably just a timestamp, better to delegate to a makefile for builds I suppose

**Comment by mthenw** [comment]
not sure what do you mean by "delegate to a makefile for builds"

**Comment by tj** [comment]
ah just that my CS example does `coffee < in > out` every build regardless of changes to `in`, whereas the Makefile would detect that it hasn't changed

**Comment by mthenw** [comment]
What about injecting code with env vars already there. No .env.json file at all. That would require some work but fixes two problems (injecting env and changing timestamp). I'm not super fan but still some idea.

**Comment by tj** [comment]
Hmmm yea true tough call. I like that in the shimmed langs we need a runtime anyway, so that gives us a chance to just grab the file, but for the others it's definitely weird. Inlining could be a decent option

**Comment by mthenw** [comment]
As I'm not fan of injecting code with env because it doesn't scale (Java(?)). So instead of that we can inject this file same as you did with `_apex_index.js` and set the mod time to the same date every time (https://github.com/jpillora/archive/blob/0032298763e340a104b6f7802942a4be21d5c5a3/a_zip.go#L25). Downside of that is that we would have to stop using jpillora/archive :/

**Comment by tj** [comment]
ah darn, well we can fork it if we have to I guess. env does seem like a lot of trouble for something that could just be a config file that they load or don't load haha

**Comment by tj** [comment]
I'll grab this tonight and release

**Comment by tj** [comment]
feels like a hack but hey. at some point we can add AddBytesInfo instead of just zeroing the mtime in our fork

**Comment by mthenw** [comment]
Yeah, will fix that later (https://github.com/jpillora/archive/issues/1)

**Comment by tj** [comment]
ah nice
