### ISSUE TITLE
Output tfvars file for Terraform

### ISSUE THREAD

**Issue by tj** [apex/apex#155]
Need to think on integration some more, but this would be pretty minimal. We could have a command or project.json path to a tfvars file that gets populated by Apex so you can reference the function ARNs.

**Comment by mthenw** [comment]
+1 for output tfvars file. As you marked it for 0.6.0 I will take care of that.

**Comment by tj** [comment]
awesome! feel free to chuck anything in 0.6.0 that you want. I'm not sure exactly what this would look like, I guess we'd just define a tfvars path in project.json or something

**Comment by mthenw** [comment]
I was just thinking about stdout :) But path in project.json sounds fine.

**Comment by tj** [comment]
Ahh yea hmm actually yeah let's do a command for now. I was thinking that it would use a CreateHook or something and output the file to keep it maintained, but easy enough to do a stdout command

**Comment by tj** [comment]
maybe `apex list --terraform` or `--tfvars`

**Comment by mthenw** [comment]
yeah! great idea
