### ISSUE TITLE
Golang structs/handlers for other Lambda sources

### ISSUE THREAD

**Issue by tj** [apex/apex#156]
I'm impartial about having them in here, it's kind of nice name-wise since Go's should match by convention, but apex/go-apex would be ok-ish. On the bright side they shouldn't change much, just some structs.

- [x] move kinesis
- [x] add SNS
- [ ] add CloudWatch Logs
- [ ] add Dynamo
- [ ] add S3
- [ ] add IoT

---
- [ ] update wiki
- [ ] update examples
- [ ] maybe `HandleSNS` / `HandleKinesis` etc

**Comment by lc0** [comment]
Definitely, would be cool to add all these handlers, but it feels like a separate project. 

Since apex is runtime-independent, for me it would totally make sense to have a separate project with all golang runtime

**Comment by tj** [comment]
Yea as much as I like the apex/apex name I agree haha.
