### ISSUE TITLE
Signature expired when deploying

### ISSUE THREAD

**Issue by gaurish** [apex/apex#166]
Has anyone seen this error before?

```
$ apex deploy --log-level debug -e AWS_S3_BUCKET=foo webhook
   • loading functions in functions
   • loading function in functions/webhook
   • inferring runtime         function=webhook
   • inferred runtime          function=webhook runtime=golang
   • deploying 1 functions
   • deploying                 function=webhook
   • creating build            function=webhook
   • hook                      command=GOOS=linux GOARCH=amd64 go build -o main main.go function=webhook hook=build
   • adding env                env=map[AWS_S3_BUCKET:foo] function=webhook
   • add shim                  function=webhook
   • add file to zip           file=.env.json function=webhook
   • add file to zip           file=byline.js function=webhook
   • add file to zip           file=index.js function=webhook
   • add file to zip           file=main function=webhook
   • add file to zip           file=main.go function=webhook
   • created build (10 MB)     function=webhook
   • fetching config           function=webhook
   • changed                   function=webhook local=XHKbBkExNwEgmugx6M9EWjN0kKxHPr8UPBi/+KEm5cQ= remote=ae1q+2LaAW4stISKip+RkPVRy272OwGGh+/ijzZm4vs=
   • updating function         function=webhook
   ⨯ error: InvalidSignatureException: Signature expired: 20160128T043759Z is now earlier than 20160128T043817Z (20160128T044317Z - 5 min.)
	status code: 403, request id: eaed5d6b-c578-11e5-95a0-cb8753796144
``````

I am assuming this happens if file upload takes more than 5mins. is that correct assertion?

**Comment by tj** [comment]
IIRC that's just clock skew, they only allow requests that are up to 5 minutes in the past or something like that, so your clock might just be out

**Comment by gaurish** [comment]
I was trying to upload using my Phone's internet which was taking longer & hence resulted in timeout. But then I tried using the internet at office, it worked fine. also, I checked clock on my MBP, it in sync.

so I am sure this issue is when uploading takes long, it will cause this error. is that possible this is a bug in the way apex handles uploads?

**Comment by tj** [comment]
could be, it's not super high priority right now since I don't think anyone else has hit this but if we can easily reproduce I can check it out

**Comment by gaurish** [comment]
I will try to get a reproducible test case & PR(if possible), can give me some pointers on how to go about this?

**Comment by gaurish** [comment]
I can get did consistently on slow connections

```
 error: InvalidSignatureException: Signature expired: 20160201T100944Z is now earlier than 20160201T100953Z (20160201T101453Z - 5 min.)
	status code: 403, request id: ecc381e1-c8cb-11e5-8271-e72692b9763d
```

**Comment by mthenw** [comment]
@gaurish is it still an issue?

**Comment by podviaznikov** [comment]
Hit the same problem right now. Happened when I added few node_modules and my size became 22 MB.

**Comment by matthewmueller** [comment]
Still an issue for large uploads on slow internet connections

**Comment by quentinfasquel** [comment]
Facing the same issue here as well.

**Comment by syedmesam** [comment]
its just the clock problem set your clock to the actual exact time it works!!!:)
