### ISSUE TITLE
Clojure runtime

### ISSUE THREAD

**Issue by plukevdh** [apex/apex#167]
I could see this going one of two ways:

1. A shim to build for use over whatever Java runtime mechanism ends up getting implemented (usually built via `lein uberjar`
2. Compile via ClojureScript (may depend on what kind of use cases are required) to JavaScript and run on the JS runtime.

**Comment by mthenw** [comment]
Are those two options equal? Or one is better than another? Which one is prefered by Clojure devs?

I'm planning to add Java support next week so both options will be possible. And just to make things clear, option 2 is possible right now, checkout coffescript example https://github.com/apex/apex/blob/master/_examples/coffeescript/project.json#L7.

**Comment by plukevdh** [comment]
@mthenw IMO, the Clojure -> Java route is probably better in the sense it will provide wider support for the "real" Clojure. As I understand it, ClojureScript is a (albeit very fully featured) [subset of Clojure](https://github.com/clojure/clojurescript/wiki/Differences-from-Clojure). Moreover functionality built on Java interop will break, though that simply means you have to decide which "branch" of Clojure you want to support (i.e. you can still interopt with Java_Script_). The major downside to the JVM version is `uberjar`ing Clojure functions can mean for very large package sizes. However that may not differ much from the size of plain Java functions either.

**Comment by tj** [comment]
I couldn't get Java working in Lambda, that whole ecosystem is really confusing to me haha. Having Clojure and/or ClojureScript makes sense to me, not having the script version pretend to be vanilla JVM Clojure

**Comment by plukevdh** [comment]
TBH, the ClojureScript version will probably work with the build hook as-is so long as it has legit CLI tooling (have not used). So maybe that's not something worth focusing too much time on. I can help some when the Java tooling comes along. I've done Clojure -> Lambda work in the past.

**Comment by mthenw** [comment]
I'm adding this to 0.7.0 as I have it almost done.

**Comment by mthenw** [comment]
Moved to 0.8.0 as there is more work than I thought :/

**Comment by mthenw** [comment]
I've removing this issue from 0.8.0 milestone as we will probably merge https://github.com/apex/apex/pull/330 so Clojure will be kinda supported. Will see how it works. If there will be high demand for "native" Clojure support we will reconsider this.

**Comment by matthewmueller** [comment]
@plukevdh were you able to get this working?

**Comment by plukevdh** [comment]
@matthewmueller On Lambda or in Apex? I never tried with Apex but yes on Lambda. I think I just pushed a jar using the AWS CLI in the end. I think it ended up requiring using the `uberjar` stuff in lien.

**Comment by rads** [comment]
I was able to get Clojure working using the current Java support without much effort:

https://github.com/rads/up-clojure

It wouldn't be hard to add first-class Clojure support for `project.clj` files so the overrides in `up.json` are no longer necessary.

**Comment by rads** [comment]
Doh, I just realized this issue is for Apex, not Apex Up. 🤦‍♂️
