### ISSUE TITLE
Vendor deps

### ISSUE THREAD

**Issue by tj** [apex/apex#169]
Pretty low priority IMO, in practice this isn't a huge problem for something with infrequent releases like Apex. Go 1.6 is coming soon so we'll have the vendor lookup.

One thing I'm not sure of is if you can disable the GOPATH lookup or not, the docs didn't make it clear if ./vendor lookup was basically prepending GOPATH or what, if so I think that's a mistake on their part, having it lookup ./vendor _and_ GOPATH is not good. So if we can have it explicitly use ./vendor only that would be great.

**Comment by farazfazli** [comment]
TJ, 1.6 looks in both places by default. I believe 1.5 checks GOPATH and ./vendor if the environmental variable is present. You can explicitly use ./vendor by rewriting imports...is that something we would want to do in the future?

**Comment by tj** [comment]
Nah rewriting is weird I think, that sucks though, wonder why they went that route, just opens you up to errors if you forget to vendor one (happened to us all the time at Segment).

**Comment by tj** [comment]
maybe later we can just have a linter that verifies that they're _all_ in ./vendor

**Comment by farazfazli** [comment]
:+1: @tj I agree!

**Comment by farazfazli** [comment]
This might be re-looked at later, closing for now.

**Comment by robzienert** [comment]
Would like to reopen this and investigate what we can use. I'd be happy to submit a PR. Trying to contribute is somewhat of an uphill battle, tracking down what dependencies apex needs. It'd be much better if I could just use godep or glide and install everything.

**Comment by tj** [comment]
`go get -u ./...` should be fine, I was using https://github.com/dpw/vendetta for this PR but doing all the hacks to omit ./vendor is pretty lame

**Comment by robzienert** [comment]
(facepalm). Thanks!
