### ISSUE TITLE
Rust

### ISSUE THREAD

**Issue by tj** [apex/apex#19]
Requires a stdio shim much like one in this package for Go https://github.com/apex/apex/blob/master/apex.go

**Comment by lpil** [comment]
What extra work would be required here? I would assume that support for other languages that compile to native would be relatively simple after Go support.

**Comment by tj** [comment]
@lpil I don't think anyone started integration really, but yea it shouldn't be too hard, though I don't think Rust supports json in the stdlib so that might make it a bit awkward

**Comment by doomsplayer** [comment]
I now have an initial implementation of rust support.
The question is rust have 2 type of runtimes currently: gnu and musl, so in my current implementation, there are 2 runtimes, `rust-gnu` and `rust-musl`. Not sure if it is ok for you.

(commit)[https://github.com/doomsplayer/apex/commit/7cdfb0dabd30a0a7d6a2ba7df91aeaf34892d969]

**Comment by doomsplayer** [comment]
Updated: I wrote a naive version of [rust-apex](https://github.com/doomsplayer/rust-apex). 

The problem is: should we use channel structures like go-apex? Since there's no goroutine/coroutine in rust, channel structure means 3 new thread at least.

**Comment by tj** [comment]
Sweet! I don't think it needs channels, I used channels in the Go one originally because I thought Lambda did multiple concurrent invokes per-container, but it doesn't, so there's no need to make it concurrent-friendly.

**Comment by doomsplayer** [comment]
PRed

**Comment by lpil** [comment]
Can this be closed?

**Comment by doomsplayer** [comment]
I think so
