### ISSUE TITLE
Handle array in request.json

### ISSUE THREAD

**Issue by gaurish** [apex/apex#195]
Suppose,
I have following the request.json file

```javascript
[
   {
      "event":"processed"
   },
   {
      "event":"deferred",
   }
]
```

and then I invoke it with lambda function:
```sh
$ cat request.json | apex invoke --logs webhook
⨯ error parsing response: json: cannot unmarshal array into Go value of type map[string]interface {}
```

I immediately get the error from apex invoke. Wondering how do we support invoking of JSON arrays?

**Comment by tj** [comment]
ah it's actually expecting newline-delimited json:

```
{ "foo: "bar" }
{ "foo: "bar" }
{ "foo: "bar" }
{ "foo: "bar" }
```

**Comment by tj** [comment]
Oh sorry I see, you want to pass the entire array. Yeah currently we unmarshal to a map to check for "event" and "context". We'll have to unmarshal to interface{} for this
