### ISSUE TITLE
Fancier shell script for binary installs

### ISSUE THREAD

**Issue by tj** [apex/apex#199]
We have:

```
latest=$(curl -s https://api.github.com/repos/apex/apex/tags | grep name | head -n 1 | sed 's/[," ]//g' | cut -d ':' -f 2)
curl -sL https://github.com/apex/apex/releases/download/$latest/apex_darwin_amd64 -o /usr/local/bin/apex
chmod +x $_
```

Which only works on OSX, but if we improved that a bit and stuffed it in a repo we could have a one-liner that works for everyone. I think this would help improve the initial UX a bit, it really depends how familiar everyone is with the tools I suppose. Regardless I think this would be a handy way to bootstrap an install of _any_ binary release, not just Apex.

**Comment by farazfazli** [comment]
Awesome, I completely agree @tj. This would be super helpful!

**Comment by mastilver** [comment]
@tj I guess that's not exactly what you are looking for but I just released: https://github.com/mastilver/apex-bin

**Comment by tj** [comment]
It'll have to be a shell script or something more portable like python

**Comment by farazfazli** [comment]
@tj I can help with a better script...something that uses ```runtime.GOOS``` to detect the OS and then downloads the correct version

**Comment by farazfazli** [comment]
That would require Go installed though...is there any way to do this natively?

**Comment by tj** [comment]
yea we can't use Go, pretty much has to be a shell script or python

**Comment by farazfazli** [comment]
I finished this earlier today and was about to push it just now. You guys work way too fast. Haha
