### ISSUE TITLE
Add region flag

### ISSUE THREAD

**Issue by tj** [apex/apex#200]
Good enough for now (re #153)

**Comment by mthenw** [comment]
why `AWS_REGION=` and region defined in `~/.aws/config` isn't enough?

**Comment by tj** [comment]
I have to deploy the same thing to multiple regions but yeah env var is fine I suppose!

**Comment by ahmedrad** [comment]
@mthenw I'm trying to specify the region on deploy by running `AWS_REGION=us-east-1 apex deploy` but it still seems to grab the region from my default AWS profile which is set to 'us-west-2' .. am I doing something wrong? I sort of expected that passing the env variable while running the command will trump whatever is in the aws config file

**Comment by tj** [comment]
@ahmedrad looks like the --profile stuff broke that (yay env), they sort of over-engineered the SDK with that stuff, but I just poked around their code, the precedence is getting crazy but this should fix it: #329

I kind of vote for just saying screw it to ~/.aws/config, not worth the hassle, magical settings coming from all over the place doesn't do much good.

**Comment by ahmedrad** [comment]
@tj you guys are crazy fast on responses :+1: , I'll be sure to write up my experience using Apex for a deployment process when I'm done ;)
