### ISSUE TITLE
CloudWatch logs for Golang

### ISSUE THREAD

**Issue by zen4ever** [apex/apex#201]
using the Node.js shim is basically makes it not possible to use fmt.Println to log output to cloudwatch logs. What would be the best/recommended practices for logging with Apex/Golang projects?

**Comment by tj** [comment]
The current plan is to fix this with #162 so each shimmed language is fixed out of the box. I thought for sure they would be passing stdio to cloudwatch but yea I guess not! We'll have that fixed for the next release

**Comment by tj** [comment]
oh sorry I read that wrong, you can use `log.*` since it writes to stderr, or if you're into structured logging there's https://github.com/apex/log

**Comment by zen4ever** [comment]
That works, thanks. I was just trying to do simple logging for development, since more structured approach requires additional setup, but apex/log looks great for production.
