### ISSUE TITLE
Loading environment variables for Python runtime

### ISSUE THREAD

**Issue by cscetbon** [apex/apex#202]
I use `apex deploy -e log_level=DEBUG App` to deploy an environment variable called `log_level` with my lambda. However it's not loaded in the environment map when I invoke it using `apex invoke App < event.js`. Is it a current limitation of the Python runtime with apex ?

**Comment by mthenw** [comment]
>  Is it a current limitation of the Python runtime with apex ?

That's right. Currently env vars are stored in `.env.json` file. So you need to read that file.

**Comment by cscetbon** [comment]
:disappointed: I think for now I'll wait for it to be implemented. I prefer to use the same way of accessing variables with all runtimes than using a custom way for Python

Do you know when it should be available ? I could also have a look at it to add it myself if I find some time

**Comment by mthenw** [comment]
I marked it for 0.6.0 as it would be cool to have consistent experience for all runtimes. You can take a look how it's handled in nodejs (https://github.com/apex/apex/blob/master/plugins/nodejs/nodejs.go#L19). We basically inject some code that reads`.env.json` and sets env vars.

**Comment by tj** [comment]
:+1: full support there would be great
