### ISSUE TITLE
Updating configuration doesn't work

### ISSUE THREAD

**Issue by mthenw** [apex/apex#206]
because we don't use $LATEST. 

AWS Docs:
> If you are using the versioning feature, note this API will always update the $LATEST version of your Lambda function.

http://docs.aws.amazon.com/lambda/latest/dg/API_UpdateFunctionConfiguration.html

**Comment by tj** [comment]
hmm but our current == $LATEST? I swear I've hit the timeout, deployed the change and have it work fine, definitely good to confirm haha

**Comment by mthenw** [comment]
`current` points to the latest deployed version but it might not equal $LATEST in terms of configuration.

**Comment by tj** [comment]
hmm maybe we should remove function.json from the .apexignore so it _does_ trigger a re-deploy in that scenario

**Comment by mthenw** [comment]
a bit hacky :)

**Comment by tj** [comment]
yep haha, beats an extra round-trip to see if the config has changed first I think, we'd have to re-deploy there anyway, I guess we just can't do a rollback and change config

**Comment by mthenw** [comment]
More info from docs:
> Published versions are immutable. You cannot update code or configuration information associated with a published version.

http://docs.aws.amazon.com/lambda/latest/dg/versioning-intro.html

I think we need to give up rollbacks :/

**Comment by tj** [comment]
How come? I think config and the code are somewhat independent, if you rollback because of some bug it's probably not too likely that you wanted to revert the timeout/memory/role IMO

**Comment by mthenw** [comment]
I posted reply too fast :) Made some more tests. 

Right now if the change is only in config Lambda will update $LATEST version (without creating new version) and it will has no effect on our "current" alias. So basically it's a bug. 

To fix that we would have to deploy code every time only config changed, which is fine imho. 

If we do that rollback will work as expected. 

Agree?

**Comment by tj** [comment]
yep that sounds good to me, I'm not totally against just letting the function.json file changes force the deploy haha, it's not explicit but zero work, we'll just have to document it or something
