### ISSUE TITLE
Invoking function from another function

### ISSUE THREAD

**Issue by mthenw** [apex/apex#209]
Implementation should be in node-apex and go-apex (and python-apex) of course but general discussion should be here.

Some of the use cases (code sharing) can be achieved with https://github.com/apex/apex/issues/180 but I would consider adding that possibility to enable complex apps. 

Thoughts?

**Comment by tj** [comment]
Something higher level would be pretty sweet, I've been using SNS between mine for now but I can imagine cases where you don't need queues or fan-out.

**Comment by alfonsodev** [comment]
would make it sense to include `apex` binary and just run `apex invoke` as child process ?  
I'm not sure about how would you pass the credentials to the function's runtime.

**Comment by alfonsodev** [comment]
Another option could be to create gateway end point for the function , and call the lambda via `http`  
what about that ?

**Comment by tj** [comment]
@alfonsodev I would recommend using the AWS SDK for whichever language you're using, for example: https://github.com/apex/apex/blob/master/function/function.go#L394-L401. That's what I use in a few functions to invoke others, but you could abstraction out the AWS SDK to make it more like a regular function call in js/python/go
