### ISSUE TITLE
Add arbitrary script support

### ISSUE THREAD

**Issue by pranspach** [apex/apex#210]
I'd like to see more configurability for hooks, or a different step for "pre-build" actions like eslint and mocha. The build step could get pretty gnarly as projects evolve.

```
"build": "eslint src/*.js test/*.js && mocha --compilers js:babel-core/register && ../../node_modules/.bin/babel src -d lib && cp -fr ../../node_modules node_modules",
```

How do you fit linting and unit testing into your workflows? Offload to external build tooling? Append to the build line? Ignore it?

Of the top of my head, we could add a pre-build hook for "Verify"?

**Comment by tj** [comment]
Forgot to add docs for hooks! we have "build", "clean", and "deploy" right now. Build and deploy are different but they since they both run on a deploy you could add linting to either. I'd use build for build stuff and deploy for validation stuff

**Comment by pranspach** [comment]
It makes sense that people don't want to bail out of the build process if linting and tests fail. I don't constantly want to deploy though -- I just want to run my tests. I'm thinking more of a "watch" feature: save file and trigger tests. Like [grunt watch](https://github.com/gruntjs/grunt-contrib-watch)

Maybe I'm misunderstanding the deploy stage...

**Comment by tj** [comment]
ah I see, in general I think there are other good solutions for running arbitrary tasks etc that don't have to be in apex (Makefiles or whatever you flavour is). There's no reason you couldn't use grunt or gulp etc. We don't have a `apex run build`, `apex run clean` etc, it's all just called internally as those things happen

**Comment by tj** [comment]
For my use-case (using Go) I just run `go test ./...` from my root dir, so I don't need Apex to do anything special there at all. You could easily do similar with node using a makefile or a grunt/gulp/*.

**Comment by pranspach** [comment]
Ya, I could use [npm watch](https://github.com/grncdr/npm-watch). I tend to group like things together, so linting/testing fits with with build tasks in Apex so I see them being configured together.

When you run go test in your root dir, does that watch for changes (like with [fswatch](https://github.com/andreaskoch/go-fswatch)) or do you manually run that?

**Comment by tj** [comment]
Yea I can't argue with that, having tasks in multiple places is a little odd, I think it's fine in Go's case since the commands all support multiple directories, `go test ./...` is idiomatic, but that's not really the case with the other runtimes.

I manually run it, but that doesn't bug me since I usually git-commit after anyway so I'm already in the term. I'll leave this open for some more feedback.

**Comment by pranspach** [comment]
:thumbsup:

**Comment by tj** [comment]
still a maybe but I'm adding to 0.7.0

**Comment by tj** [comment]
closing for now, it feels a little arbitrary to run the commands relative to function dirs, and to run them in the CWD might as well be a makefile
