### ISSUE TITLE
Support [default] region

### ISSUE THREAD

**Issue by 5loop** [apex/apex#213]
Maybe this is a Windows issue, or my setup is wrong... Either way, Apex can't find my AWS region config. Any help?

![image](https://cloud.githubusercontent.com/assets/8572133/12799324/7f617f94-ca8b-11e5-9856-87a12a974ad0.png)

**Comment by tj** [comment]
ah I don't think we check default right now, just `[profile <name>]` sections

**Comment by 5loop** [comment]
I can work with that :) thanks

**Comment by 5loop** [comment]
Never got "apex --profile" to work with `[profile <name>]` sections... It threw the same error as before.

Got set up using "aws config" and it's working fine now. Feel free to close this.

**Comment by tj** [comment]
I think we should still support `[default]`. I just noticed though that it's `./.aws` in your screenshot, we're looking in `~/.aws`

**Comment by tj** [comment]
false alarm, didn't realize we had [default] already
