### ISSUE TITLE
can not compile from source

### ISSUE THREAD

**Issue by davyzhang** [apex/apex#220]
# github.com/tj/go-prompt
go/src/github.com/tj/go-prompt/prompt.go:81: assignment count mismatch: 2 = 1
go/src/github.com/tj/go-prompt/prompt.go:93: assignment count mismatch: 2 = 1

**Comment by mthenw** [comment]
Try
```
go get -u github.com/tj/go-prompt
```

**Comment by davyzhang** [comment]
works like a charm, thanks
