### ISSUE TITLE
Deploy does not include directories on Windows

### ISSUE THREAD

**Issue by 5loop** [apex/apex#222]
Directories in a function's directory are not included when `apex deploy` is run on Windows. So, `require`ing something in `node_modules` will fail, for example.

Deploying the same project on Linux does work. 

In both setups Apex 0.6 is installed.

**Comment by mthenw** [comment]
Hey, could you paste `apex deploy --log-level debug` output from both Windows and Linux (for the same project). I'm completely unfamiliar with Windows but we can try to fix this :)

**Comment by 5loop** [comment]
Linux output:

```
• loading functions in functions
• loading function in functions/foo
• deploying 1 functions
• deploying                 function=foo
• creating build            function=foo
• add file to zip           file=index.js function=foo
• add file to zip           file=index.zip function=foo
• add file to zip           file=stringholder/foostring.js function=foo
• created build (762 B)     function=foo
• fetching config           function=foo
• config unchanged          function=foo
• code unchanged            function=foo
• cleaning 1 functions 
```

Windows output:
```
   • loading functions in functions
   • loading function in functions\foo
   • deploying 1 functions
   • deploying                 function=foo
   • creating build            function=foo
   • add file to zip           file=index.js function=foo
   • add file to zip           file=index.zip function=foo
   • add file to zip           file=stringholder\foostring.js function=foo
   • created build (762 B)     function=foo
   • fetching config           function=foo
   • config unchanged          function=foo
   • code unchanged            function=foo
   • cleaning 1 functions
```

**Comment by tj** [comment]
Hmm those look fine to me, producing the same byte size, is that the case with node_modules involved as well?

**Comment by 5loop** [comment]
Yep, just verified with node_modules. Once again it's the same byte size, but Lambda is throwing the following after a deploy from Windows:
```
{
  "errorMessage": "Cannot find module 'async'",
  "errorType": "Error",
  "stackTrace": [
    "Function.Module._resolveFilename (module.js:338:15)",
    "Function.Module._load (module.js:280:25)",
    "Module.require (module.js:364:17)",
    "require (module.js:380:17)",
    "Object.<anonymous> (/var/task/index.js:2:13)",
    "Module._compile (module.js:456:26)",
    "Object.Module._extensions..js (module.js:474:10)",
    "Module.load (module.js:356:32)",
    "Function.Module._load (module.js:312:12)",
    "Module.require (module.js:364:17)"
  ]
}
``` 
Works fine after a Linux deploy.

**Comment by tj** [comment]
I suppose the archive would literally have `\\` in the path names, I've never really thought about that haha, haven't touched windows in ages, may have to switch that to a path.Join

**Comment by mthenw** [comment]
@5loop could you use `apex build foo > out.zip` and check files paths inside zip?

**Comment by 5loop** [comment]
The file paths in the .zip from `apex build foo > out.zip` look fine. However, if I upload that file manually or via aws-cli, I get the same error as above when invoking.

If I zip the files manually and then upload the .zip from that, there is no error.

Maybe it is a `\\` vs `/` issue, like @tj mentioned. I know that Windows does some automagic file path stuff so that it can read files from Linux machines, which might be why everything looks fine inside of the .zip even though the paths are still breaking
