### ISSUE TITLE
MissingRegion

### ISSUE THREAD

**Issue by tleen** [apex/apex#223]
Upgraded to  v0.6.0 and started to see an error:

> Error: function versions: MissingRegion: could not find region configuration

~/.aws/config looks like:

```
[default]
region = us-east-1
output = json

[profile x]
region = us-east-1
output = json

```

Everything words fine when I manually set AWS_REGION in env. I'm on Ubuntu 15.04, another user in slack has the same issue on Ubuntu 15.10.

**Comment by plukevdh** [comment]
@tleen I assume you want it to default to "default" if not provided either via the `-p` flag or `AWS_REGION`? 

Working on a fix.

**Comment by tj** [comment]
@plukevdh he mentioned it wasn't working even with the profile set. I opened #225 since it's probably related

**Comment by tleen** [comment]
I think using default by default would be the expected behavior. Although I would also support putting the default profile for a specific project into the project.json file, or some other way local to the project itself.

**Comment by tj** [comment]
@tleen hmm yea I like that, +1 from me. It's definitely a little confusing if we support a million things but having it local to the project would be nice to prevent mistakes
