### ISSUE TITLE
replace os/user with go-homedir

### ISSUE THREAD

**Issue by tj** [apex/apex#225]
looks like it's still using cgo, cross-compiles fine but seems like it could be our issue with ~/.aws/config on windows. https://github.com/mitchellh/go-homedir

**Comment by tobyjoe** [comment]
I think the issue with ~/.aws/config is that the AWS Go SDK doesn't use it. Maybe I'm thinking of a different issue?

https://github.com/aws/aws-sdk-go#aws-cli-config-file-awsconfig

**Comment by tj** [comment]
oops, updated the desc, this is a windows-only problem (we added ~/.aws/config support in apex)
