### ISSUE TITLE
fix pattern matching for .gitignore parity

### ISSUE THREAD

**Issue by tj** [apex/apex#228]
Not reallllly a bug but `src` should be valid to leave out the entire dir etc. re: #226 

Maybe only dirs is what they read specially, I haven't actually read the gitignore docs haha.

**Comment by mthenw** [comment]
I made some research and fnmatch has been replaced with custom function (wildmatch) in 1.8.4 https://github.com/git/git/blob/master/Documentation/RelNotes/1.8.4.txt

wildmatch source https://github.com/git/git/blob/8d530c4d64ffcc853889f7b385f554d53db375ed/wildmatch.c YAY

**Comment by mthenw** [comment]
found JS version https://github.com/vmeurisse/wildmatch/blob/master/src/wildmatch.js

**Comment by tj** [comment]
hahaha lovely, maybe it's not worth it, I suppose having a nicer way to preview what _is_ in the function would help a bit

**Comment by tj** [comment]
or https://github.com/rliebling/gitignorer

**Comment by mthenw** [comment]
yeah, much better. I don't think that using this C func in Go should be a problem though.
