### ISSUE TITLE
`generate` command

### ISSUE THREAD

**Issue by pitr** [apex/apex#229]
A simple `apex generate` or `apex init` that will create a simple structure. Takes runtime as argument, defaulting to node. Recreates corresponding [example](https://github.com/apex/apex/blob/master/_examples) in current directory.

(I can work on this)

**Comment by tj** [comment]
:+1: on a related note I'd like to bootstrap Terraform too, like the apex/boilerplate repo (but tweaked a bit). We haven't figured out what works best for node deps yet but we could get started

**Comment by tobyjoe** [comment]
:+1: for sure. 

I spent a couple of nights this week creating a "wrapper" project that automates the creation of an apex/boilerplate style project. It's super rudimentary, and written for my personal workflow, but it may be of interest as reference for ideas. 

I'd happily shift focus to a couple of additional CLI commands. Higher-value ones for myself and my teams would be:

```bash
apex init [path] # Create a new project in the current directory or supplied path
apex new [name] # Create a new function with the given name
```

Additionally, a flag or ```project.json``` and ```function.json``` field to signal that ```terraform apply``` should be called (perhaps via ```deploy``` hook?) would be pretty sweet.

There are obviously lots of opinions on how to manage Terraform config out in the world, but for Apex, it seems like the same "greater specificity" rule as JSON config would be great. 
Either separating the ```terraform``` dir from the ```functions``` dir:

```bash
project.json
functions/foo/index.js
functions/bar/index.js
terraform/project.tf
terraform/modules/iam/iam.tf
terraform/modules/{etc}/{etc}.tf
terraform/functions/foo/function.tf
terraform/functions/bar/function.tf
```

Or, mixing them so each function feels like a Go package:
```bash
project.json
functions/foo/index.js
functions/foo/terraform/function.tf
functions/bar/index.js
functions/bar/terraform/function.tf
terraform/project.tf
terraform/modules/iam/iam.tf
terraform/modules/{etc}/{etc}.tf
```

FWIW, my project hasn't embraced either approach - I'm still just defining one global Terraform for now, to unblock using it on a project at work. My `-h` commands:

```bash
tjbair:test tobyjoe$ copper project -h

Create a new Apex and Terraform project

Usage:
  copper project [flags]

Flags:
  -b, --base string          Project base directory (default ".")
  -s, --bucket string        Terraform remote config bucket
  -c, --credentials string   Credentials (~/.aws/credentials)
  -d, --description string   Project description (default "AWS Lambda function")
  -k, --key string           Terraform remote config key
  -m, --modules value        Terraform modules to bootstrap (default [])
  -n, --name string          Project name (default "Copper Project")
  -p, --profile string       AWS profile name (default "default")
  -g, --region string        AWS Region (default "us-east-1")
  -r, --runtime string       Project runtime (nodejs, python, go, java) (default "nodejs")
```

And the function generator:
```
tjbair:test tobyjoe$ copper function -h

Create a new Apex function

Usage:
  copper function [flags]

Flags:
  -n, --name string      Function name
  -r, --runtime string   Runtime (default "nodejs")
```

I'll push to a remote tonight or tomorrow morning. I'm running out at the moment.

Either way, I'd love to contribute to this tooling aspect, as it will help with consistency and the simple conventions Apex already builds on.

**Comment by pitr** [comment]
@tobyjoe looks like you've given this much more thought and time than I did :+1:

**Comment by tobyjoe** [comment]
@pitr - I'm trying to disentangle some of the deeper bits I put into my project and extract a basic project generator and function generator. 

I'll push something soon, and folks can hack on it until it feels right for Apex.

**Comment by mthenw** [comment]
Closing as we added `init` command in https://github.com/apex/apex/releases/tag/v0.7.0
