### ISSUE TITLE
S3 source

### ISSUE THREAD

**Issue by tj** [apex/apex#23]

**Comment by fibo** [comment]
Hi,

I am trying apex and I think it is a good idea. In particular, I need to load data from S3 (ELB logs, for instance) to RedShift.

I started with an `apex init` creating a dummy function, and for sure I need to add an *Event Source* to trigger the function.

Something like

![screen shot 2016-03-25 at 16 48 43](https://cloud.githubusercontent.com/assets/176730/14047693/a919c044-f2a9-11e5-92da-822d869f0974.png)

I guess this is an issue related to this topic, my question is:

1. Would it be possible to support event source? Right now if I run `apex deploy` the Event source is deleted.
2. Alternatively, would it be possible to not delete it and keep the one configured on AWS?

I don't know which option feet better with apex project goals, but, I would like to contribute. Even if am not a skilled golang programmer, it should be easy for me to test and eventually propose some modification if   I recieve some hint before diving into the code.

Please let me know any hint.

**Comment by tj** [comment]
Oops this should be closed actually. We're advocating the use of existing tools like CloudFormation / Terraform to manage non-Lambda infrastructure, at least for now! I use Apex + Terraform for my projects personally

**Comment by fibo** [comment]
Can you give an example? As a user that is trying apex, if when I updated the lambda with `apex deploy` it overrides the S3 source and there is no hint in the documentation, it is a limit that makes me write a lambda from the AWS interface.

**Comment by tj** [comment]
Oh I see it's overriding? That definitely should not be the case, anything you configure manually or via another tool should remain. The only parts that an `apex deploy` should override is the actual function's config such as role and timeout.

**Comment by fibo** [comment]
Sorry, it does not override neither delete: it works.
I tryed again and it worked. I got confused cause I created my very first lambda function with AWS, then my second one with apex, with a similar name.

Thanks.

**Comment by tj** [comment]
ahhh cool, had me confused :D glad it's not doing strange things
