### ISSUE TITLE
walk up to 'project.json'

### ISSUE THREAD

**Issue by tleen** [apex/apex#230]
When calling the apex functions it may be handy to have it walk up the directory structure to find the project.json file. When working on a function, having it be able to deploy from that directory rather than needing to call apex from the project root. Small productivity optimization.

**Comment by tj** [comment]
Possibly! I'm not against it. For now I like the simplicity but could have this as a utility that doesn't touch the rest of the system, just alters the commands or something

**Comment by mthenw** [comment]
I'm not fan of that. This may give false impression that `apex deploy` in function's dir will deploy only this function. Things should be simple (which doesn't equal easy in some cases :))

**Comment by tleen** [comment]
Yeah, I was thinking more like NPM where you can execute commands in subdirs and they reference the root package.json. I don't think this is very important. if anything perhaps just more info in the error message when project.json is not found.

**Comment by tj** [comment]
Closing for now, I don't dislike the idea but I agree it adds unnecessary complexity for now, especially in the docs department I could see people getting confused. I'm generally a bigger fan of having one way to do something if possible
