### ISSUE TITLE
Mechanism to register event hooks with a lambda?

### ISSUE THREAD

**Issue by plombardi89** [apex/apex#246]
I've got a lambda written that I want to hook up with an SNS topic. I didn't see any way to do this via the documentation? Is this a planned feature in the future by any chance or did I just miss something in the documentation?

**Comment by mthenw** [comment]
Generally we suggest using Terraform for anything besides Lambda funcs. We don't what to rewrite existing tools. You can get function ARNs via `list` command http://apex.run/#listing-functions

**Comment by plombardi89** [comment]
Understandable... I guess I prefer a more integrated solution, but the design decision makes sense. Wondering if this could be addressed by creating an apex-recipes type repository that's a bit more in depth than the examples and shows how to do stuff like glue Apex together with Terraform to build a SNS notification processor.

Anyways great tool and the first one I think that actually makes Lambda feel "easy".

**Comment by tj** [comment]
We do plan on having tighter integration with TF, and potentially provide generators and/or TF modules to help in situations like you mention. There's definitely a reasonably large barrier for getting up and running right now.

I'm going to close, but keep an eye on #253!
