### ISSUE TITLE
Deploy config changes

### ISSUE THREAD

**Issue by tj** [apex/apex#25]
Currently no way to tweak beyond the original function creation. Options:

1. separate command
2. `deploy` opt-in flag
3. `deploy` checks changes of both and updates (with opt-out flag)

Currently thinking 3, that's what I would expect at least. 

We'll also need a way to install third-party deps or programs and allow tweaking their config without editing the repo contents.

**Comment by mthenw** [comment]
+1 for 3. 

I was so surprised, when I used apex for the first time, that config changes are applied during deploy.

**Comment by tj** [comment]
Actually I guess we'll need a `apex deploy config` for cases where you haven't changed the code, but I still think deploying it w/ code changes makes sense

**Comment by mthenw** [comment]
What is the reason for having separate command for config changes?

**Comment by tj** [comment]
yea nvm me haha just being dumb
