### ISSUE TITLE
Terraform integration

### ISSUE THREAD

**Issue by tj** [apex/apex#253]
I thought we had this issue already but meh! haha

- [x] ensure TF is installed
- [x] .gitignore for ignoring .terraform
- [x] Decide on multi-env TF structure
- [x] Generate project.json
- [x] Decide on defaults (enough to get started, lambda role etc)
- [ ] Fix flag collisions with Terraform (everything after `infra` should be TF)
- [ ] Env switching in Apex
- [x] Bootstrap example function
- [x] Add bootstrapping of the directory and its defaults
- [x] Add terraform "proxy" command (`apex infra plan`, `apex infra apply` ?) relative to env
- [ ] Generate vars for TF (lambda ARNs etc)
- [x] Initialize S3 state per env
- [ ] Add environment scoping for regular Apex config
- [x] Expose functions to TF
- [ ] Expose terraform output to Apex
- [ ] Add language bootstrap prompt, let them choose node/go/python 
- [ ] make it look nice
- [ ] remove tfvars listing?
- [ ] scope state to project name? (I use separate buckets but meh?)
- [ ] Fix weird prompt scan bug, skips input when a space is passed

## Defaults

- [x] Lambda role
- [ ] User account (so people don't use root all the time)
- [x] Stage and prod envs
- [ ] Cross-account role and example user(s)

## Future

Later we'll have things like TF modules for helping tie functions together with SNS, Kinesis and other services. Alternatively this could come in other forms, such as templating, since TF modules are a little weak, but they should be fine for this use-case.

## Misc

Like @mthenw mentioned maybe we use TF to define the function config as well. We could possibly leave deploys to Apex, since I think it does this better, but the config could potentially live in TF. I'm not sure there would be a big benefit there, since we wouldn't have defaulting like we do in project.json etc, but not having two types of config would be more elegant.

Curious to see how TF handles gateway as well, I have a hunch that it'll be a big heredoc with the JSON, which would not be ideal either. 

We'll need a little walkthrough for the initial state stuff, via `apex init` or similar. All you should need to bootstrap a project is an AWS account and S3 bucket.

## Extra mile

- [ ] Install terraform for them if it's not available?
- [ ] Walk them through ~/.aws/credentials

**Comment by mthenw** [comment]
Few thoughts that I have in mind

## Basic structure 
```
.
project.json
infrastructure/
  apex - bootstraped minimal module with role, user can add stuff here like s3 bucket etc
  project.tf - bootstraped env file with "module" block, user can add more files like this
functions/
  ..
```

## Steps to add another env

1. create `project_<env>.json`
2. create `infrastructure/project_<env>.tf` with `module "apex_<env>"` block

or just 

`apex init env <env>`

`project.json` is default. There is no need to specify env param while `deploy` or `rollback`. For any other env there has to be `-e <env>` (?) param passed.

## TF -> apex integration

`deploy` or any other command could read state file and get role ARN and any other ARN in future.

## apex -> TF integration

`apex infra plan` would call terraform command with `-var 'apex_function_foo=arn...'` params for every function so it could be used in .tf files.

**Comment by mthenw** [comment]
Also, not sure what to do with order of command. Should we require `apex infra` before `apex deploy`?

**Comment by tj** [comment]
I think the flow would be something like:

```
$ apex init # generate the project boiler junk
$ apex infra apply # bootstrap infrastructure 
$ apex deploy # deploy functions
```

But maybe those could all be wrapped in:

```
$ apex setup
```

Or maybe `init` walks you through the steps and invokes each after showing you the command, sort of like a little interactive tutorial. That way you learn a bit about Apex while it's bootstrapping.

**Comment by tj** [comment]
Ah good call with -var though, forgot about that, no need to write to files yay

**Comment by tj** [comment]
Might start toying with this tonight a bit, if I do I'll push a branch up so we can start toying with ideas

**Comment by mthenw** [comment]
> maybe it's not really our concern at all how the terraform stuff is structured other than the envs.

I think so.

Also 
> Like @mthenw mentioned maybe we use TF to define the function config as well

Not sure where I said that but right now I'm against that idea :)





> prefix apex functions ... so it's not oddly unbalanced by apex infra ...

Please no :)

**Comment by tj** [comment]
Haha in Slack you mentioned Apex being a layer on top of TF, maybe I misinterpreted.

**Comment by tj** [comment]
So far it feels pretty nice, should really improve the user experience. Feels awkward shelling out to another package, but I doubt TF is easy to integrate with at the Go level, seeing as it ships with dozens of bins.

**Comment by mthenw** [comment]
> I think it could possibly work, but I'm not super fond of requiring people to use TF

That's why I'm against that. I want to separate responsibility clearly. Apex is about Lambda funcs (& API Gateway), TF is about everything else.

> Using an env var seems like the logical way to go, even if it's not a "cute" api like apex env <name>

IMHO `-e <env>` should be dedicated for env switching. We should come up with other param to pass environment vars to function.

**Comment by mthenw** [comment]
> apex init

I was thinking if this should bootstrap TF stuff. Maybe separate param `apex init --instrastructure`?

Assuming that TF is not needed for running apex (which I tihnk i a huge benefit) maybe we should provide some command to init project without TF?

**Comment by tj** [comment]
Yea I guess it could be a prompt or flag. I think passing `-e prod` all the time would be a little annoying but being explicit about the env you're in is not necessarily a bad thing, just ugly, so I have mixed feelings there

**Comment by mthenw** [comment]
> I think passing -e prod all the time would be a little annoying but being explicit about the env you're in is not necessarily a bad thing, just ugly

I personally find it useful because user is 100% sure what he does.

> Maybe "defaultEnv": "stage" and -e prod or environment variable?

Not sure if it's not confusing but I would just name it "default" env. If you run command without `-e <env>` you use "default" env. User has to decide what is it.

**Comment by tj** [comment]
Yea I agree with you there, just thinking out loud. I like clarity too, I was thinking for that same reason that specifying the profile in ./project.json like someone else brought up makes sense too, I've never been very fond of environment variables for anything, too magical & accident-prone.

**Comment by tj** [comment]
needs some love stuff but I pushed the add-init branch

**Comment by mthenw** [comment]
Closing as we have basic integration commited.
