### ISSUE TITLE
Always disregard mtime

### ISSUE THREAD

**Issue by tj** [apex/apex#262]
Kind of hacky, but since webpack and friends aren't really great at not re-generating the same content, it could be nice to ignore mtime.

**Comment by mthenw** [comment]
Not sure what is benefit here. Could you elaborate?

**Comment by tj** [comment]
Maybe we're already doing it, I forget now but I'm pretty sure when you use webpack/browserify etc Apex will currently re-deploy each time since the mtime of the build file(s) will change regardless of content

**Comment by mastilver** [comment]
@tj yes I can confirm, it's redeploying every functions even if there is no change

**Comment by tj** [comment]
@mastilver ah thanks for the confirmation! It's a bit of a dirty hack but I can't recall the last time I actually used mtime, I don't plan on using Makefiles in a lambda function haha
