### ISSUE TITLE
VPC not working

### ISSUE THREAD

**Issue by ghislainf** [apex/apex#273]
Hi,

VPC feature not seem to work, no data related to VPC config was defined on my AWS lambda functions.

My project config related to VPC :
```
"vpc": {
  "securityGroups": ["sg-380d27**"],
  "subnets": ["subnet-a8dc49**"]
},
```

Please correct me if I've missed anything.

Big thanks ! Apex save me a lot of time :)

**Comment by tj** [comment]
hmm I haven't tried it yet, CC @mthenw. Did you install from master? v0.6.x didn't have VPC support

**Comment by mthenw** [comment]
@ghislainf as TJ said, if you want to use VPC support you need to build from master or wait few days until 0.7.0 will be released.

**Comment by ghislainf** [comment]
I have make a build from master and try again, and it's not working also.

**Comment by mthenw** [comment]
Are you sure you were deploying using apex compiled from master?

Just checked it and with following config 
```
{
  "name": "node",
  "description": "Node.js example project",
  "role": "arn:aws:iam::...",
  "vpc": {
    "securityGroups": ["sg-..."],
    "subnets": ["subnet-..."]
  }
}
```

I was able to deploy function with VPC enabled.

<img width="286" alt="screenshot 2016-02-26 13 19 26" src="https://cloud.githubusercontent.com/assets/455261/13352137/9c166ed0-dc8b-11e5-8247-205d1ceecb85.png">

**Comment by mthenw** [comment]
Closing for now.
