### ISSUE TITLE
apex logs doesn't work

### ISSUE THREAD

**Issue by madushan1000** [apex/apex#274]
Any of `apex logs`, `apex logs func_name`, `apex logs -s 2h` doesn't work as expected. 
I can see my lambda function logs in aws cloud watch console. But `apex logs` returns nothing. 
`apex logs -f` works fine though.

**Comment by mthenw** [comment]
Just checked it against master version and 0.6.1 and works as expected. Could you specify exactly what do you mean by " doesn't work as expected".

**Comment by madushan1000** [comment]
I can see there are logs under cloud watch log group (`/aws/lamba/my_func`) when I use the aws console. But when I run `apex logs` in my apex project directory it doesn't output anything. I tried specifying the different times with -s flag too. Didn't work. 

Do I need to add log read permissions to the lambda execution role in `project.json`?

**Comment by mthenw** [comment]
> Do I need to add log read permissions to the lambda execution role in project.json? 

Nope, you have to have log read permission on you account that you use to run `apex logs`. 

Could you run logs command with `--log-level debug` and paste output here.

**Comment by mthenw** [comment]
@madushan1000 any news here?

**Comment by madushan1000** [comment]
Turns out, My account didn't have the permissions read logs. Thank you for the help :). I'm closing the issue.
