### ISSUE TITLE
Default credentials from `.aws` files not including region based on console instructions

### ISSUE THREAD

**Issue by ajcrites** [apex/apex#280]
From what I can ascertain from the [AWS CLI configuration instructions](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html), you should have an `~/.aws/credentials` file and a `~/.aws/config` file for defaults.  Apex seems to use the credentials just fine, but I can't get it to recognize my region:

    # credentials
    [default]
    aws_access_key_id=<key>
    aws_secret_access_key=<secret>
    region=us-east-1

    # config
    region=us-east-1
    output=json

The credentials seem to be working fine, but I need to use `AWS_REGION` when I run apex, as in:

    AWS_REGION=us-east-1 apex deploy

This may just be me misunderstanding either apex or the CLI instructions or both, but I don't seem to be able to set the default region for apex.

**Comment by tj** [comment]
hmm missing `[default]\n` in ~/.aws/config? I think it's required (could be wrong)

**Comment by ajcrites** [comment]
Same result for adding a newline after `[default]` as for omitting it.

**Comment by tj** [comment]
Ahh are you on Windows? I thought we got this in the last release but right now only master has it: https://github.com/apex/apex/commit/1672d1c4cd5d0d4fd63d1a3fe2627660359881af

**Comment by ajcrites** [comment]
I'm on Ubuntu 15.10. Should have specified that before.

Maybe this will fix the issue for other OSen as well, though. Let me try out the master branch...

**Comment by tj** [comment]
Ah darn haha, cool thanks for checking it out, we'll be releasing 0.7.0 in the next few days regardless of getting all the changes we wanted in

**Comment by ajcrites** [comment]
Seems like it works properly when I build from master, so 1672d1c probably fixes the issue.

By the way, do you have instructions on building it? I couldn't really figure it out and just did `go get -d && gox` from the `cmd/apex` directory, but that seems wrong to me.

**Comment by tj** [comment]
`go get github.com/apex/apex/cmd/apex` should do the trick, but that assumes $GOPATH/bin is in your $PATH
