### ISSUE TITLE
EACCES error when running go-lang lambda function

### ISSUE THREAD

**Issue by bnoon** [apex/apex#281]
I am getting the following when deploying go functions:
```
{
  "errorMessage": "Process exited before completing request"
}
```
With `[Error: spawn EACCES] code: 'EACCES', errno: 'EACCES', syscall: 'spawn'` in the log.

This is caused by the `main` executable not having the `+x` mode set.  The FileInfo isn't being set when creating the `zip` archive.

A hack using `zip.AddFile` allows me to deploy lambda functions again, but it looses the `mtime` fix.

**Comment by tj** [comment]
My bad, yea I guess we need AddBytesInfo instead of AddBytesMTime

**Comment by tj** [comment]
waiting on https://github.com/jpillora/archive/pull/5/files

**Comment by bnoon** [comment]
Thanks!  BTW, this is a great tool.
