### ISSUE TITLE
Storing sensitive variables or parameterizing environment

### ISSUE THREAD

**Issue by ajcrites** [apex/apex#282]
My lambda function needs access to an API key that I don't want to store in version control. From the apex docs I see that you can create `environment` properties as key-values, but this requires you to store the actual value.

One possibility would be to parameterize parts of the configration like `function.json`

```
{
    "description": "Do something sensitive",
    "environment": {
        "AJCRITES_API_KEY": "{{AJCRITES_API_KEY}}"
    }
}
```

This could read from the existing environment during build/deploy.

**Comment by mastilver** [comment]
It's already supported, but for all functions not for a specific one
https://github.com/apex/apex/blob/master/docs/env.md

**Comment by ajcrites** [comment]
This is exactly what I need, but per-function support would be nice too. It would also be convenient if apex could read from the environment as a whole during deployment.
