### ISSUE TITLE
Support for compressed deployment packages

### ISSUE THREAD

**Issue by raime** [apex/apex#286]
Currently, Apex does not compress the deployment package, which means the maximum size for the uncompressed function, when deployed using Apex, is 50MB - the same as the limit for a compressed deployment package (see [Amazon Lambda Limits](http://docs.aws.amazon.com/lambda/latest/dg/limits.html#limits-list)). If the deployment package (.zip) was compressed, the function could contain a lot more data, as the actual limit for uncompressed function data is 250MB.

Please add compression to the deployment .zip packages so that the uncompressed function data could be five times as large as is currently possible using Apex.

**Comment by mthenw** [comment]
It's already there (https://github.com/apex/apex/commit/21d3b959c525ba5bb56272dbcda2f3c2de264f2d) Will be released in version 0.7.0 in few days.

**Comment by raime** [comment]
Oh, excellent! I talked about it with TJ two weeks ago, but added the issue now as I did not see the already closed one. :)


Best regards,

Jeremias
