### ISSUE TITLE
I can specify VPC dependent information but not the actual VPC id?

### ISSUE THREAD

**Issue by sharvell** [apex/apex#287]
I can specify VPC dependent information but not the actual VPC id? How can I specify the actual VPCID or is it autodetected? Deploy does not setup the VPC properties if I only include vpc.securityGroups and vpc.subnets

**Comment by mthenw** [comment]
You can't specify VPC ID. This is how AWS handle that. 

From SDK docs:
> If your Lambda function accesses resources in a VPC, you provide this parameter identifying the list of security group IDs and subnet IDs. These must belong to the same VPC. You must provide at least one security group and one subnet ID.

http://docs.aws.amazon.com/lambda/latest/dg/vpc.html
http://docs.aws.amazon.com/sdk-for-go/api/service/lambda.html#type-VpcConfig
