### ISSUE TITLE
Pre-built Java JAR support

### ISSUE THREAD

**Issue by robzienert** [apex/apex#300]
The current Java plugin requires Apex to have a POM file and then rebuilds the JAR for you. A lot of more modern JVM projects use Gradle, and generating a POM from Gradle is a pain, and is redundant. 

It would be nice if the java plugin were made to support either Gradle, or supplying a fat JAR. What I could see is one of the two:

1. Add a fork in Build to look for a `build.gradle`, in which case it would attempt to run the `gradle shadowJar distZip` tasks. If `build.gradle` doesn't exist, it would move onto generating the pom file as it does today.
2. It could just look for the presence of `target/apex-plugin-target.jar` or `build/apex-plugin-target.jar`. If those exist, it'll zip the JAR and move on. 

Maybe just making a `java-gradle` plugin would be the cleaner way?

Thoughts? This work would be pretty easy, but would remove a lot of boilerplate legwork for projects using Gradle.

**Comment by tj** [comment]
Whatever is idiomatic sounds good to me, I'm a total Java noob so we're relying on contributions for the integration. For anything more opinionated I like the idea of "sub-runtimes" like node-babel or like you mention java-gradle.

**Comment by bhurlow** [comment]
supplying a built jar would help for clojure support as well

**Comment by mthenw** [comment]
Would be great to have Gradle support. I think that there should be two separate plugins as those are two different systems.

I think that option 1. is how we should approach that. But not in existing plugin but in separate.

**Comment by robzienert** [comment]
Separate plugins sounds good to me. Nice and clean. I'll work on a `java-jar` plugin, since that's quite ubiquitous.

**Comment by mthenw** [comment]
Also I think that we should stop generating pom. It adds unnecessary noise in plugin code and probably isn't helpful to anyone. 

As it hasn't been released yet I will refactor it tomorrow and also add Gradle support.

**Comment by mthenw** [comment]
@robzienert haven't seen your. Ok so I will refactor existing plugin and you can create new one for Gradle. Not sure why 'java-jar' not 'java-gradle'?

**Comment by robzienert** [comment]
Based on @bhurlow 's comment, it may make sense to have a generic jar plugin. The JVM has Maven, Gradle, SBT, Lein and more - all that do builds differently, but at the end of the day are all capable of generating a single fat jar.

Depends what direction we want to take it. We'll get maximum flexibility with a jar module that puts the burden of generating the jar on the developer, but works for everything. Going the tool-specific route will be lower barrier to entry for tools we support, but we'll wind up with more modules. With `java-jar`, we'd just need to check both `build/jar-name.jar` and `target/jar-name.jar`, then could still handle the zipping inside of the plugin.

**Comment by robzienert** [comment]
Going to start on the `java-jar` plugin today, now that I have some time at work.
