### ISSUE TITLE
Define event sources in function.json

### ISSUE THREAD

**Issue by slaskis** [apex/apex#314]
I'm using [scheduled events](http://docs.aws.amazon.com/lambda/latest/dg/with-scheduled-events.html)  with my apex functions right now and although it's quite easy to set up using the AWS console, it would be so nice to be able to have them defined in the `function.json` config file and tracked by version control.

Perhaps something like:

```
{
  ...
  "events": [
    {
      "source": "schedule",
      "name": "Every 5 minutes",
      "schedule": "rate(5 minutes)", // or "cron(Minutes Hours Day-of-month Month Day-of-week Year)"
    },
    {
      "source": "s3",
      "name": "When log file has been stored",
      "bucket": "my-bucket",
      "type": "put",
      "prefix": "logs/",
      "suffix": ".log"
    }
  ]
}
```

Thanks for making AWS Lambda super easy to use!

**Comment by tj** [comment]
ah we did consider this before actually (#192), but it's a bit of a slippery slope. At least until we hit 1.0 I think it's best to stay away from things that other tools (CloudFormation, Terraform) do pretty well.

That said Terraform has been bugging me a bit lately, hitting a decent number of bugs, and CloudFormation is just slow/awkward/no dry-run, so I'd still consider it long-term, but overall I don't want to duplicate Terraform's efforts.

**Comment by slaskis** [comment]
Ah somehow I missed that issues when I tried to find if there has been previous discussions about it. 

Looking at the commits of that issue it looks way more complicated that I was hoping it would be, I'll just stick with the console for now. 

Cheers!
