### ISSUE TITLE
appending environment variables to the function name

### ISSUE THREAD

**Issue by ahmedrad** [apex/apex#315]
Not sure if there's a way already to do this but I'm trying to use Apex to deploy to both integration and production functions named "my-function-production" on us-west-2 region and "my-function-integration"  on "us-east-2".

my plan was on deployment run a deploy on the specific function and add an environment variable that specified the current_environment
```apex deploy -e CURRENT_ENV='integration' --profile my-function-integration my-function```

that way the profile specifies the right region but I don't know how the function name can append the `CURRENT_ENV` variable to it's name so that on AWS they end up as two separate functions in two separate regions.

**Comment by ekosz** [comment]
I'm migrating from `node-lamda` so I created a setup to do exactly this. I have this file called `bin/apex`:

```bash
#!/usr/bin/env bash

# Set APEX_ENV env var, default to "development" if undefined
export APEX_ENV=${APEX_ENV:=development}

if [ -e ".env.${APEX_ENV}" ]; then
  # Load the correct .env file defaults to ".env.development"
  eval $(cat .env.${APEX_ENV} | sed 's/^/export /')
fi

# Substitute the env vars into the template
envsubst < project.json.teml > project.json
# Run our apex command with the new project file
apex $*

# Cleanup
rm project.json
```

And this is what my `project.json.teml` file looks like: 

```json
{
  "name": "xxx",
  "description": "xxx",
  "role": "xxx",
  "runtime": "nodejs",
  "handler": "lib.default",
  "hooks": {
    "build": "../../node_modules/.bin/webpack --config ../../webpack.config.js --bail",
    "deploy": "../../node_modules/.bin/eslint src",
    "clean": "rm -fr lib"
  },
  "environment": {
    "ENTITY_HOST": "${ENTITY_HOST}",
    "IMGIX_HOST": "${IMGIX_HOST}",
    "LATTICE_HOST": "${LATTICE_HOST}",
    "NODE_ENV": "${NODE_ENV}",
    "SENDWITHUS_API_KEY": "${SENDWITHUS_API_KEY}"
  },
  "nameTemplate": "{{.Function.Name}}-${APEX_ENV}"
}
```

This does two things: 

1. Manage my env vars for me under different environments
2. **Changes the name of the function based on the `APEX_ENV` env var**

You can do the same, skipping the env vars if you'd like but still have the `nameTemplate` be dynamic.

Does that answer your question?

**Comment by ahmedrad** [comment]
I think so yeah thanks a lot, could you write the example bash commands just so I'm sure I follow the flow correctly (sorry my bash skills are non-existent and not sure how that bash script in the top would execute when I'm deploying)

**Comment by ekosz** [comment]
Sure thing the bash commands would look exactly the same as regular `apex`, except you would run the custom `apex` command with the env var you want to set.

```bash
# Deploy using integration
CURRENT_ENV=integration ./bin/apex deploy

# Deploy using production
CURRENT_ENV=production ./bin/apex deploy
```

**Comment by ekosz** [comment]
The script really relies on the `envsubst` command. Documentation here: https://www.gnu.org/software/gettext/manual/html_node/envsubst-Invocation.html

**Comment by mthenw** [comment]
@ahmedrad could you say more about the reason for having env name as a part of function name?

**Comment by ahmedrad** [comment]
thanks a lot @ekosz I really appreciate it

@mthenw for all our applications we have an integration environment that's a replica of our production environment. We usually separate them by region but that's not always ideal and so our naming convention has been to append production or integration to the end of the function name so that we're able to differentiate between them. That way the integration function is hooked up to our integration app through integration SNS and fires of API calls to integration 3rd party services and production goes through an identical but separate pipeline.

**Comment by mthenw** [comment]
@ahmedrad basically we suggest using separate account for different envs and this is what we have in mind building apex. But in your situation policy for specific resource might be helpful http://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements.html#Resource

You can have different roles for different env under same account.

**Comment by tj** [comment]
I'd like to eventually maybe allow env vars / terraform vars / user vars in the JSON, but that's probably not a near-term thing (haven't had a need for it yet) – issue #178 to watch for that.
