### ISSUE TITLE
Clean hook should still be run after deploy hook failure

### ISSUE THREAD

**Issue by ekosz** [apex/apex#316]
First off, thank you for creating this awesome project. Its really helped me cleanup and consolidate my existing lambda functions.

I have a project that is using webpack to compile my javascript using the `build` hook. I recently added an eslint `deploy` hook and noticed that the compiled javascript from webpack still stuck around after a failed linting.

Is this by design? I would think the `clean` hook would always be run even after a failed `deploy` command.

Thanks!

**Comment by mthenw** [comment]
> Is this by design?

I think that's proper behaviour. Assuming that build failed we can't continue the deploy process. Currently Clean will be called only if deploy finishes without an error. 

In your case I think that you should lint before compiling JS (?) so there would be no leftovers after failed eslint.

**Comment by ekosz** [comment]
Hmm, I would have thought the `deploy` to be more of a ephemeral hook that possibly uses built artifacts of `build` to do things, but not necessarily leave its own artifacts.

If that's not the case, then should the documentation be updated? Currently it lists linting and testing as examples to do during the `deploy` hook, but it seems that may not be the best place for them after all?

**Comment by mthenw** [comment]
I believe that it depends highly on lambda language/build system. Not sure but I think that in your case adding eslint as a part of `build` hook, before webpack compile would solve the problem, something like:

```
"build": "../../node_modules/.bin/eslint . &&  ../../node_modules/.bin/webpack --config ../../webpack.config.js",
```

**Comment by mthenw** [comment]
@ekosz have you resolved your issue?

**Comment by ekosz** [comment]
Yeah. I moved the linting to the build step.
