### ISSUE TITLE
Support symlinks

### ISSUE THREAD

**Issue by ummwolfcat** [apex/apex#320]
I put all the shared code for my functions in a shared npm module. To make development easier, I use "npm link" to create a symbolic link of this module in each function. This way, as I make changes to my shared code, I don't have to go and do an "npm install" for each function.

However, this approach appears to not work, because when I ran "apex deploy" I got this error:
Error: function getTasks: Only regular files supported: node_modules/core.

What's the recommended way to handle shared code for the Node.js environment?

**Comment by tj** [comment]
Ah yea we don't support symlinks at the moment, we should probably just 'follow' them and pull the files in (zips are built in-memory so it should be fine).

**Comment by ummwolfcat** [comment]
Okay cool! For now I guess I'll just use local paths to reference my shared module, and then write a quick script that will run "npm install" within each function anytime I've made changes to shared code — unless there's a better way!

**Comment by tj** [comment]
I guess we'd have to mess with the paths. If you have a link like `../node_modules/core` that obviously won't work once Lambda unzips, hrmm. Thinking symlinks that are outside of the function are just bad news. 

We have a few issues regarding better ways to package common libs:

- #180
- #306 

It's still unresolved but we do need a better solution for scripted languages. Closing this one for now, I think it would be way too awkward to try mess with paths outside the func.

**Comment by ummwolfcat** [comment]
To be clear, the npm link command puts the symlink inside the function. If you were to zip it, it would get zipped as if it was actually there. Seems like it should just work?

I'm going off of how "DaliborKovac" describes how he handles sharing code in the comments of this thread:
https://forums.aws.amazon.com/thread.jspa?threadID=214756

**Comment by tj** [comment]
Oh sorry you're right, I had paths like `require('../../foo')` in mind, those wouldn't work, but I get it now hahaha.
