### ISSUE TITLE
how to relate the package in lambda to a certain git commit

### ISSUE THREAD

**Issue by ahmedrad** [apex/apex#321]
So I'm developing my lambda functions locally and pushing to github when I'm done and deploying as well. Is there anyway I can link the code on lambda to a certain git commit? I'm worried because as this process is manual me or any other developer can cause these two to go out of sync. So I end up with some package on lambda that I can never trace back to a certain commit on the github repo. Any thoughts would be highly appreciated.

I was thinking of writing some custom bash script to add an environment variable to the function with the latest commit sha but that feels like an ugly workaround .. any thoughts?

**Comment by tj** [comment]
Hmm if you just want to inject the commit sha for logging etc I'd probably just do `alias apex='apex -e GIT_COMMIT=$(command to get git sha)'` so you can just use `apex deploy` like normal

**Comment by mthenw** [comment]
@ahmedrad closing. If you have further questions I will open it.
