### ISSUE TITLE
install.sh not working: GitHub API rate limit exceeded

### ISSUE THREAD

**Issue by fibo** [apex/apex#323]
Following [installation instructions](http://apex.run/#installation) I get a */usr/local/bin/apex* with the content `{"error":"Not Found"}`.

If I run the command I found in the install script, which populates the `LATEST` variable I get

```
curl -s https://api.github.com/repos/apex/apex/tags
{
  "message": "API rate limit exceeded for 195.103.105.74. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

**Comment by tj** [comment]
Did you try again since then? Nothing we can do about the GH rate limit there

**Comment by fibo** [comment]
Thanks, I tryed later and it worked.
