### ISSUE TITLE
Set default env in project.json 

### ISSUE THREAD

**Issue by mthenw** [apex/apex#338]
Based on https://github.com/apex/apex/pull/331

**Comment by mthenw** [comment]
@tj assuming that we will have something like
```
{
  "name": "myproject",
  "role": "whatever",
  "env": {
    "prod": { "role:" "new thing" }
  }
}
```

what do you think about marking default env with `"default": true` 
```
{
  "name": "myproject",
  "role": "whatever",
  "env": {
    "prod": {
        "default": true,
        "role:" "new thing"
    }
  }
}
```

**Comment by tj** [comment]
hmm that could work, might be easiest to have something on the root level so we dont have to iterate to find it (or have multiple with default by accident (unlikely anyway but hey))
