### ISSUE TITLE
Constantly asking for terraform on windows

### ISSUE THREAD

**Issue by silarsis** [apex/apex#343]
C:\Users\Kevin\Source\Repos\scheduled-events [master +3 ~0 -0 !]> C:\Users\kevin\Downloads\apex_windows_amd64.exe init

Enter the name of your project. It should be machine-friendly, as this
is used to prefix your functions in Lambda.

  Project name: scheduled-events

Enter an optional description of your project.

  Project description: Various Scheduled Events

Would you like to manage infrastructure with Terraform? (yes/no) no
Would you like to manage infrastructure with Terraform? (yes/no) no
Would you like to manage infrastructure with Terraform? (yes/no) no
Would you like to manage infrastructure with Terraform? (yes/no) n
Would you like to manage infrastructure with Terraform? (yes/no) yes
Would you like to manage infrastructure with Terraform? (yes/no)
Would you like to manage infrastructure with Terraform? (yes/no) n
Would you like to manage infrastructure with Terraform? (yes/no) no
Would you like to manage infrastructure with Terraform? (yes/no) no
Would you like to manage infrastructure with Terraform? (yes/no) Would you like to manage infrastructure with Terraform? (yes/no)
C:\Users\Kevin\Source\Repos\scheduled-events [master +3 ~0 -0 !]>

**Comment by tj** [comment]
yikes, that's not good hmm, wonder if it's maybe a line ending issue https://github.com/tj/go-prompt/blob/master/prompt.go#L16

**Comment by silarsis** [comment]
A number of them didn't work at all. Password seemed to work. string_required worked:

C:\go\src\github.com\tj\go-prompt [master ≡]> \go\bin\go run .\_examples\string-required.go
First name: kevin
Last name: littlejohn

Hello "kevin\r" "littlejohn\r"
C:\go\src\github.com\tj\go-prompt [master ≡]>

**Comment by tj** [comment]
ah interesting ok cool thanks! We should be fine if we add \r to the trim list

**Comment by tj** [comment]
0.7.3 should be up in a minute
