### ISSUE TITLE
Multi-env support in config

### ISSUE THREAD

**Issue by mthenw** [apex/apex#344]
Similar to `--set` we could support `--role`. Might be helpful for users that don't want to use TF for envs.

**Comment by cnuss** [comment]
+1

**Comment by ummwolfcat** [comment]
I was just looking for a --role option! How else can I specify the role when I'm regularly switching between a dev and prod environment (two different AWS accounts)?

**Comment by mthenw** [comment]
@ummwolfcat assuming that you use Terraform for managing AWS resources you can use `-e` switch. It's poorly documented right now but will be described better in 0.8.0.

**Comment by ummwolfcat** [comment]
@mthenw I do not. I'm new to AWS and just want a simple mobile backend, with as few dependencies and abstractions as I can manage. I have a simple bash script that I'm using for testing and deploying my lambda functions and was able to workaround this problem — for now —by simply managing a prod project.json and a dev project.json, and have the script copy over the appropriate file before calling apex deploy.

Definitely interested if you think there's a better way for a small project like this?

**Comment by tj** [comment]
:D yea Apex sucks for multi-env right now, sorry, very close to needing a nicer setup myself. Kind of a pain to use `--profile foo --role bar` to toggle. I'm not against having a role flag but I think even for the non-terraform cases it should be a little smoother.

We'll need to start supporting env config soon anyway (I needz it), which would look something like:

```json
{
  "name": "myproject",
  "role": "whatever",
  "env": {
    "prod": { "role:" "new thing" }
  }
}
```

or envs are root-level props, doesn't really matter, we'll have something

**Comment by joshrtay** [comment]
have you guys considered implicitly using the git branch as the `env` var?

**Comment by tj** [comment]
Hmm little too magical I think. I'd still use the same branch personally, the only thing different between envs in my case is a few end-points that need swapping

**Comment by mthenw** [comment]
Yeah, makes more sense to specify that as @tj mentioned.

**Comment by joshrtay** [comment]
Definitely agree. Too specific to my workflow.
