### ISSUE TITLE
env for deploy no longer seems to work

### ISSUE THREAD

**Issue by ajcrites** [apex/apex#349]
Using node.js, after updating from 0.6.1 to 0.7.3, I can no longer seem to deploy with `-e` / `--env` flags:

    apex deploy fn --env "FOO=BAR"

In my lambda function I just return `process.env`, but `FOO` is missing.

**Comment by ajcrites** [comment]
I see that `-e` / `--env` was changed to `--set`, so this is just a documentation bug.

**Comment by mthenw** [comment]
Yup, `-e` flag is now used to switch infra environments. If you want to set environment variable use `-s/--set` flag.

**Comment by mthenw** [comment]
@ajcrites that's right. I will update website with new docs.
