### ISSUE TITLE
Docs about logging

### ISSUE THREAD

**Issue by mthenw** [apex/apex#35]
It took me few clicks to understand this `apex logs`. Would be great to have some docs describing how to use this command with log library or/and log-collector.

**Comment by tj** [comment]
It might not be worth including in here since it's not using cloudwatch logs, not sure if people would expect that (could be useful too). Might move it to a separate repo so people can use it if they want to use the other log stuff

**Comment by tj** [comment]
Closing for now, removed that stuff in the MF pull-request. Might just go with CloudWatch logs and parse JSON from there in log-collector, then we get the best of both!
