### ISSUE TITLE
Environment variables with commas cause `index out of range`

### ISSUE THREAD

**Issue by ajcrites** [apex/apex#350]
This may be related to another library apex is using, but I can't tell. If I try to set an environment variable that contains a comma, I get an "index out of range" error, e.g.

    apex deploy --set "foo=bar,baz"

Using `'foo="bar,baz"'` or `"foo='bar,baz'"` doesn't seem to change anything.

I'm not trying to use an array or set multiple variables or anything like that; the environment variable I'm trying to set is a MongoDB DSN with a replica set so it happens to have a comma in it.

```
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0xa7ae80, 0xc82000e220)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/apex/apex/cmd/apex/deploy.run(0xed1da0, 0xc8201778c0, 0x0, 0x12, 0x0, 0x0)
        /Users/tj/dev/src/github.com/apex/apex/cmd/apex/deploy/deploy.go:65 +0x282
github.com/spf13/cobra.(*Command).execute(0xed1da0, 0xc8201777a0, 0x12, 0x12, 0x0, 0x0)
        /Users/tj/dev/src/github.com/spf13/cobra/command.go:565 +0x62c
github.com/spf13/cobra.(*Command).ExecuteC(0xed2fa0, 0xed1da0, 0x0, 0x0)
        /Users/tj/dev/src/github.com/spf13/cobra/command.go:656 +0x55c
github.com/spf13/cobra.(*Command).Execute(0xed2fa0, 0x0, 0x0)
        /Users/tj/dev/src/github.com/spf13/cobra/command.go:615 +0x2d
main.main()
        /Users/tj/dev/src/github.com/apex/apex/cmd/apex/main.go:37 +0x81
```

**Comment by eyko** [comment]
The comma acts as a separator so the parser is expecting another k=v: `apex deploy --set "foo=bar,baz=qux"`. Try using another character, like a semicolon: `apex deploy --set "foo=bar;baz"` will give you `bar;baz` which you can then do a `strings.Split(s, ";")` on.

**Comment by ajcrites** [comment]
I'm not trying to use it as a separator as such. The environment variable (a MongoDB DSN) in this case has a comma in it. I could try replacing it but that would be pretty hacky.

**Comment by tj** [comment]
eek, not good, we should be using SplitN actually anyway, I'll patch this up tonight

**Comment by eyko** [comment]
Actually @ajcrites this seems to work like you expected: `apex deploy --set \"foo=bar,baz,qux\"` (escaping quotes so the shell doesn't ignore them).

**Comment by tj** [comment]
hrm you shouldn't have to escape quotes, this is Cobra doing the comma splitting? /me confused

**Comment by eyko** [comment]
yeah, so `f.StringSliceVarP` [here](https://github.com/apex/apex/blob/master/cmd/apex/deploy/deploy.go#L47) means that when we get to [`Split` and `Setenv` here](https://github.com/apex/apex/blob/master/cmd/apex/deploy/deploy.go#L64-L65) you can't guarantee that all env vars are in the `k=v` format – i.e. in the case of `--env foo=bar,baz` range env will be `foo=bar`, `baz`)

**Comment by tj** [comment]
ahhh I missed that feature, I did not intend for that haha, though I don't hate it but I would rather just `-s foo=bar -s bar=baz`

**Comment by tj** [comment]
we can come back to it later but I think it might make the most sense to disable that part of Cobra if possible, I didn't expect that just looking at it personally

**Comment by ryantuck** [comment]
fwiw, i got this error when i neglected to set the `handler` param correctly in `function.json`:

```
{
  "handler": "my_function"
}
```

instead of the correct:

```
{
  "handler": "main.my_function"
}
```

hth
