### ISSUE TITLE
Add support for node 4.3.2 runtime

### ISSUE THREAD

**Issue by rotemtam** [apex/apex#356]
Amazon recently added a nodejs 4.3.2 runtime for lambda. It would be able to specify it as a value in the configuration json files.  Maybe like:

```
{
  "description": "<function desc> ",
  "runtime": "nodejs:4.3.2"
}
```

**Comment by tj** [comment]
:+1: just saw this as well

**Comment by poscar** [comment]
+1

**Comment by rotemtam** [comment]
http://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html

Amazon has "nodejs" for the 0.10 runtime, and "nodejs4.3" for the new one, would make sense to stay aligned with that terminology

**Comment by tj** [comment]
It's a little annoying (internally) not having a nice delimiter, even "nodejs:4.3" like you mention would be nice

**Comment by mthenw** [comment]
+1 for staying aligned with AWS terminology. I will work on it tomorrow.
