### ISSUE TITLE
Node.js 4.3 Support

### ISSUE THREAD

**Issue by ummwolfcat** [apex/apex#360]
I was so excited to learn this morning that Lambda now supports Node.js 4.3:
https://aws.amazon.com/about-aws/whats-new/2016/04/aws-lambda-supports-node-js-4-3

I updated my project.json file to the new runtime: "nodejs4.3" and I got the following error while trying to deploy:
Error: error opening function getTasks: Handler: zero value

Is there a workaround or anything I can do to get this working? Doesn't apex just pass the runtime along to AWS CLI?

Thanks!

**Comment by tj** [comment]
Are you on 0.8.0? Should be ok: https://github.com/apex/apex/commit/1b37b3bfaf0dba4c6b42d687e860face677d8fe5

try `apex upgrade`

**Comment by ummwolfcat** [comment]
Oops! You're right, I wasn't on the latest version. I updated and am no long getting that error, however, making that change in my project.xml doesn't seem to do anything? I updated runtime to "nodejs4.3", but now when I run apex deploy it just says "config unchanged" for all my functions. When I log in to the AWS console I can confirm that all my Lambda functions are still on 0.10.

**Comment by ummwolfcat** [comment]
I don't know why this isn't working (it incorrectly thinks the configuration hasn't changed, possibly because I tried running it prior to upgrading apex?), but I was able to workaround it by just deleting my lambda functions in the console and deploying again :)

**Comment by tj** [comment]
@mthenw mentioned something about the API not letting us change runtimes, haven't tried myself so I can't comment! Or maybe it was just that it's not part of the GetFunctionConfiguration (whatever that call is) so we can't do a diff on it to detect change

**Comment by mthenw** [comment]
Golang SDK doesn't expose function to change Runtime of existing function (http://docs.aws.amazon.com/sdk-for-go/api/service/lambda/Lambda.html#UpdateFunctionConfiguration-instance_method). The only function that accepts Runtime param is http://docs.aws.amazon.com/sdk-for-go/api/service/lambda/Lambda.html#CreateFunction-instance_method.

I've wrote post about that [Node.js 4.3 support in Apex 0.8.0](https://medium.com/apex-serverless/node-js-4-3-support-in-apex-0-8-0-e8a4bdd4e37a).

**Comment by mthenw** [comment]
Closing for now. @ummwolfcat if you want to discuss it more I will reopen.

**Comment by davyzhang** [comment]
So my golang project keep reporting :"The runtime parameter of nodejs is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs4.3) while creating or updating functions."

How can I change the golang's runtime to nodejs4.3?

**Comment by polds** [comment]
@davyzhang looks like PR #637 fixes this. I'll review it and merge it. @tj would need to publish it.

**Comment by tj** [comment]
doing a release in a minute
