### ISSUE TITLE
Updating alias on deploy

### ISSUE THREAD

**Issue by dekz** [apex/apex#364]
Thanks for your work on Apex! It's a super easy to use tool for us.

We are using multiple AWS accounts, but not exactly one per environment. Production, NonProd are split. This means NonProd might have a few environments under it, or per-person lambdas.

We are seeing an issue with deploying and having aliases in a CI pipeline.

Current State: 
- Version 3 has tags `[dev, staging]`

New code change:

```
> apex deploy --alias dev
   • config unchanged          function=failure_alerts
   • updating function         function=failure_alerts
   • updated alias dev         function=failure_alerts version=4
   • function updated          function=failure_alerts name=test_failure_alerts version=4
```

Current State: 
- Version 3 has tags `[staging]`
- Version 4 has tags `[dev]`

This passes testing and continues to the staging environment:

```
> apex deploy --alias staging
   • config unchanged          function=failure_alerts
   • code unchanged            function=failure_alerts
```

Current State: 
- Version 3 has tags `[staging]`
- Version 4 has tags `[dev]`

Expected State:
- Version 4 has tags `[dev, staging]`

**Comment by dekz** [comment]
I can side step the Noop by setting fake environment variables on each deploy stage, but this creates excess lambda versions.

**Comment by mthenw** [comment]
Thanks for reporting. That's right, we should update alias even though there are no changes in code or configuration.

**Comment by mthenw** [comment]
I've been thinking about this for a bit and I'm not sure how we should resolve that. Possible solutions:

1. Update alias every time alias version is not the latest version.
2. Compare configuration under alias with the latest version configuration and update only if those configs differs. 

@tj any preference?

**Comment by tj** [comment]
hmm if I understand correctly, sounds like we just maybe need a set of commands for alias CRUD. I think trying to add alias operations to deploy could be a little confusing. When I see those commands I don't really see a clear behaviour in mind, like oh that obviously does X.

If I run `apex deploy --alias tj` as dev-level isolation, I'd expect it to be a new release, so I'm not sure how we could have both there.

Maybe we're better off using "current" as we always have, and delegating all other alias operations to `apex alias`, but then we need more CRUD to grab versions etc. It would be more like `git tag` though, which could feel more intuitive.

**Comment by mthenw** [comment]
yeah, I was also think about what we have now as a "correct" but on the other hand would be cool to support mentioned use case. 

@dekz I'm removing this issue from upcoming release. Let's wait for more feedback.

**Comment by joshrtay** [comment]
@tj I agree. Deploying and aliasing seem pretty orthogonal. It would be cool if `apex alias` worked like `git tag`, though I think an explicit version number should be required rather than defaulting to $latest the same way `git tag` defaults to HEAD. 

+1 for `apex alias`

**Comment by tj** [comment]
I'd really love a way to associate version numbers with local releases / git sha's or something as well. As-is they're not very useful, you're just left wondering "wtf was in version 343"

**Comment by tj** [comment]
Maybe on `apex deploy` we have an optional `--message`, so it's almost like a git commit. We could store those somewhere and recall them when listing versions or rolling back etc. Or an option to tag locally to match the version, I dunno haha

**Comment by joshrtay** [comment]
Why don't you just add an implicit git sha alias with each deploy. Is there a limit on the number of aliases you can have?

**Comment by samstav** [comment]
@joshrtay I was curious about this for other purposes... I stopped at around 11k.

![apparently-no-limit](https://dl.dropboxusercontent.com/s/c4pu4agp55q0pms/aliaslimit.png)

**Comment by joshrtay** [comment]
@samstav Haha. Nice.

**Comment by mthenw** [comment]
@samstav nice one!

**Comment by tj** [comment]
wow hahaha. I've been wanting a better way to keep track of which have/have no been deployed, I definitely think we should have an inclusive way to add an alias (and retain `current`). I'd love to chuck the GIT SHA in there

**Comment by lhulet** [comment]
This is becoming a huge issue for me. Are there any workarounds. I have a "dev" alias and a "dev_test" alias. CircleCI first deploys and runs tests on "dev_test" lambda alias, then if the tests pass, it deploys to the "dev" alias. 

Unfortunately, I would have to make some sort of small change to the code before deployment in order to trigger the alias update.

What `apex deploy --alias *name*` should do is check the version for *name* and see if there are any changes, if there are, then either create a new version, or update alias to latest version (depending on if the latest version contains the same code being deployed).

**Comment by tj** [comment]
@lhulet yea I think we'd be safe to add the Qualifier and check for config/code changes to that specific alias. I'll mark this for the next release, I can't think of any downsides of doing so at the moment, happy to look at a PR as well if anyone gets to it before me, I don't use aliases often.

**Comment by diranged** [comment]
I vote for a new 'apex alias <desired alias> <source alias/LATEST>' command thats only job is to ensure that the desired alias points to the same version as the source alias, or points to LATEST.

With that in mind, you could easily have this flow:

'''
## CI deploys current alias on merge to master
$ apex deploy
'''

'''
## CI updates alias staging on merge to Staging branch
$ apex alias staging current
'''

'''
## after testing, user triggers update of production alias
$ apex alias production staging
'''

**Comment by diranged** [comment]
Bah -- typed on iPhone.. Clearly I can't discern the ticks and single quotes on this thing..

**Comment by DavidTPate** [comment]
I fixed the quotes @diranged

**Comment by DavidTPate** [comment]
@diranged I could see that being one way to fix this, but IMO it makes sense to have this in `apex deploy --alias <alias>` as I don't think it is a good workflow to have to go:

```bash
$ apex deploy
$ apex alias staging
```

If the `apex deploy --alias <alias` was updated so that it would apply the alias if it wasn't already applied then I think this would address your issue.

**Comment by diranged** [comment]
In a world where you only use two aliases - sure... But if you have many aliases and you want checks and balances before you update an alias, then you want the separate command that's explicit. In truth, I see supporting both models as important.

**Comment by samstav** [comment]
Why not both? I assume they could share code.

**Comment by tj** [comment]
So we'll have:

- `apex deploy` == current
- `apex deploy --alias stage` == stage
- `apex alias prod` == alias `prod` as `current`'s version
- `apex alias prod other` == alias `prod` as `other` (other alias or version)

Sound reasonable? 

A command for listing aliases would be nice too I suppose! I literally have only used `current` but I'll try and get this in sometime unless someone wants to take a stab at it.

**Comment by lhulet** [comment]
Maybe I'm missing something... but I don't think an `alias` command is necessary. As long as you have the correct code checked out that you want to upload to that alias, then `apex deploy --alias stage` would work fine, even if you have multiple stages.

For example: Let's say you have `dev` stage, `beta`, and `prod`

`dev` is currently at `$LATEST` version (#141).
`beta` is at version 100
`prod` is at version 38

You decide that you want to release your dev stage to beta, so you check out your `dev` branch, and run `apex deploy --alias beta`

APEX would then check to see if the code checked out is the $LATEST code (in this case it is), so it would add the alias `beta` to the $LATEST version.

Now: 

`dev` is currently at `$LATEST` version (141).
`beta` is at `$LATEST` version (141).
`prod` is at version 38

Make some changes to dev... so:

`dev` is currently at `$LATEST` version (150).
`beta` is at version 141.
`prod` is at version 38

You decide you want to release `beta` to `prod`, so you check out the `beta` branch and run `apex deploy --alias prod`

APEX then checks to see if the code == $LATEST, which it is not, so it uploads a new version, and sticks the `prod` alias on it.

So now you have: 

`dev` is at version 150
`beta` is at version 141
`prod` is at version 151

However, version 141 == version 151. Maybe that's a little weird. @diranged maybe you want to chime in on this?

**Comment by lhulet** [comment]
@tj We'll also need to deal with this error probably:

"Error: function auth: ResourceConflictException: Unable to delete version because the following aliases reference it: [current]
	status code: 409, request id: d196b309-6124-11e6-bc55-c7e8eeb30a1b"

If people start using aliases, this is going to happen... a lot. I think this error could be changed to a warning, and the code could continue to execute.

**Comment by inblueswithu** [comment]
I see there seem to be no change in apex behavior in v0.11.0 for alias from previous versions. Are we planning to do it in next release by any chance?

**Comment by tj** [comment]
#0bd97d606010648dfe2cbefbf2b21c40e51aa98b
