### ISSUE TITLE
Config inference for simple cases

### ISSUE THREAD

**Issue by tj** [apex/apex#38]
Uou should be able to just plunk an index.js in a dir and have it deploy fine. Pretty much just need to check ENOENT on the function.json open and fall back to checking for `{index.js,main.py,main.go}` files etc.

**Comment by mthenw** [comment]
Yeah, super useful for new users but what with iam role? It's hard to inference that.

**Comment by tj** [comment]
That could be in the project.json instead of re-specifying in each function.json (renamed lambda.json in the MF pull-request). That way unless you need access to something weird you can just have a "global" role

**Comment by tj** [comment]
closed by #63
