### ISSUE TITLE
Environment variables in python functions

### ISSUE THREAD

**Issue by jamesw201** [apex/apex#381]
testing a function with the function.json contents shown below:

{
    "environment": {
        "bucket": "my-cloud-bucket"
    }, 
    "handler": "index.handler", 
    "memory": 128, 
    "role": "arn:aws:iam::***************:role/lambda_basic_execution", 
    "runtime": "python2.7", 
    "timeout": 45
}

results in: 
{
  "errorMessage": "Unable to import module '_apex_main'"
}

**Comment by ryantuck** [comment]
what was the resolution here?

**Comment by jamesw201** [comment]
I found that I was mistaken in the case of this simple example so I closed it myself.
