### ISSUE TITLE
add support for `--env-file` command line flag

### ISSUE THREAD

**Issue by bhurlow** [apex/apex#387]
the `--set` flag works well for passing in a few vars. This gets unwieldy for more than a few vars tho.
Docker supports the `--env-file` flag which would load a file of VAR=value pairs. 

Would ya'll be open to adding something like this to apex? seems like the vars are already in a file somewhere in the lambda zip

**Comment by mthenw** [comment]
That's right env vars are stored in separate file inside zip but I'm not sure if we should add possibility to specify that file. I'm still +1 for possibility to specify `--env-file` though.

**Comment by tj** [comment]
Hmm my opinion there is that if you just have a big list of config (as json or similar), you might as well just `require('./config.json')` etc. Or use our "environment" object in project.json (this is what I do). I don't think `--set` is even very useful haha, other than for one-offs

**Comment by bhurlow** [comment]
@tj yea I see where you're coming from for sure. In my case supporting the .env style config would make certain configs portable between my docker projects and lambda projects so I could use the same file *sometimes*

**Comment by tj** [comment]
you could also have it in npm (if you're using node) or just in a Go package etc, but I prefer having a less "global" config, I've had a lot of issues with that in the past haha. At Segment we had one massive config package used by every program

**Comment by bhurlow** [comment]
I feel the struggle :) might just use `dotenv` instead

**Comment by brentsnook** [comment]
We'd love this feature right now - we worked around it by reading from a file and converting each line to --set flags but it is a bit ugly.

**Comment by tj** [comment]
I suppose another hack would be `--env $(cat myenv)` and use `foo=bar,bar=baz` in there. I can see how people would want to keep sensitive stuff out of project.json. 

I think I'm 👍 on it, otherwise people would have to symlink a shared config file into the functions I guess, bit more of a pain.

**Comment by reggi** [comment]
I'm stuck here too. I think a quick hacky fix would be to have a command that parses the `.env` file into `json` using `dotenv` and injects it into `project.json` then removes it after the command is written.

Then one could use the hooks :/

**Comment by tj** [comment]
would be cool to get this in there soon. Anyone have opinions on `foo=bar\nbar=baz` or just go with JSON? I think the former is probably the best, to match /etc/environment

**Comment by matthew-andrews** [comment]
an `--env-file` would certainly be the most useful for my team……  occasionally people put spaces into these env vars, which is proving to be a bit tricky to reliably pass through the CLI.

**Comment by reggi** [comment]
Also comments! I recommend json

**Comment by tj** [comment]
@matthew-andrews any opinion on flat file vs json?

**Comment by matthew-andrews** [comment]
i don't mind, `.env` is a nice standard but i know that it ultimately ends up as a `.env.json` file anyway so why not keep it as that all the way through.

**Comment by reggi** [comment]
What about allowing `function.json` and `package.json` to also be `js` then we could `let env = require('env.json')`. I know this isn't a great solution for those who don't want to use javascript, but it would allow room for an `env.json` file that could live outside of the `.json` and be ignored from git. This way we could have functions with their own scope of environment variables and not have to provide a global set.

**Comment by tj** [comment]
I like the idea of having an environment.json or similar in the dirs, that would play nice with hooks to load from external sources. For now I've added `--env-file` but I'll open an issue for files

**Comment by erdii** [comment]
Is this really implemented? I can't find `--env-file` in the docs and my apex installation (`v.0.14.0`) does not know this flag. :( What am I missing?
