### ISSUE TITLE
Generate new functions in existing projects

### ISSUE THREAD

**Issue by tlvince** [apex/apex#389]
Given an existing project, it'd be nice to be able to generate new functions following those that are produced by `apex init`.

Perhaps a new parameter to init would work for this, such as `apex init <function-name>`? Although that may be confused with naming a new project, so maybe behind a flag instead?

**Comment by mthenw** [comment]
Creating function dir is pretty straightforward, because it's just a dir inside `./functions`. Not sure why that would be helpful?

**Comment by morgondag** [comment]
```touch ./functions/yofile.js```

**Comment by tj** [comment]
Closing for now, we can probably revisit if things get more complicated but hopefully we can keep it simple enough that a quick `mkdir functions/foo && touch functions/foo/index.js` is good enough.

cheers

**Comment by tlvince** [comment]
I had in mind something that also copies in the [boilerplate index.js](https://github.com/apex/apex/blob/5ecaf1954301be367352e7eaa98fa25ce2fa38ef/boot/boilerplate/_boilerplate/functions/hello/index.js), but erring on the side of simplicity is never a bad thing ;)

**Comment by tj** [comment]
For that sort of thing I usually just have snippets in my editor since that's pretty easy for file-level boiler
