### ISSUE TITLE
Formatting occasionally lost in docs command

### ISSUE THREAD

**Issue by tlvince** [apex/apex#390]
Sometimes the the output of `apex docs` has formatting errors. For example, in hooks:

![screen shot 2016-05-02 at 16 31 29](https://cloud.githubusercontent.com/assets/323761/14957070/8516cf5a-1083-11e6-9186-22fd2647753a.png)

Notice "function’sdirectory". The [source file](https://github.com/apex/apex/blob/b6f48d7958ce115361bb4427bf1bd67ac3cfeb92/docs/hooks.md) doesn't have this issue.

I have the following set:

```
❯ echo $LESS
--quit-if-one-screen --no-init --RAW-CONTROL-CHARS --ignore-case
```

… but `LESS='' apex docs` doesn't seem to make any difference.

❯ apex version
Apex version 0.8.0

**Comment by mthenw** [comment]
Thanks for reporting. Looks like there is a new line sign.
