### ISSUE TITLE
Add tags to function.json

### ISSUE THREAD

**Issue by tj** [apex/apex#391]
This might be an alternative to #306, or possibly still useful regardless, but basically add some keywords/tags to the function.json after which you could deploy/delete/log on them. I think in most cases I'd still prefer grouping or globs but I'll let this sit here in case anyone has feedback!

I can't think of too many cases that wouldn't just be a single tag for the effective "group" anyway, though you could use this to hack envs as well: ``"tags": ["alerting", "prod"]` or per-user `"tags": ["api", "tj"]` and `apex deploy --tag tj`.

**Comment by mthenw** [comment]
Hahaha I was thinking about the same thing few days ago. Yeah, probably will not replace groups but still can be useful.

**Comment by tobyjoe** [comment]
Are you thinking of AWS resource tags? I know there's an [open thread](https://forums.aws.amazon.com/thread.jspa?messageID=691599) discussing the lack of tags in AWS Lambda...

**Comment by tj** [comment]
nah just tagging so we can group functions, but I think once AWS supports resource tagging we could just re-use these tags for those as well

**Comment by tj** [comment]
closing for now, globbing is great so far
