### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by tj** [apex/apex#4]
Haven't tried it out yet but since they have native support it should be fine. Seems pretty convoluted compared to the others, I'm not familiar with Java though so I'd probably do something unconventional.

**Comment by mthenw** [comment]
Just few notes here:
* Lambda supports Java via fat jar (maven-shade-plugin) or zip (gradle zip) (http://docs.aws.amazon.com/lambda/latest/dg/lambda-java-how-to-create-deployment-package.html)
* Java Handler function (http://docs.aws.amazon.com/lambda/latest/dg/java-programming-model.html)
