### ISSUE TITLE
Installer not working on Mac OSX

### ISSUE THREAD

**Issue by gmaclennan** [apex/apex#400]
`install.sh` currently does not work on Mac. The JSON returned by `curl -s https://api.github.com/repos/apex/apex/tags` does not currently seem to include newlines, which causes [this command](https://github.com/apex/apex/blob/master/install.sh#L42) to fail to actually correctly parse the latest tag. The grep/sed commands need updated. The current output on my machine:

```
$ LATEST=$(curl -s https://api.github.com/repos/apex/apex/tags | grep name | head -n 1 | sed 's/[," ]//g' | cut -d ':' -f 2)
$ echo $LATEST
v0.8.0zipball_url
```

**Comment by tj** [comment]
hmm I swear we fixed this once already, thanks for the report!

**Comment by mthenw** [comment]
similar issue https://github.com/apex/apex/pull/340

**Comment by gmaclennan** [comment]
`grep` and `sed` cross-platform a pain because Mac OSX doesn't include GNU versions. This works on Mac and Ubuntu in my testing:

```
curl -s https://api.github.com/repos/apex/apex/tags | grep -Eo '"name":.*?[^\\]",'  | head -n 1 | sed 's/[," ]//g' | cut -d ':' -f 2
```

**Comment by gmaclennan** [comment]
This and the original will both break if you use `:` in a tag name, but I don't think you would do that...

**Comment by mschinis** [comment]
`install.sh` works fine for me on OSX.

**Comment by gmaclennan** [comment]
Ok, very interesting... it would appear that for certain user-agent headers, github returns API calls without  any spacing or newlines. Try this to replicate the problem I was having:

```
curl -A 'My User Agent' -s https://api.github.com/repos/apex/apex/tags | grep name | head -n 1 | sed 's/[," ]//g' | cut -d ':' -f 2
```

For some reason I completely forget, I had a `.curlrc` setting `user-agent = "Mozilla/5.0 (Windows; U; MSIE 9.0; Windows NT 9.0; en-US)"`

The modified command I shared works whether the response includes linebreaks or not.

**Comment by tj** [comment]
oh wow, nice find

**Comment by wujiang** [comment]
The fix does not work for older version of `grep` (say latest OpenBSD 6.0 has `grep` 0.9). The error is `grep: repetition-operator operand invalid`. `grep -Eo '"name":.*[^\\]",'`  is good. I'll create a PR.
