### ISSUE TITLE
The RetainedVersions values are weird

### ISSUE THREAD

**Issue by tobyjoe** [apex/apex#407]
The semantics are getting a little weird for this one, IMO, but I wanted to file an issue to see if it's just me.

AFAIK, the origins of the ```if RetainedVersions == 0 { RetainedVersions = 10 }``` logic was due to the integer value of an unset ```RetainedVersions``` value defaulting to zero - effectively disabling the retention. It was also impractical/impossible to test (was it default? was it set by a user?), so the zero value was taken to mean "not set by user" as a rule.

Then, we overload the *real* value of zero with ```-1``` - an idiom which commonly means "unbounded" in many code bases - to mean zero.

Am I wrong that using the pointer value of ```Function.RetainedVersions``` would let us "reclaim" the zero value, because the pointer would be ```nil``` vs ```0``` when not explicitly set?

**Comment by tj** [comment]
👍 I haven't changed the default personally but I agree that a pointer would be good
