### ISSUE TITLE
apex upgrade can have cross-device link error

### ISSUE THREAD

**Issue by wujiang** [apex/apex#412]
When `/tmp` and `apex` binary are on different partition, [`os.Rename` ](https://github.com/apex/apex/blob/35063c0201d83cd711b1d746edf409a00db2d469/upgrade/upgrade.go#L71) will have this error

```
⨯ Error: rename /tmp/apex-upgrade /usr/local/bin/apex: cross-device link
```

I'm not sure how to resolve this.

**Comment by tj** [comment]
Ah I didn't think of that, hmm not sure either off-hand

**Comment by wujiang** [comment]
Hmm, maybe use the `cmdPath` instead of `tmpPath` for the download. (https://github.com/apex/apex/blob/6235d4a8b25901e23101ce372c3cb477ba23c3aa/upgrade/upgrade.go#L65)
