### ISSUE TITLE
Apex should inject environment as a tfvar 

### ISSUE THREAD

**Issue by JefStat** [apex/apex#422]
A nice to have would be the environment name as passed by apex to terraform. 

When using terraform modules with multiple environments and to avoid naming conflicts frequently the environment name is appended to the resource.  For example:
`main.tf`
```
variable "env" {}

module "iam" {
  env = "${var.env}"
  source = "../modules/iam"
}
```

`modules/iam`
```
variable "env" {}

resource "aws_iam_role_policy" "cloudwatchlogs_full_access" {
  name = "cloudwatchlogs_full_access_${var.env}"
  role = "${aws_iam_role.aw_loops_lambda.id}"
  policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "logs:*"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:logs:*:*:*"
        }
    ]
}
EOF
}
```

**Comment by tj** [comment]
Hmm with separate main.tf's per env that part would be a bit redundant I think, but definitely an easy add

**Comment by tj** [comment]
forgot to close, we have `apex_environment`
