### ISSUE TITLE
API Gateway example - 

### ISSUE THREAD

**Issue by nirving-versent** [apex/apex#423]
Hello! Please include the following when creating an issue:

  - Operating system: Macintosh
  - Version (`apex version`):  0.9.0

Been trying the API Gateway integration and hit an issue.

I had to set the following for 
https://github.com/apex/apex/blob/master/_examples/api-gateway/infrastructure/dev/api-gateway.tf

```
variable "apex_function_hello" {
  type="string"
  default="arn:aws:lambda:xxxx:xxxxxxx:function:xxxx_hello"
}
```

Without this the `infra deploy` would fail with
```
Errors:

  * 1 error(s) occurred:

* Required variable not set: apex_function_hello
```

Is there something missing from the example that does the lookup and sets the variable?

**Comment by tj** [comment]
Hmm I think that example might be incomplete, missing a project.json and it should be ./functions/hello/index.js

**Comment by nirving-versent** [comment]
@tj yes it seems an incomplete example.
I have tried (as documented here https://www.terraform.io/intro/getting-started/variables.html)
```
apex list --tfvars > terraform.tfvars
apex list --tfvars > infrastructure/terraform.tfvars
apex list --tfvars > infrastructure/dev/terraform.tfvars
```
Still no luck.

**Comment by nirving-versent** [comment]
Okay, I have figured out a way to get this to work.

1. `apex init`
2. `apex infra plan`
3. `apex infra apply`
4. `apex deploy`
5. Add in `infrastructure/dev/api-gateway-iam.tf` and `infrastructure/dev/api-gateway.tf`
6. `apex infra plan`
7. `apex infra apply`

Not sure why the order is important as of yet, but it gets around all the issues.

if I do
1. `apex init`
2. Add in `infrastructure/dev/api-gateway-iam.tf` and `infrastructure/dev/api-gateway.tf`
3. `apex infra plan`
then the following error occurs.
```
Errors:

  * 1 error(s) occurred:

* Required variable not set: apex_function_hello
   ⨯ Error: exit status 1  
```

**Comment by tj** [comment]
Ah right, the order is because the function won't exist yet, but you also need the terraform role to deploy the function. Not the best UX right now, I'm not sure if there's anything we can really do there but I'll definitely look into it. 

This issue #377 details the same problem with bootstrapping, it's not too bad if you start from `apex init` and add to it over time but to start entirely new envs.. yep haha, not great.

**Comment by tj** [comment]
removed that example for now since it was incomplete

**Comment by lpil** [comment]
Hi @tj. I think it'd be great to have an example of this again. Would you be open to a new example if it was more complete?

**Comment by hpgmiskin** [comment]
I was looking into how to manage API Gateway with apex (I know there is apex up which makes it a lot simpler process) however like the fine grained control on terraform.

For anyone like me who would like to look back [here is a link to the incomplete example](https://github.com/apex/apex/tree/b8b9550d466b61ac824fd13a9931160f4c8431a8/_examples/api-gateway)
