### ISSUE TITLE
Fail to install on Amazon Linux AMI

### ISSUE THREAD

**Issue by Peilun0912** [apex/apex#425]
I execute `curl https://raw.githubusercontent.com/apex/apex/master/install.sh | sh` on Amazon Linux AMI 2016.03, it exited without error messages but I can't run `apex` command.

**Comment by mthenw** [comment]
Thanks for reporting. The problem is that `/usr/local/bin` is owned by root so default user can't put files there.

**Comment by zeliard** [comment]
how about sudo?
curl https://raw.githubusercontent.com/apex/apex/master/install.sh | sudo sh

**Comment by Peilun0912** [comment]
@zeliard: Your solution works, thanks!

I'm going to check if there are other ownership related problems exist.

**Comment by mooyoul** [comment]
@tj @mthenw Should we document sudo required on installation?

**Comment by tj** [comment]
We could mention it maybe, but I think default of `| sh` is more trust-worthy haha. I always chown /usr/local personally

**Comment by mooyoul** [comment]
@tj Agree. Keep current installation snippet and just mention about that at below snippet would be great. I'll get it done :)
