### ISSUE TITLE
Error: error opening function hello: Role: zero value

### ISSUE THREAD

**Issue by reggi** [apex/apex#427]
I just got up and running with `apex init` and I'm seeing the following error when I run `apex deploy` and `apex list`.

```
Error: error opening function hello: Role: zero value
```

**Comment by reggi** [comment]
Seems I needed to run `apex infra apply` first

**Comment by smrutiranjantripathy** [comment]
@reggi I'm getting the same error .How do u resolve the error ?

**Comment by sekitaka-RBS** [comment]
@smrutiranjantripathy hi, I had same error. I deleted empty folder which is functions sub directory, then fix it.
