### ISSUE TITLE
apex ignores function.json handler key for python

### ISSUE THREAD

**Issue by ryantuck** [apex/apex#433]
- OS X 10.11.4
- apex version v0.9.0
- runtime: python2.7

in `function.json`:

```
{
    "handler": "main.do_stuff"
}
```

after I deploy my function, I see this in the console:

![image](https://cloud.githubusercontent.com/assets/1762274/15689142/9d7c85ce-274b-11e6-8268-f72d8fd00f79.png)

This issue seems to be newly introduced after upgrading to v0.9.0

**Comment by ryantuck** [comment]
downgrading to v0.8.0 resolves this issue for me.

**Comment by mthenw** [comment]
It has been fixed after 0.9.0 release. You can try master branch version.

BTW Apex wraps your function with another function and register that wrapper function to Lambda so checking web console will always indicate different func.

**Comment by mthenw** [comment]
https://github.com/apex/apex/pull/424

**Comment by ryantuck** [comment]
awesome, thanks!

actually, for python, the console does indicate the correct handler name assuming it gets uploaded properly:

![image](https://cloud.githubusercontent.com/assets/1762274/15689740/70617e0c-274e-11e6-8be4-e06c4af66386.png)
