### ISSUE TITLE
Error: json: cannot unmarshal number into Go value of type string

### ISSUE THREAD

**Issue by ipmsteven** [apex/apex#436]
In my `project.json` file I have the config like the following: 
```javascript
{
    name: xxx,
    description: xxx,
    memory: 128,
    timeout: 10,
    role: arn:aws:iam::xxx:role/xxx,
    defaultEnvironment: dev,
    environment: {
      AWS_REGION: "us-west-2",
      DEFAULT_TOKEN_SIZE: 12,
    }
  }
```
and when I run `apex deploy`, I get the error says `json: cannot unmarshal number into Go value of type string`, it turns out that I have to make a string value for `DEFAULT_TOKEN_SIZE` instead of a integer.

I am wondering it apex should support the integer value for environment config inside `project.json`

**Comment by tj** [comment]
I'll make sure this gets documented, but just like env vars on the command-line can only be strings, it's the same case here. For example `DEFAULT_TOKEN_SIZE=12 ./myprogram` would just be "12"
