### ISSUE TITLE
How can I change the template of index.js

### ISSUE THREAD

**Issue by davyzhang** [apex/apex#438]
If you have a bug report please let us know the following:

  - Operating system
MacOSX
  - Version (`apex version`)
Apex version 0.9.0
 
I am trying to implement a background daemon process which has no need to emit json outputs, so I think maybe I can change the template or apex can give an option to turn json parse off

**Comment by tj** [comment]
Hey!

What's the template you're referring to? I'm not quite sure what you mean

**Comment by davyzhang** [comment]
Hey!

Sorry for the confusion, I've noticed that in the index.js there are some lines:
```javascript
out.on('data', function(line){
  if (process.env.DEBUG_SHIM) console.log('[shim] parsing: %j', line)
  var msg = JSON.parse(line)
  ctx.done(msg.error, msg.value)
})
```
But the problem is when I try to run log something not "JSON" format to the stdout, this function will surely jump out with exceptions

So, I think if apex can have a way to specify a custom index.js file and zipp it with ohter files

currently I logged everything to stderr with golang's log, and keep stdout as clean as possible

**Comment by tj** [comment]
Ah yep, the stdout _has_ to be JSON, stderr is recommended for logging or debugging. I'm not sure I understand the use-case of responding with something else. Even if you wanted to respond with a string you could just `return "something", nil` in Go and it'll be serialized as JSON

**Comment by davyzhang** [comment]
Thanks for the clarification, I pretty much understand how things going there. But since I've met a similiar problem before I suggest surround json parsing code with try catch, some go lang lib might print their own errors which not follow the rule.

below is code I've used for another project
```javascript
		// check for newline ascii char 10
		if (data.length && data[data.length-1] == 10) {
			try{
				var output = JSON.parse(data.toString('UTF-8'));
				data = null;
				done(null, output);
			}catch(err){
				console.log("error when trying to decode:"+data.toString('UTF-8'));
				done(err);
			}
		};
```

**Comment by tj** [comment]
True true, I'll close for now but if it comes up again I'll add a try/catch. I haven't noticed any packages logging to stdout

thanks!
