### ISSUE TITLE
No valid credential sources found for AWS Provider.

### ISSUE THREAD

**Issue by reggi** [apex/apex#444]
If you have a bug report please let us know the following:

  - Operating system (OSX 10.11.4 (15E65))
  - Version (Apex version 0.9.0)
 
I'm having an issue below.

* I've cloned this repo
* `cd` to `/_examples/babel-browserify`
* run `apex init`

Then `apex infra plan`

```
thomasreggi@zx:babel-browserify$ apex infra plan
Refreshing Terraform state prior to plan...

Error refreshing state: 1 error(s) occurred:

* 1 error(s) occurred:

* No valid credential sources found for AWS Provider.
  Please see https://terraform.io/docs/providers/aws/index.html for more information on
  providing credentials for the AWS Provider
   ⨯ Error: exit status 1     
thomasreggi@zx:babel-browserify$ echo $A
$AWS_DEFAULT_PROFILE         $AWS_PROFILE                 $AWS_REGION                  $Apple_PubSub_Socket_Render  
thomasreggi@zx:babel-browserify$ echo $A
$AWS_DEFAULT_PROFILE         $AWS_PROFILE                 $AWS_REGION                  $Apple_PubSub_Socket_Render  
thomasreggi@zx:babel-browserify$ echo $AWS_PROFILE
zxventures
thomasreggi@zx:babel-browserify$ echo $AWS_DEFAULT_PROFILE
zxventures
```

However I have `AWS_PROFILE` set.

I'm not sure if terraform supports `$HOME/.aws/config` seems like they support `$HOME/.aws/credentials`.

https://www.terraform.io/docs/providers/aws/index.html

**Comment by tj** [comment]
most of the examples don't use Terraform, so there's no `apex infra *`

**Comment by tj** [comment]
adding some Readme's to the examples, but soonish I'd like to have `apex init` or similar bootstrap existing projects properly

**Comment by reggi** [comment]
I'm still getting this issue :/
```
thomasreggi@zx:estore-api-apex$ apex deploy post-to-requestbin
   ⨯ Error: function post-to-requestbin: NoCredentialProviders: no valid providers in chain. Deprecated. 
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

Why isn't apex reading the profile I have set in my bash?

**Comment by reggi** [comment]
I had some wonky settings deleted `~/.aws` and removed any global env vars.

Getting something better now.

```
thomasreggi@zx:apex$ apex deploy post-to-requestbin
   • creating function         function=post-to-requestbin
   ⨯ Error: function post-to-requestbin: AccessDeniedException: Cross-account pass role is not allowed.
	status code: 403, request id: 344a4b22-2eae-11e6-9f91-973e8df45f0b
```

**Comment by reggi** [comment]
Was using ur arn :/

#justLearnedSomething

**Comment by tj** [comment]
hahaha god the errors from the SDK are pretty cryptic sometimes, the "no valid providers in chain" one definitely needs fixing
