### ISSUE TITLE
Required variable not set: apex_function_hello

### ISSUE THREAD

**Issue by reggi** [apex/apex#445]
If you have a bug report please let us know the following:

  - Operating system (OSX 10.11.4 (15E65))
  - Version (Apex version 0.9.0)
 
I'm having an issue below.

* I've cloned this repo
* `cd` to `/_examples/api-gateway`
* run `apex init`

Then `apex infra plan`

```
thomasreggi@zx:api-gateway$ apex infra plan
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * 1 error(s) occurred:

* Required variable not set: apex_function_hello
   ⨯ Error: exit status 1     
```

**Comment by tj** [comment]
example is busted :( I'll remove it for now until I have time to fix
