### ISSUE TITLE
Webpack: import local modules

### ISSUE THREAD

**Issue by eltoro** [apex/apex#446]
I'm using apex 1.0.0 on a mac with the webpack example setup. I have a directory called shared at the project level that I have some custom modules in. How do I get webpack to bundle the directory? When I build I get 'cannnot find module...'. I tried this:

```
resolve: {
    modulesDirectories: ['node_modules', 'shared'],
    extensions: ['', '.js', '.jsx']
},
```

And trying to:

`import {myModule} from '../../shared/my-module.js';`

The build is not getting the shared directory. Is there a way to do this without a symlink?

**Comment by tj** [comment]
The `build` commands are relative to the function's directory, so it looks like you might need `../shared`. I have really limited knowledge about webpack but let me know if that helps!

**Comment by eltoro** [comment]
Turned out to be pretty easy after digging through webpack's docs. I added this to the config file:

```
resolve: {
    root: [
      path.resolve('../../shared')
    ]
  }
```

and then imported the module like it was installed with npm.
