### ISSUE TITLE
Python dependencies management suggestion

### ISSUE THREAD

**Issue by zen4ever** [apex/apex#449]
Currently Lambda requires you to install Python packages into the `functions/<function_name>/` folder
So common pattern is to have `functions/<function_name>/requrements.txt`
and then run 

```bash
pip install -r functions/<function_name>/requrements.txt -t functions/<function_name>/
```

One of the problems with that is that then third party packages get mixed with your function code.
You either have to write a very elaborate .gitignore listing individual package names, or commit everything into your version control. Both solutions are not very flexible.

One way around it, is to install your modules into a separate folder inside the function folder

```bash
pip install -r functions/<function_name>/requrements.txt -t functions/<function_name>/lib/
```

And then add the following lines to the function

```python
import sys
sys.path.insert(0, "./lib")
```

Then the `lib/` folder can be safely added to `.gitignore`

Is it possible to add those lines to the `_apex_main.py`?

**Comment by tj** [comment]
Hmm hard for me to comment since I'm not used to python idioms, but it sounds a little too opinionated to be at the apex level. It would definitely be a bit of a hack but you could probably use the `build` hook to do something like `cat ../prelude.py index.py > main.py` if you wanted to sneak in some project-wide logic

**Comment by zen4ever** [comment]
ok, then is it possible to add some hooks to be able to modify _apex_main.py via project.json settings?

**Comment by zen4ever** [comment]
`cat ../prelude.py index.py > main.py` seems manageable for this particular case though

**Comment by tj** [comment]
yeah maybe in the future some sort of extensible templates, but it would definitely be preferable to avoid that

**Comment by ryantuck** [comment]
@zen4ever that's a clever hack - did you ever find a better one?

i ran into an issue where i used `from __future__ import print_function` in my `main.py` and the compiler complained:

```
Syntax error in module 'index': from __future__ imports must occur at the beginning of the file (index.py, line 4)
```

my fix was to use python2.7 `print` instead in this case, but would be ideal to resolve in a more robust way.

**Comment by zen4ever** [comment]
we've ended up writing our own python-specific tool for Lambda deployment
