### ISSUE TITLE
Deploying nested folders

### ISSUE THREAD

**Issue by reggi** [apex/apex#459]
What are the thoughts on supporting folder structures within functions?

`apex deploy hello/world`

**Comment by tj** [comment]
Dup of #306. It might happen, but it would require that we remove our runtime inference features. Removing that might be fine, I've found in most cases I have a function.json file anyway.

That said I think the flat layout is really simple, I really like that personally, similar to how most react apps have a single ./components directory. Globbing mitigates most of the issues managing the flat list, ex `apex deploy check_*` deploys my _reporter,_processor,_queuer functions. Globbing is actually _more_ powerful in some ways, `apex deploy *_reporter` to deploy check_reporter and alert_reporter.
