### ISSUE TITLE
Golang runtime custom clean hook not working

### ISSUE THREAD

**Issue by dxjacob** [apex/apex#461]
Looks like its getting overridden:
https://github.com/apex/apex/blob/3da45b5d83e9aafff5efcaf709c4970dd8089a9b/plugins/golang/golang.go#L33

Suggest an empty string check before setting to the default like the build hook a few lines up:
https://github.com/apex/apex/blob/3da45b5d83e9aafff5efcaf709c4970dd8089a9b/plugins/golang/golang.go#L27-L29

**Comment by tj** [comment]
sounds good to me!
