### ISSUE TITLE
function.json ignored when using default environment

### ISSUE THREAD

**Issue by w-vi** [apex/apex#467]
If `-env` not provided the default is appended to `function.json` unlike the `project.json`. In my case `dev` is the default and I do not specify it when `apex build myfunc -l debug > out.zip` but it looks for `function.dev.json` and read `project.json`. I thought that those work the same way. Is this a bug or intended behaviour?

Relevant bit of [function.go](https://github.com/apex/apex/blob/master/function/function.go#L116). The environment is not empty, it seems that it is never empty as the default if specified is used.

  - __Operating system__: Linux 
  - __Apex Version__: 0.10.2

**Comment by tj** [comment]
hmm sounds like a bug, I think in any case it would be sane to default to function.json if that's the only thing available

**Comment by w-vi** [comment]
Yes `deafultEnvironment` from `project.json` file gets propagated to the `Function.Open(environment string)`

**Comment by tj** [comment]
Gotcha cool thanks, definitely an oversight
