### ISSUE TITLE
connect to mongodb with mongoose, outside of the handle

### ISSUE THREAD

**Issue by elgubenis** [apex/apex#469]
hi, awesome effort so far, I still try to understand how the stateless handle function is working,
when I write a mongoose.connect or mongoose.createConnection outside the handle, the execution times out, (even though with loggly i can verify that mongoose connected successfully) i tried raising the timeout, but thats not it, its seems like the mongoose connection is blocking further execution of code, any idea on how i could accomplish connectiing to mongodb (with or without mongoose) without opening a new connection on every handle/request?

**Comment by lhulet** [comment]
db.close() solves this.

**Comment by elgubenis** [comment]
can you be more explicit? sounds like you refer to opening and closing a connection per request, thats what should not be done afaik.

**Comment by lhulet** [comment]
^See my edit.

**Comment by elgubenis** [comment]
thats maybe why all the examples use dynamo, huh?

**Comment by tj** [comment]
I use connections to postgres outside of the handler, I imagine it should be fine but I can't really comment on Mongo

**Comment by mooyoul** [comment]
You should close mongodb connection when your job was done. (@lhulet commented that) unless connection closing, Node process will not be exited until mongo connection is not closed.

so It's not a Apex or AWS lambda's problem. i'm using node-mongodb-native on my Lambda function with apex over 2 weeks. Everything  works great.

**Comment by elgubenis** [comment]
@mooyoul do you have the working sample which you were talking a month ago public? or would you mind to share?

**Comment by cpsubrian** [comment]
@mooyoul Also trying to get node-mongodb-native working via apex and not having luck. Whats the process? Note: I'm building with webpack but I've tried including `node_modules` in the zip and even tried to prebuild on a linux machine and I get the following error when I invoke:

```
$ apex invoke quotes_requests_get
   ⨯ Error: function response: Cannot find module "."
```
