### ISSUE TITLE
Unexpectedly not receiving input to apex invoke

### ISSUE THREAD

**Issue by eldondevcg** [apex/apex#473]
When calling apex invoke, this works: 
`echo  "{\"key\":\"value\"}" | apex invoke myfunc -L`
This does not seem to work, but I would expect it to:
`apex invoke myfunc -L <(echo  "{\"key\":\"value\"}")` 

Is this expectation valid? I suppose this only works when the program accepts a file descriptor as a cli arg, but that seems reasonable here, especially since the comparable ` < request.json ` works.

If you have a bug report please let us know the following:

  - __Operating system__:
`Linux vagrant-ubuntu-trusty-64 3.13.0-87-generic #133-Ubuntu SMP Tue May 24 18:32:09 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
 A mostly stock ubuntu vagrant virtualbox VM running on an osx host
  - __Apex Version__:

0.10.2 - installed via `go get`

When appropriate please also paste the debug log output using `-ldebug` or `--log-level debug`.

**Comment by tj** [comment]
The equivalent of `< request.json` here would be something like `apex invoke myfunc -L < <(echo '{ "foo": "bar" }')`, since `apex invoke <name>`  doesn't (currently) accept a file argument

**Comment by eldondevcg** [comment]
I find myself reusing the same invocations repeatedly as I develop new functions. having invoke accept a filename as json input might be convenient for some use cases.

**Comment by tj** [comment]
Might consider it, I left it out since it's only the one extra character for redirection but feel free to open a feature request if that gets annoying
