### ISSUE TITLE
Noob - trying to install Apex on Mac OSx -- getting error

### ISSUE THREAD

**Issue by kennethchapman99** [apex/apex#474]
Ran this simple command:
sudo curl https://raw.githubusercontent.com/apex/master/install.sh | sh

Got back:
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    21  100    21    0     0     73      0 --:--:-- --:--:-- --:--:--    73
sh: line 1: 400:: command not found

No idea what to do next... am just trying to get Apex installed to write an AWS Lambda function that talks to Amazon Echo

**Comment by matthew-andrews** [comment]
try this:-

```
curl -sfL https://github.com/apex/apex/releases/download/v0.10.2/apex_darwin_386 -o /usr/local/bin/apex && chmod +x /usr/local/bin/apex
```

**Comment by tj** [comment]
Looks like your link is wrong somehow, it should be https://raw.githubusercontent.com/apex/apex/master/install.sh, or what @matthew-andrews mentioned :D

**Comment by kennethchapman99** [comment]
So I ran that - seemed to work, nothing printed on the terminal...   tried looking for Apex commands on my system but 'command not found'

Is there a walk-through or documentation for setting up Apex I can review?  haven't found it...

**Comment by DavidTPate** [comment]
@kennethchapman99 You can find the instructions here: http://apex.run/#installation

**Comment by juliangruber** [comment]
try adding `/usr/local/bin/` to your `$PATH`

**Comment by tj** [comment]
If `/usr/local/bin/apex version` has some output then it's definitely a $PATH issue, been a while now but I'm pretty sure /usr/local/bin is in $PATH by default

**Comment by juliangruber** [comment]
at least in osx it is

**Comment by talolard** [comment]
I have the same problem on Ubuntu

**Comment by kennethchapman99** [comment]
So /usr/local/bin is in my $PATH 
I figured out how to see /usr/local/bin in Finder -- and see no references to Apex

Running 'Apex version' in that directory in Terminal gives me 'Command not found'

So it didn't install?  The instructions just have a single statement that I already ran, and i'm trying to find other issues but haven't

Is there another way to install?

**Comment by juliangruber** [comment]
@kennethchapman99 so running

```bash
$ sudo curl https://raw.githubusercontent.com/apex/apex/master/install.sh | sh
```

finished and outputted nothing, but there's also nothing in /usr/local/bin?

**Comment by kennethchapman99** [comment]
Yes - here is a screencap of my terminal session (I'm in /usr/local/bin)

![image](https://cloud.githubusercontent.com/assets/20187836/16778139/92584394-483a-11e6-9775-4352415a5b43.png)

**Comment by juliangruber** [comment]
@kennethchapman99 hm, interesting! i guess the most efficient right now would be for you to debug the install script. 

oh, what shell do you use? and this is osx, right?

**Comment by DavidTPate** [comment]
@kennethchapman99 The only thing that I see in the Install script is there no `else` for a system that isn't `Darwin`, `Linux` or `OpenBSD`. I added an else there just to make it do `exit 1` and print out the info if you want to try that.

It's available here: https://gist.githubusercontent.com/DavidTPate/a6f5a17cb1f9c2529f84e4cd65b5f75c/raw/cc8908e7096a80d1a5b13846262e43e3f0306abc/apex_install.sh

Please take a look before hand at what it does, I'm not nefarious but want you to be certain of what you are running :)

To run this it would be 

```bash
$ sudo curl https://gist.githubusercontent.com/DavidTPate/a6f5a17cb1f9c2529f84e4cd65b5f75c/raw/cc8908e7096a80d1a5b13846262e43e3f0306abc/apex_install.sh | sh
```

It does the same thing as the install script but adds that extra `echo`

**Comment by kennethchapman99** [comment]
Haha, I'm not sure if I'm using a shell?  
 I'm just using the Terminal to do the Apex install (?)

**Comment by kennethchapman99** [comment]
Still got nothing back after running that

![image](https://cloud.githubusercontent.com/assets/20187836/16779796/bc92173c-4841-11e6-80c7-cabf67a87afa.png)

**Comment by mooyoul** [comment]
@kennethchapman99  `curl` will be executed in root via `sudo`, but piped `sh` will **NOT** executed in root.
I'd suggest using `curl https://raw.githubusercontent.com/apex/master/install.sh | sudo sh`.

**Comment by wontwon** [comment]
@kennethchapman99 were you able to get Apex working on your machine?

**Comment by kennethchapman99** [comment]
No, I ended up writing my own stuff in node


-KC

**Comment by tj** [comment]
FWIW if anyone has an issue you can just curl the binary with `-o /usr/local/bin/apex` and `chmod +x` that file
