### ISSUE TITLE
Clarify order of operations in documentation

### ISSUE THREAD

**Issue by gravyboat** [apex/apex#476]
I ran into this issue while running Apex as a new user, on http://apex.run it isn't clearly explained that you MUST `apex deploy` prior to `apex invoke hello`. This however is explained much more clearly in the README example: https://github.com/apex/apex#example. Change wise I would propose both a note on the invoke section noting you need to deploy first, as well as clarifying these steps on http://apex.run.

**Comment by tj** [comment]
Ah good call, I'll make note that invoking is non-local
