### ISSUE TITLE
[feat] use pre-built zip

### ISSUE THREAD

**Issue by andreineculau** [apex/apex#480]
I have a few issues with the current flow that revolve around building and deploying the zip content:
1. it is good practice to first build, then test, then deploy. Currently I think the only way to do that is to build and redirect into a zip file. But then the deploy command will re-build the zip in memory and push it to AWS, meaning it's not a deterministic operation (i.e. it's possible we tested ver A of the zip, things changed, we upload ver B of the zip)
2. even if I close an eye on that, we still waste resources for building the ~same zip twice
3. we already have a process to zip the necessary files actually, and couple with the above, we would also skip using the apex hooks

I believe all the above are linked to the missing feature of using a pre-built zip, thus the feature request.

**Comment by tj** [comment]
Hmm I think resolving the publishing mentioned in the other issue would be a better way to solve this personally

**Comment by andreineculau** [comment]
you mean #482 ? that's rather different I think. To be clear, there is no way to test what ends up in the zip before deploying, and without building the zip twice.

**Comment by tj** [comment]
Oh see, that's a bit of a weird use-case. You could still sanity-check with `apex build`, but beyond that I'm not really sure about having a pre-built zip feature

**Comment by andreineculau** [comment]
So "Build once, deploy many" is a weird use-case?

On Thu, Jul 14, 2016 at 3:04 AM, TJ Holowaychuk <notifications@github.com>
wrote:

> Oh see, that's a bit of a weird use-case. You could still sanity-check
> with apex build, but beyond that I'm not really sure about having a
> pre-built zip feature
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/apex/apex/issues/480#issuecomment-232529688>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AArOQcUuKqaEZnW1i6PslUTbzUwI5q_Yks5qVYsugaJpZM4JJpHl>
> .
>



-- 
andreineculau.com <http://www.andreineculau.com>

**Comment by tj** [comment]
I've never wanted to unit-test the contents of my zips, happy to consider it if lots of people want to do this for some reason but otherwise I'm -1 personally

**Comment by thewillhuang** [comment]
@andreineculau could use apex hooks to run your unit tests? like so

```bash
  #project.json or function.json
  "hooks": {
    "build": "npm test; ...;"
    "clean": "..."
  }
```

**Comment by tj** [comment]
I actually wouldn't mind this now for multi-region stuff, I just re-build each time but that ends up being slow with Go's build times

**Comment by andreineculau** [comment]
@thewillhuang you're missing the point. Build first, store artifact, then use n-times (test, deploy, etc).
