### ISSUE TITLE
Hooks not working for java runtime

### ISSUE THREAD

**Issue by akranga** [apex/apex#491]
When building java runtime function, then hooks not triggered. 

Steps to reproduce:
1. Create `function.json` file: 
```json
{
	"runtime" : "java",
	"hooks": {
		"build": "./gradlew jar",
		"clean": "./gradlew clean"
	}
}
```

2. Run `apex deploy <fn_name>`
3. See error: `Error: function ui: Expected jar file not found`
Expected Result:
Gradle build should be triggered prior function deployment

**Comment by tj** [comment]
Hmm the java plugin was contributed, looks like you're hitting https://github.com/apex/apex/blob/master/plugins/java/java.go#L70. I don't know anything about java idioms unfortunately so I can't comment on what might be wrong there, `-l debug` might give you some more insight for what it's trying to find

**Comment by akranga** [comment]
Yeah, I was running with -l debug. Pushed PR with pretty trivial fix

**Comment by tj** [comment]
awesome thanks for the fix!

**Comment by noerremark** [comment]
I had a similar issue. Turns out that maven wasn't installed...
