### ISSUE TITLE
Add support for Node v6 to Lambda using Apex

### ISSUE THREAD

**Issue by FGRibreau** [apex/apex#493]
From what I see we could perfectly add Node v6 support to Apex right?
- using `Shim=true`, "main" would be node v6 process built with the right arch
- `shim/index.js` could [forward parameters](https://github.com/apex/apex/blob/35063c0201d83cd711b1d746edf409a00db2d469/shim/index.js#L15)
- anything else that should be changed?

**Comment by tj** [comment]
Hmm yeah I suppose you could! Looks like the binary is around 25M. I like it, very meta haha

**Comment by mantoni** [comment]
Well, ES6 supports a long list of new language features that where not part of node 4 (http://node.green has all the details). Currently, Node 4 is 57% complete on ES6 while Node 6 is at 95%.

I'm currently pre-compiling my node code down to Node 4 compatible code to be able to use these features. While this is fine, I was wondering if the Node 6 performance improvements make it worth to launch a custom Node version.

I'm sure AWS will support Node 6 once it becomes LTS, but there's always a next version ... 🚀

**Comment by kopertop** [comment]
Perhaps a better solution would be to add pre-compilation support directly in the deploy. This could probably be done with a pre-deployment hook.

It may be worth benchmarking what the difference in speed would be between running Node v4 native vs a shimmed version of Node v6.

**Comment by DavidTPate** [comment]
@kopertop There's support baked into Apex for hooking into the build process. You can see an example of [Node + Babel + Webpack](https://github.com/apex/apex/tree/master/_examples/babel-webpack) in the examples directory along with other examples.

**Comment by kopertop** [comment]
Now that AWS supports 6.10, how do I specify that in Apex? I tried using nodejs6.10 but it gave me a "ZERO_RESULTS" error.

**Comment by tj** [comment]
didn't have time to test but https://github.com/apex/apex/releases/tag/v0.13.1 should be fine now

**Comment by kopertop** [comment]
I can confirm this is working. Thanks for the quick fix!
