### ISSUE TITLE
Subfolders for AWS Lambda function

### ISSUE THREAD

**Issue by jelliotartz** [apex/apex#494]
Hi,

We are trying to create subdirectories within the functions directory in Apex. Is this currently possible? If not, it would be a handy feature to have!

Operating system: OS X 10.11.4
Apex Version: 0.10.2

Any help you can provide is greatly appreciated!

If you have a bug report please let us know the following:

  - __Operating system__: 
  - __Apex Version__: 

When appropriate please also paste the debug log output using `-ldebug` or `--log-level debug`.

**Comment by tj** [comment]
Hey! You can see some discussion #306 for the same thing and a bit #459. TL;DR is: maybe some day, for now [globbing](http://apex.run/#deploying-functions) is a really simple and even more powerful in some ways. We'd have to cut out a feature or two to add sub-dirs support.

Closing as a duplicate

**Comment by jelliotartz** [comment]
Great, thanks for pointing me in the right direction!
