### ISSUE TITLE
InternalFailure: status code 500 on initial invoke hello

### ISSUE THREAD

**Issue by wwwroth** [apex/apex#497]
Upon initial install of Apex and config, I deployed my functions to AWS successfully but I'm getting the following error when invoking hello for the first time. Running OSX 10.11.5 and Apex 0.10.2.

```
☁  apex  apex invoke hello --log-level debug
   • loading functions in functions
   • loading function in functions/hello
   • inferring runtime         function=hello
   • inferred runtime          function=hello runtime=nodejs4.3
   ⨯ Error: function response: InternalFailure:
	status code: 500, request id: 516489b9-4ded-11e6-8762-ff23d693816d
```

Also, here's my project.json
```
{
  "name": "apex-playground",
  "description": "apex",
  "memory": 128,
  "timeout": 5,
  "role": "arn:aws:iam::***:role/apex-playground_lambda_function",
  "environment": {}
}
```

**Comment by tj** [comment]
I keep seeing AWS notifications on Twitter, it may just be them having a problem right now. Probably not much we can do for a 500

**Comment by wwwroth** [comment]
Ran it again and it seems to be working. Must have been due to AWS outages. Thanks!
