### ISSUE TITLE
Getting "index out of range" error after adding a new function.

### ISSUE THREAD

**Issue by jadudm** [apex/apex#498]
OS: Amazon AMI (Linux)
Apex version: 0.10.2

I created a project, deployed, and invoked: worked.

I added a new folder under "functions" called "goodbye". In this folder, I put the following function.json:

```
{
  "description": "Say goodbye",
  "runtime": "python",
  "handler": "handle",
  "memory": 128,
  "timeout": 5,
  "region": "aws-east-1",
  "role": "arn:aws:iam::NUMBER:role/Echo_lambda_function"
}
```

I copied the role from "project.json" into the "function.json" just to see if it would help. It did not. (I was grasping.)

I also included "index.py", which was also (at various points) named "main.py" and "funs.py".

```
def handle (event, context):
    return {"RESULT" : "GOODBYE"}
```

Then, I tried to run "apex deploy", and received the following. My best guess has to do with notions of "LATEST" and rollback, but... 

This dumps out as follows:

```
[ec2-user@ip-something MICAEcho]$ apex deploy
panic: runtime error: index out of range

goroutine 9 [running]:
panic(0xb540e0, 0xc82000e070)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/apex/apex/plugins/python.(*Plugin).Build(0x10a0948, 0xc82006b340, 0xc820141aa0, 0x0, 0x0)
	/Users/tj/dev/src/github.com/apex/apex/plugins/python/python.go:68 +0x4aa
github.com/apex/apex/function.(*Function).hookBuild(0xc82006b340, 0xc820141aa0, 0x0, 0x0)
	/Users/tj/dev/src/github.com/apex/apex/function/function.go:723 +0x184
github.com/apex/apex/function.(*Function).Build(0xc82006b340, 0x0, 0x0, 0x0, 0x0)
	/Users/tj/dev/src/github.com/apex/apex/function/function.go:530 +0x133
github.com/apex/apex/function.(*Function).BuildBytes(0xc82006b340, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/tj/dev/src/github.com/apex/apex/function/function.go:509 +0x5c
github.com/apex/apex/function.(*Function).Deploy(0xc82006b340, 0x0, 0x0)
	/Users/tj/dev/src/github.com/apex/apex/function/function.go:183 +0x8b
github.com/apex/apex/project.(*Project).Deploy.func1.1(0xc82004afc0, 0xc82006b340, 0xc82004b020)
	/Users/tj/dev/src/github.com/apex/apex/project/project.go:198 +0x71
created by github.com/apex/apex/project.(*Project).Deploy.func1
	/Users/tj/dev/src/github.com/apex/apex/project/project.go:204 +0xd0

```
When run with debug:

```
[ec2-user@ip-something MICAEcho]$ apex -ldebug deploy 
   • loading functions in functions
   • loading function in functions/goodbye
   • loading function in functions/hello
   • inferring runtime         function=hello
   • inferred runtime          function=hello runtime=nodejs4.3
   • deploying 2 functions    
   • deploying                 function=hello
   • creating build            function=hello
   • injecting prelude         function=hello
   • adding env                env=map[APEX_FUNCTION_NAME:hello LAMBDA_FUNCTION_NAME:Echo_hello] function=hello
   • deploying                 function=goodbye
   • creating build            function=goodbye
   • injecting prelude         function=goodbye
panic: runtime error: index out of range
```

and then everything as above.

I'm unsure what other information I can provide to assist. It seems to have to do with having added another function, but... perhaps I did that incorrectly? I'm not explicitly trying to create a multi-language deploy (if that is an issue), but instead was just trying to create a Python handler to see if it would "just work."

Thoughts? Anything else I can do?

**Comment by tj** [comment]
Hmm so this happens when you have index.py or did it happen at all times? If possible maybe a zip of the project for reproducing would be helpful

**Comment by tj** [comment]
nvm I see what's breaking there, you're missing a `.` in the "handler", Lambda requires the file on the left such as "main.myhandler" or "index.myhandler". Either way this should not explode like this so I'll mark it as a bug, thanks for the report!
