### ISSUE TITLE
api gateway

### ISSUE THREAD

**Issue by Grandiz** [apex/apex#499]
If you have a bug report please let us know the following:

  - macos:
  - 0.10.2:

is the way to map api gateway endpoint to specific lambda? for example in project.json

and by the way, can i have deep structure in functions directory? for example
- function
-- user
---login
----index
---logout
----index
---get_user
----index

and deploy something like apex deploy user.login?

**Comment by DavidTPate** [comment]
What you would want to do for setup on your API Gateway @Grandiz is to use [Terraform](https://www.terraform.io/) which is mentioned [here](http://apex.run/#managing-infrastructure), in this case you would use the [AWS Provider](https://www.terraform.io/docs/providers/aws/index.html) that they have to configure your API gateway.

As for the nesting of functions that you asked about, that wouldn't work currently (not sure if there is some work around for it). Including sub-folders could lead to some weird organization problems as then you wouldn't know if they were meant to be functions or just someone organizing their code.

Personally the way that I do it is with a folder structure like the following:
* functions
  * user-login
  * user-logout
  * ...
  * user-get-user

**Comment by tj** [comment]
No deep structures currently, just globbing so you can do `apex deploy user_*` for all user functions etc.

API Gateway isn't first-class at the moment either, you have to use Terraform or similar. We'll likely add something later, there's cool new stuff coming but I'm holding off using the current API Gateway personally, I don't find it useful.

Closing though we have a few of these!
