### ISSUE TITLE
Apex max timeout required?

### ISSUE THREAD

**Issue by bhurlow** [apex/apex#500]
Looks like apex is restricting timeout values to be <= `300s`. 

Is this a lambda imposed restriction?
If yes can we add this to the docs?

**Comment by morenoh149** [comment]
http://docs.aws.amazon.com/lambda/latest/dg/limits.html#limits-list If you're interested in Lambda you probably already know of the limit. But sure, it could be documented here.

**Comment by bhurlow** [comment]
Thanks!

**Comment by tj** [comment]
Yep that's a lambda limit, but I'll add to the docs
