### ISSUE TITLE
AWS Credentials Environment Variables Don't Line Up With SDKs

### ISSUE THREAD

**Issue by DavidTPate** [apex/apex#506]
If you have a bug report please let us know the following:

  - __Operating system__: OS X
  - __Apex Version__: v0.10.2

While going through the process of getting setup with Apex and Terraform on my CI server I noticed that the environment variables currently being used don't match with those required by the AWS SDKs. It's a bit of a pedantic comment, but it definitely led me to some issues and repetition of environment variables as I have to define what Apex expects as well as what the AWS SDKs & Terraform expect.

Currently Apex looks at the following:
* AWS_ACCESS_KEY `AWS account access key`
* AWS_SECRET_KEY `AWS account secret key`
* AWS_REGION `AWS region`

While the AWS SDKs for [Go](https://docs.aws.amazon.com/sdk-for-go/latest/v1/developerguide/configuring-sdk.title.html#environment-variables), [Node.js](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html#Credentials_from_Environment_Variables) and others are looking for the following:

* AWS_ACCESS_KEY_ID `AWS account access key`
* AWS_SECRET_ACCESS_KEY `AWS account secret key`
* AWS_REGION `AWS region`

It seems like these should be inline instead of having special ones for Apex.

**Comment by tj** [comment]
Ah that's a typo in the docs, we do just use the SDK
