### ISSUE TITLE
Syntax Error in module '_apex_index'

### ISSUE THREAD

**Issue by demetriusnunes** [apex/apex#507]
- __Operating system__: Mac OS X 10.11
- __Apex Version__: 0.10.2

After deploying my function, I'm getting a cryptic syntax error: 

```
$ apex -ldebug invoke listers --logs
   • loading functions in functions
   • loading function in functions/listers
   • inferring runtime         function=listers
   • inferred runtime          function=listers runtime=nodejs4.3
START RequestId: 4e2f582a-5385-11e6-a87f-5b54797329a9 Version: 6
Syntax error in module '_apex_index': SyntaxError
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/task/index.js:1:90)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
END RequestId: 4e2f582a-5385-11e6-a87f-5b54797329a9
REPORT RequestId: 4e2f582a-5385-11e6-a87f-5b54797329a9	Duration: 1.06 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 15 MB	
   ⨯ Error: function response: Unexpected token {
```

**Comment by tj** [comment]
http://apex.run/#faq's _apex_index part documents that a bit, but I would try doing `apex build listers > out.zip` and maybe peeking at the contents if necessary. The error should still be in your code though, js stack traces are just kinda cryptic craziness, I think the index.js:1:90 would be the one

**Comment by demetriusnunes** [comment]
I did that. I was testing locally and it was running dine, until I realised I was running node 6 locally. Ran inside a node 4.3 docker container and found out that destructuring is not yet implemented in 4.3, hence the syntax error. Bummer. Is it too much overhead to run babel in Lambda?

**Comment by juliangruber** [comment]
@demetriusnunes here's an example how you can use babel with apex: https://github.com/apex/apex/tree/master/_examples/babel-browserify

**Comment by demetriusnunes** [comment]
@juliangruber This setup based on Webpack is also really nice: https://github.com/rricard/lambda-es6-example - even has a local Lambda emulator/runner.

**Comment by tj** [comment]
We decided to keep it out of core since the tool you use (babel/webpack/browserify/rollup) etc gets opinionated quick.

**Comment by DavidTPate** [comment]
@demetriusnunes Definitely all for the [babel + webpack](https://github.com/apex/apex/tree/master/_examples/babel-webpack) example. We use that actively in Production. Interestingly enough it leads to a quicker average time as compared to an unbuilt function.

The reason being that `require(...)` is for the most part no longer needed thanks to `webpack` and we get to avoid all of those Filesystem lookups. It also means that we can use Async Await, destructuring, etc.

**Comment by demetriusnunes** [comment]
Had a lot of issues dealing with dependencies with both Browserify and Webpack. They just didn't work with "google-spreadsheet" npm package.

Sadly, ended up falling back to native Node 4.3 features...

**Comment by tj** [comment]
I'd stick to node 4.3 too personally, compiling SS code is pretty awkward, that's not really apex's fault though, the state of js is just weird right now, people want a language which doesn't exist yet

**Comment by DavidTPate** [comment]
@demetriusnunes Yeah, there's definitely weirdness related to "native" Node packages (The `C` based ones) right now with `webpack` or `browserify`. Some are easier than others to work around.
