### ISSUE TITLE
how to deploy contain other model with node.js 4.3

### ISSUE THREAD

**Issue by tk009999** [apex/apex#509]
how to deploy contain other model with node.js 4.3?
i'm use 'npm install https' in my project, and then depoly, but when i test my function can't run require('https')

**Comment by DavidTPate** [comment]
If you're attempting to use modules that are installed via `npm` then you'll either need to package those files with the ZIP that you are deploying or execute a build process for your deployment. Personally, I prefer to use the [babel-webpack](https://github.com/apex/apex/tree/master/_examples/babel-webpack) example for use with Node.

**Comment by tk009999** [comment]
Nice, I will try to use the babel-webpack, thank you David.

**Comment by tk009999** [comment]
actually, I already to solve my problem, I find, be successfully deploy project to running on Lambda, just when i deploy my project, I can't have 'node_modle' folder, the project folder gradation need like below:

![screen shot 2016-08-02 at 10 55 12 am](https://cloud.githubusercontent.com/assets/10436665/17315618/a3e771a0-589f-11e6-8c71-345469f4c53c.png)

but, i don't know why for the reason

**Comment by tj** [comment]
As David mentioned as long as node_modules (or the final build file) ends up in the function's directory they'll be added to the zip :D
