### ISSUE TITLE
Aliases don't seem to be updating properly?

### ISSUE THREAD

**Issue by diranged** [apex/apex#511]
## Environment
OS: Ubuntu 12
Apex Version: 0.10.2

## Issue
We're trying to use Apex to deploy a single Lambda function to multiple aliases. The behavior we _expect_ is that:

  * `apex deploy` will push the latest version of the code (if the zip has changed in any way) and update the `current` alias
  * `apex deploy --alias staging` should update the `staging` alias to point to the `$LATEST` version of the code (which effectively is the same as the `current` alias)

However, we're only seeing the first part of the behavior. Deploys of code are idempotent, but alias updating isn't happening:

![image](https://cloud.githubusercontent.com/assets/768067/17344421/da1b8ef2-58b6-11e6-8aa1-20acaf0450c6.png)

Are we misunderstanding how its supposed to work?

**Comment by DavidTPate** [comment]
@diranged Could you please re-run this but with `-l debug` instead of `-l DEBUG`. I did a quick test locally and that is case sensitive right now which is why we aren't seeing all of the debug information.

I went through and tried this myself as well. My new alias was only created if my function code changed. It seems like an edge case which the code doesn't currently handle as the Aliases are only Created/Updated when the function code or configuration is [updated](https://github.com/apex/apex/blob/e14f5ace75ecdc21480bc42cb4f5599053425248/function/function.go#L352-L354).

Here's the part that handles determining if an [update is needed](https://github.com/apex/apex/blob/e14f5ace75ecdc21480bc42cb4f5599053425248/function/function.go#L258-L273), it seems like that just needs to check if an alias change has occurred as well and be a bit smart about linking the versions.

**Comment by tj** [comment]
We have another issue somewhere discussing this a bit more, no consensus yet but the idea was to have something more like `git tag` for cases like this, rather than forcing a deploy or conflating the two operations. Open to suggestions there, I don't use aliases heavily at all myself.

**Comment by diranged** [comment]
Ok so a few things.. First, before I ran any of the below commands, here's the state of our lambda function and its aliases:

![image](https://cloud.githubusercontent.com/assets/768067/17389643/08e3d352-59bb-11e6-9020-e4c4101b80d1.png)

### it seems that in dry-run, debug logging doesn't work at all
```
MacBook:log-pipeline-data-transformer diranged$ /usr/local/bin/apex --dry-run -l debug deploy --alias production

MacBook:log-pipeline-data-transformer diranged$ /usr/local/bin/apex --dry-run -l debug deploy --alias staging

```

### two, without dry run, here's a proper idempotent deploy with no alias
```
MacBook:log-pipeline-data-transformer diranged$ /usr/local/bin/apex -l debug deploy
   • loading functions in functions
   • loading function in functions/stream-to-firehose-transformer
   • deploying 1 functions    
   • deploying                 function=stream-to-firehose-transformer
   • creating build            function=stream-to-firehose-transformer
   • injecting prelude         function=stream-to-firehose-transformer
   • adding env                env=map[APEX_FUNCTION_NAME:stream-to-firehose-transformer LAMBDA_FUNCTION_NAME:log-pipeline_stream-to-firehose-transformer] function=stream-to-firehose-transformer
   • add file to zip           file=index.js function=stream-to-firehose-transformer
   • add file to zip           file=package.json function=stream-to-firehose-transformer
   • add file to zip           file=test/index.js function=stream-to-firehose-transformer
   • created build (12 kB)     function=stream-to-firehose-transformer
   • fetching config           function=stream-to-firehose-transformer
   • config unchanged          function=stream-to-firehose-transformer
   • code unchanged            function=stream-to-firehose-transformer
   • cleaning 1 functions     
   • conditional flush         above_duration=24h0m0s above_size=500 age=3m35.595955828s size=25
   • close                    
```

### next, here's a proper idempotent deploy to the staging alias, which was up to date already
```
MacBook:log-pipeline-data-transformer diranged$ /usr/local/bin/apex -l debug deploy --alias staging
   • loading functions in functions
   • loading function in functions/stream-to-firehose-transformer
   • deploying 1 functions    
   • deploying                 function=stream-to-firehose-transformer
   • creating build            function=stream-to-firehose-transformer
   • injecting prelude         function=stream-to-firehose-transformer
   • adding env                env=map[LAMBDA_FUNCTION_NAME:log-pipeline_stream-to-firehose-transformer APEX_FUNCTION_NAME:stream-to-firehose-transformer] function=stream-to-firehose-transformer
   • add file to zip           file=index.js function=stream-to-firehose-transformer
   • add file to zip           file=package.json function=stream-to-firehose-transformer
   • add file to zip           file=test/index.js function=stream-to-firehose-transformer
   • created build (12 kB)     function=stream-to-firehose-transformer
   • fetching config           function=stream-to-firehose-transformer
   • config unchanged          function=stream-to-firehose-transformer
   • code unchanged            function=stream-to-firehose-transformer
   • cleaning 1 functions     
   • conditional flush         above_duration=24h0m0s above_size=500 age=3m44.441596249s size=27
   • close                    
```

### now here's the deploy that should update the production alias, but doesnt
```
MacBook:log-pipeline-data-transformer diranged$ /usr/local/bin/apex -l debug deploy --alias production
   • loading functions in functions
   • loading function in functions/stream-to-firehose-transformer
   • deploying 1 functions    
   • deploying                 function=stream-to-firehose-transformer
   • creating build            function=stream-to-firehose-transformer
   • injecting prelude         function=stream-to-firehose-transformer
   • adding env                env=map[APEX_FUNCTION_NAME:stream-to-firehose-transformer LAMBDA_FUNCTION_NAME:log-pipeline_stream-to-firehose-transformer] function=stream-to-firehose-transformer
   • add file to zip           file=index.js function=stream-to-firehose-transformer
   • add file to zip           file=package.json function=stream-to-firehose-transformer
   • add file to zip           file=test/index.js function=stream-to-firehose-transformer
   • created build (12 kB)     function=stream-to-firehose-transformer
   • fetching config           function=stream-to-firehose-transformer
   • config unchanged          function=stream-to-firehose-transformer
   • code unchanged            function=stream-to-firehose-transformer
   • cleaning 1 functions     
   • conditional flush         above_duration=24h0m0s above_size=500 age=5m59.612866951s size=29
   • close                    
MacBook:log-pipeline-data-transformer diranged$ 
```

**Comment by DavidTPate** [comment]
As @tj mentioned this is related to #364

**Comment by tj** [comment]
closing in favour of the discussion in #364
