### ISSUE TITLE
couldn't install on Mac El Capitan

### ISSUE THREAD

**Issue by FeiYao** [apex/apex#518]
I tried to install the latest version of Apex on El Capitan but fail, even using sudo. Please advise.

Thanks

**Comment by tj** [comment]
What error(s) do you get? I'll try and add homebrew install support soonish

**Comment by FeiYao** [comment]
It doesn't give you an error and seemingly the installation is successful. But it didn't install, and I couldn't find it in /usr/local/bin either.

Thanks for your quick response.

**Comment by DavidTPate** [comment]
@FeiYao When you added `sudo` which of these did you run?

```
sudo curl https://raw.githubusercontent.com/apex/apex/master/install.sh | sh
```

```
curl https://raw.githubusercontent.com/apex/apex/master/install.sh | sudo sh
```

You'll want to run the second one as running `curl` with `sudo` won't fix the installation issue.

**Comment by FeiYao** [comment]
Thanks for the prompt response. Only second one works for me though. So, my problem is kind of solved.

Thanks, David.

**Comment by DavidTPate** [comment]
I took a stab at a potential way to address this in #519

**Comment by mooyoul** [comment]
#474 seems similar issue. Good job @DavidTPate :)
