### ISSUE TITLE
Config validation & defaults

### ISSUE THREAD

**Issue by tj** [apex/apex#52]
We should probably validate the config on Open(), via gopkg.in/validator.v2 or similar. Even just required fields would be fine for now. 

- [ ] Add required fields
- [ ] Add defaults to "memory" of ??
- [ ] Add defaults to "timeout" of ??
- [ ] Change "role" to be optional once we support it at the project level
- [ ] Update https://github.com/apex/apex/wiki/function.json

**Comment by mthenw** [comment]
I will add required fields with #40

**Comment by mthenw** [comment]
In terms of defaults I would use AWS Lambda defaults which is memory: 128 and timeout: 3

**Comment by mthenw** [comment]
1, 2, 3, 4 done.

**Comment by tj** [comment]
updated wiki!

**Comment by mthenw** [comment]
IMHO https://github.com/apex/apex/wiki/project.json should also be updated :)
