### ISSUE TITLE
Change the functions/ directory?

### ISSUE THREAD

**Issue by matthewmueller** [apex/apex#533]
Curious if there's a way to change the `functions/` directory. I tend to keep everything under `src/`, so having it top-level is a little inconvenient.

**Comment by polds** [comment]
Looks like `functions` is hardcoded:

https://github.com/apex/apex/blob/master/boot/boot.go#L170-L171

**Comment by tj** [comment]
I kinda like it hard-coded TBH haha, at least for Go projects where you have tons of root-ish pkgs

![Uploading Screen Shot 2016-08-24 at 8.52.20 AM.png…]()

**Comment by matthewmueller** [comment]
ahh that does look really nice, what about your project's dotfiles? with node there's a gazillion of them.

**Comment by matthewmueller** [comment]
closing, this standardization has grown on me
