### ISSUE TITLE
Suggestions on using Apex in OSS Projects?

### ISSUE THREAD

**Issue by polds** [apex/apex#534]
Greetings all,

Wondering if anyone has any suggestions on best practices of using Apex from some OSS Lambda projects. As the project.json file has the iam policy in it it's probably not the best idea to commit that directly. 

I'm wondering if the contents of the repo should be what would normally be in the `functions` folder and let the user scaffold everything up themselves, as demonstrated below:

```
[#] git clone github.com/polds/reponame
[#] mkdir new-project && cd new-project
[#] apex init
[#] cp -R ../reponame/ ./functions/
```

The second option I thought is to gitignore the project.json file and still have the user run `apex init`

Anywho, ideas?

**Comment by tj** [comment]
For single functions I've been just suggesting submods (ex https://github.com/apex/capture), but yea for initializing a non-new project it needs some love

**Comment by DavidTPate** [comment]
@polds If you're utilizing Terraform then it would just be pulling the role from wherever Terraform set the infrastructure up.

**Comment by polds** [comment]
Going to close this issue.
