### ISSUE TITLE
ship version 0.10.3?

### ISSUE THREAD

**Issue by skabbes** [apex/apex#535]
I submitted [a patch](https://github.com/apex/apex/pull/530) a few weeks ago which fixed (for me) a critical bug which prevented me from using apex in a CI environment.

Any chance you could publish another release to resolve this?  I'm sure anyone else working in a VPC will have similar issues.

**Comment by tj** [comment]
Yeahhh probably long overdue for a release! I'll get that up in a minute

**Comment by tj** [comment]
https://github.com/apex/apex/releases/tag/v0.10.3
