### ISSUE TITLE
Long file path cause Access denied when deploying function

### ISSUE THREAD

**Issue by lethanhtrung2020** [apex/apex#537]
Hi,
  - __Operating system__: Windows 7 Enterprise
  - __Apex Version__: 0.10.2

I use apex deploy my lambda function that use firebase module and there was a message appeared as below

←[31m   ?←[0m Error: function firebase: open functions\firebase\node_modules\firebase\node_modules\jsonwebtoken\node_modules\jws\node_modules\base64url\node_modules\meow\node_modules\indent-string\node_modules\repeating\node_modules\is-finite\node_modules\number-is-nan: Access is denied.

I try to zip the folder by default zip of windows 7 (by using send to Compressed (zipped) folder then it shows error as below

![image](https://cloud.githubusercontent.com/assets/14961790/18270024/1c3ac7a8-7455-11e6-8d5d-c8c2d2a64b8f.png)

So I guessed that the issue related to default zip application. I try to install 7zip but don't know how to make it as default. 
I tried to compress function folder content (js file, node_modules folder, ...) upload zip file (by using 7zip) to AWS lambda then it is ok. however, running test the function throws error 

  "errorMessage": "Cannot find module '_apex_index'",
  "errorType": "Error",
  "stackTrace": [
    "Function.Module._load (module.js:276:25)",
    "Module.require (module.js:353:17)",
    "require (internal/module.js:12:17)"
  ]
}

Please help. Thanks

**Comment by DavidTPate** [comment]
@lethanhtrung2020 This issue has to do with how Windows handles long filenames and `npm` making large nested directories. You can find an old issue on it [here](https://github.com/nodejs/node-v0.x-archive/issues/6960) and the resolution that `npm` came up with [here](https://github.com/nodejs/node-v0.x-archive/issues/6960#issuecomment-46704998). 

I'm guessing that if you were to update your `npm` version that you wouldn't hit the same issue. You can find the most recent issue [here](https://github.com/npm/npm/issues/3697). If you need additional support with this you'll need to hop over to the `npm` [issues](https://github.com/npm/npm/issues) and file a bug as this isn't a problem with `apex` but with your version of `npm`.

**Comment by lethanhtrung2020** [comment]
Thanks DavidTPate for your kind support. I agree that this is not apex issue and it should be a question, not an issue. I will follow your advice to find a solution.
