### ISSUE TITLE
Error while deploying `Error: json: cannot unmarshal string into Go value of type map[string]string`

### ISSUE THREAD

**Issue by cgswong** [apex/apex#538]
I'm trying to deploy my project but getting the error below:

```
Error: json: cannot unmarshal string into Go value of type map[string]string
```

- __Operating system__: MacOS 10.11.6
- __Apex Version__: 0.10.2

I'm sure I'm doing something wrong but have no idea. I've got two project files for each environment, i.e. `project.json` and `project.nonprod.json`. There contents are below

```
{
  "name": "elasticsearch",
  "description": "Elasticsearch Curator",
  "memory": 128,
  "timeout": 5,
  "role": "arn:aws:iam::999999999999:role/ESCuratorLambdaAdmin",
  "runtime": "python",
  "nameTemplate": "{{.Function.Name}}",
  "vpc": {
    "securityGroups": [ "sg-44444444" ],
    "subnets": [ "subnet-44444444" ]
  },
  "environment": "prod"
}
```

Any help is appreciated.

**Comment by cgswong** [comment]
Also happens in Apex 0.10.3

**Comment by tj** [comment]
Sorry, Go's JSON errors are awful. "environment" is an object for environment variables, the chosen env is set via `-e xxx` currently.

**Comment by cgswong** [comment]
Thanks, I just realized that as well :-)

Thanks for quick reply!
