### ISSUE TITLE
Clarification on usage/purpose (question)

### ISSUE THREAD

**Issue by cgswong** [apex/apex#539]
I think Apex is pretty good, however, I'd appreciate some further clarity on something that seems missing. Is it "just" a Lambda function manager so one still has to configure the actual trigger for the function such as CloudWatch events for scheduled events? If so what does the workflow look like with Apex?

Thanks.

**Comment by tj** [comment]
Currently it's just for managing the functions, sources are done via Terraform (or manually) so you can preview changes made to the configuration.

**Comment by cgswong** [comment]
Ah. Thanks for the clarity.
