### ISSUE TITLE
[nodejs4.3] handler defaults to "_apex_index.handle" and can't be changed 

### ISSUE THREAD

**Issue by murtyjones** [apex/apex#540]
I'm trying to change the handler in the function.json for a nodejs4.3 function but can't do so. Despite the following line:

"handler": "index.handle"

the handler in AWS appears:

_apex_index.handle

Am I missing something in the config?

OS: Mac OSX Yosemite 10.10.5
Apex version: 0.10.3

**Comment by tj** [comment]
The last FAQ sort of covers what that file is: http://apex.run/#faq. Gist of it is we have an env-injecting wrapper script which delegates to whatever your handler is: https://github.com/apex/apex/blob/master/plugins/nodejs/nodejs.go#L36 but it will display _apex_index.handle in Lambda's UI

**Comment by DavidTPate** [comment]
@murtyjones I'm closing this out as I believe we've answered your question. Feel free to respond if you need some more clarity.
