### ISSUE TITLE
RequestError: send request failed

### ISSUE THREAD

**Issue by it-sumanp** [apex/apex#541]
If you have a bug report please let us know the following:

  - __Operating system__: OS X 10.10.5
  - __Apex Version__: 0.10.3

Hi ..
I am following instruction at https://apex.run/#getting-started 
when I run apex deploy or apex invoke i got below error ..

Error: log "/aws/lambda/apex-lambda-suman_hello": RequestError: send request failed
caused by: Post https://logs.Oregon.amazonaws.com/: dial tcp: lookup logs.Oregon.amazonaws.com: no such host

When appropriate please also paste the debug log output using `-ldebug` or `--log-level debug`.

**Comment by DavidTPate** [comment]
What value did you put in for your region? It looks like we don't validate those region values (not sure that we should) and that you put in `Oregon` as the region which isn't a valid region. Instead it should be `us-west-2` for the region. You can find the valid regions [here](http://docs.aws.amazon.com/general/latest/gr/rande.html).

**Comment by it-sumanp** [comment]
Thanks It worked

**Comment by it-sumanp** [comment]
detailed solution ... 
I updated region value to us-west-2  in ~/.aws/config and it worked (y)
