### ISSUE TITLE
[Python] Error: function response: Unable to import module '_apex_main'

### ISSUE THREAD

**Issue by paulosuzart** [apex/apex#543]
- __Operating system__: 3.19.0-32-generic #37~14.04.1-Ubuntu
  - __Apex Version__: 0.10.3

```
apex invoke pyllo -ldebug --log-level debug
   • loading functions in functions
   • open                      env= function=pyllo
   • loaded config             config=function.json env= function=pyllo
   ⨯ Error: function response: Unable to import module '_apex_main'
```

Hi, I just deploy a python function as simple as:

```
from PIL import Image
print "start simple function"
def handle(event, context):
    print "processing event"
    return event
```
And got the error as shown above. Any idea? Should I have to install any apex dependencies with `pip`?

Just to mention, PIL is propperly setup at function level folder.

TIA

**Comment by tj** [comment]
hmm the error is a bit strange, I'm not overly familiar with Python but we wrap your main module here: https://github.com/apex/apex/blob/master/plugins/python/python.go#L31, but if there's an import error I would expect something like `Unable to import Image from PIL`. Let me know if you see anything glaringly wrong there.

They do have to end up in the Lambda function (see http://docs.aws.amazon.com/lambda/latest/dg/lambda-python-how-to-create-deployment-package.html), which seems to be a little tricky with pip. It also looks like PIL has some native code, so it would have to be built in Docker or on a Linux platform :(

**Comment by paulosuzart** [comment]
Thanks for the quick replay. In fact this PIL import is just to test a
function that uses libs in Python that requires certain os native libs
present.

I'll remove the import and test again with pure Python. I'll check your
link and post here the findings.

Cheers

**Comment by paulosuzart** [comment]
Tj, after using `ami-f0091d91` for installing, init, and deploy the python function with Pillow, it worked. *Of course I had to `cp -R ~/apexenv/lib64/python2.7/site-packages/PIL/ .` to the root of the function folder.*

The problem was my Ubuntu compiled Pillow stuff being deploy to the aforementioned AMI. This extra step for basically coding and testing in a EC2, is really annoying, but it is not Apex fault, just the way AWS architects the thing.

Great, thanks a lot.

**Comment by tj** [comment]
Yeah unfortunately not much we can do there, other than having a dependency on Docker but that would be awkward.
