### ISSUE TITLE
Unable to build from source (where to git clone?)

### ISSUE THREAD

**Issue by matthewmueller** [apex/apex#547]
If you have a bug report please let us know the following:

  - __Operating system__: OSX
  - __Apex Version__: 0.10.2

---

This is most likely a total Go n00b question, but haven't been able to get this working: 

```sh
go get ./...
```

Eventually errors out saying:

```sh
go install: no install location for directory $HOME/Projects/apex/vpc outside GOPATH
	For more details see: go help gopath
```

Does this  project source need to be located within the  `$GOPATH`?

---

**EDIT:** I think I'm just wondering where I should `git clone` this puppy so that `go get ./...` works properly.

**Comment by polds** [comment]
@matthewmueller Yeah this is a Go issue. Go is quite opinionated about folder setup. This project will need to live `$GOPATH`. Usually the git clone location (for this repo) should be `$GOPATH/src/github.com/apex/` as git clone will create the additional repo name directory.

Take a look at [this doc](https://golang.org/doc/code.html#Workspaces) on the recommended Workspace set up for Go.

So to best answer your question:

```
[~] mkdir -p $GOPATH/src/github.com/apex/
[~] cd $GOPATH/src/github.com/apex/
[$GOPATH/src/github.com/apex/] git clone git@github.com:apex/apex.git && cd apex
[$GOPATH/src/github.com/apex/apex] go get ./...
```

Hopefully that helps some.

**Comment by DavidTPate** [comment]
Yeah, I did the exact same thing my first time setting up Go...

Closing this as it's not an Apex issue.

**Comment by matthewmueller** [comment]
Thanks guys for the help!

**Comment by kopertop** [comment]
I had this exact same problem, would be nice to see some sort of documentation in the README showing steps for installing from source.

**Comment by DavidTPate** [comment]
@kopertop PRs are accepted if you want to see that in the README.
