### ISSUE TITLE
Not able to overwrite lambda function name when deploy

### ISSUE THREAD

**Issue by yikaus** [apex/apex#561]
- Debian 8:
  - Apex version 0.10.3:
  - Python function

Try to overwrite lambda function name , by default apex set it to python_yourFunctionName

Using below command to test overwrite default LAMBDA_FUNCTION_NAME , it works when build a zip file .
```
apex build -s LAMBDA_FUNCTION_NAME=foo bar > test.zip

test.zip/.env.json
{"APEX_FUNCTION_NAME":"bar","LAMBDA_FUNCTION_NAME":"foo"}
```

However try to use same way to deploy with no luck 
```
apex deploy -s LAMBDA_FUNCTION_NAME=foo bar
   • creating function         env= function=bar
   • created alias current     env= function=bar version=1
   • function created          env= function=bar name=python_bar version=1
```

**Comment by tj** [comment]
What's the use-case for giving a custom name?

**Comment by yikaus** [comment]
We have some naming standard for all the aws resource we created . 

Also apex build seems handle the name changes , but deploy command not pick it up

**Comment by tj** [comment]
Ahh I see, yeah LAMBDA_FUNCTION_NAME is hard-coded to pass the generated name, but it has no effect on the Lambda function name itself. 

I'm against overrides personally, it's confusing if they don't match the directory name. The project can be stripped via re-defining `nameTemplate` to `{{.Function.Name}}` http://apex.run/#structuring-projects.

**Comment by yikaus** [comment]
You right , that is all I need . didn't read through document clearly . 

Thanks tj

**Comment by tj** [comment]
It's a weird option haha :D hard to find. 

cheers
