### ISSUE TITLE
Build file contains devDependencies

### ISSUE THREAD

**Issue by marcelpanse** [apex/apex#562]
- __Operating system__: OSX 10.11.6
  - __Apex Version__: 0.10.3

I have a package.json with dependencies, devDependencies and bundledDependencies. 
When I look at the generated build zip file it seems to contain all the dependencies including the devDependencies which results in an unnecessary large zip file.

**Comment by tj** [comment]
Apex has no specific knowledge of Node projects, so anything present in the function's directory which isn't excluded by .apexignore will end up in the zip.

Typically people use a bundler like webpack or browserify which just happens to strip the dev deps out by producing the build, and ignoring the rest. The laternative would probably require that `npm install --production` is used. 

Another alternative is to do deploys in CI so they're only built with `--production` in CI. Node is admittedly not a great setup for doing Lambda deploys from a local dev machine.

**Comment by marcelpanse** [comment]
Thanks, that makes sense.

**Comment by DavidTPate** [comment]
@marcelpanse I highly recommend using a bundler as @tj mentioned for your Node projects. In my testing it actually reduces your average execution times as well (less hits on the file system & less code). Check out the [webpack](https://github.com/apex/apex/tree/master/_examples/babel-webpack) example for how to use it.

**Comment by marcelpanse** [comment]
Yes I'll try the babel setup. I'm already using babel on our React project. 
Going through a CI is not really an option, since I need to deploy fast and often to a dev environment.
