### ISSUE TITLE
Connecting to both AWS Elasticache and internet APIs with AWS Lambda

### ISSUE THREAD

**Issue by wscherfel** [apex/apex#569]
Hello,

I am working on a parser that is run on AWS Lambda, and i want to integrate AWS Elasticache into it.
I use some internet APIs (wikipedia, IBM Watson etc.). 

If i add the vpc field to project.json file and fill it with subnets and security groups, the Elasticache works but i cannot connect to the internet APIs. If i delete the vpc field from project.json i can connect to mentioned internet APIs but not to Elasticache.

Is there a way to connect both to internet and AWS Elasticache?

**Comment by DavidTPate** [comment]
@wscherfel the issue that you have doesn't deal with Apex but rather how you have your VPC setup. See [this note](http://docs.aws.amazon.com/lambda/latest/dg/vpc.html#vpc-internet) about connecting to the internet from within a VPC:

> If your Lambda function needs Internet access, do not attach it to a public subnet or to a private subnet without Internet access. Instead, attach it only to private subnets with Internet access through a NAT instance or an Amazon VPC NAT gateway.

**Comment by wscherfel** [comment]
Thanks for your answer, i will look into it.
