### ISSUE TITLE
How can I set a trigger for a lambda function

### ISSUE THREAD

**Issue by HugoCornu** [apex/apex#572]
Hi,
Thanks for Apex.

I would like to trigger a function whenever a file is put into a bucket.
 
Should I deploy the function with Apex and then manually set the trigger? 
Can I have Apex set the trigger for me ?
If set manually, will the trigger survive when I deploy a newer version of the function ?

I looked for your doc about triggers but didn't find it, hence this issue

**Comment by tj** [comment]
Either manual or via https://www.terraform.io/, and yep if you point the source to the 'current' alias for your function (that apex creates) it'll be maintained for newer releases of the function

**Comment by woodnz** [comment]
Thanks tj that helped me.  Loving Apex!   @HugoCornu  no doubt you've solved this already but heres a snippet of generally useful terraform code that integrates with Apex

```
resource "aws_lambda_function" "my_lambda" {

  function_name = "my_lambda_my_function"
  filename = "../my_function.zip"
  role = "${aws_iam_role.lambda_role.arn}"
  handler = "_apex_index.handle"
  publish = "true"
}

resource "aws_lambda_alias" "current" {
  name = "current"
  description = "Sets the alieas for the latest version to 'current'.  This is the alias used by apex."
  function_name = "${aws_lambda_function.my_lambda.arn}"
  function_version = "$LATEST"
}
```

**Comment by HugoCornu** [comment]
Thanks @tj

Thanks you @woodnz  Always very useful to see how others do it !
