### ISSUE TITLE
AWS phasing out support for the Node 0.10 runtime

### ISSUE THREAD

**Issue by polds** [apex/apex#578]
Just as a heads up got this notice today:

From what I can see, it appears at least the Go shim uses this runtime.
# 

Dear AWS Lambda Customer,

You are receiving this message because you have recently created/updated Node 0.10 functions within AWS Lambda in your AWS account.
- What is happening?

AWS Lambda is deprecating the Node 0.10 runtime. The v0.10.42 runtime will no longer be available to create new functions starting 11/10, but will continue to be supported for existing functions till April 2017. All functions written in Node will need to use the Node v4.3 runtime moving forward till newer version of Node are available within AWS Lambda.
- How does this affect you?

All existing functions will continue to work till April 2017 as is with no change required on your part in the near term, including making updates to code and configuration. You will however, no longer be able to create new functions using the Node 0.10 runtime starting 11/10. Any ongoing deployments, such as direct API calls or automated deployment tools you have configured for deploying Node 0.10 code to AWS Lambda as new functions will start returning errors.
- What do you need to do?

We recommend you migrate your v0.10 functions to runtime v4.3 as soon as possible. For more information please see "Using the Earlier Node.js Runtime v0.10.42" section of our documentation in the AWS Lambda Developer Guide http://email.awscloud.com/ZZkdt08rt010210HD00OMT0.

If you have any questions or concerns, you can contact the AWS Support Team on the community forums and via AWS Premium Support at: http://aws.amazon.com/support http://email.awscloud.com/DTEd10s0MZH00028Ok0t0t1

Sincerely,

Amazon Web Services

**Comment by DavidTPate** [comment]
Makes sense that support is being phased out at Node 0.10 is off LTS now. We'll have to see if there are any impacts to the shim from upgrading (I'm guessing there won't be much). I think @tj uses that shim regularly.

**Comment by tj** [comment]
oOo interesting, guess we're stuck upgrading that haha..  yeah all my stuff is Go

**Comment by jhayashi** [comment]
Amazon is saying that 0.10 is no longer supported and is encouraging migration to a supported runtime version. Any update?

**Comment by polds** [comment]
Closed by #637 .

**Comment by tj** [comment]
v0.12.0 has the fix
