### ISSUE TITLE
Pass function version as env var for logging

### ISSUE THREAD

**Issue by tj** [apex/apex#581]
Would be nice to have LAMBDA_FUNCTION_VERSION etc for logging, not sure if it's in the context or not but that's not the best spot for it

**Comment by mthenw** [comment]
FYI, it's in context object under `functionVersion` key.

**Comment by tj** [comment]
ahh thought it might be in there, shame they don't seem to expose it as an env var

**Comment by tj** [comment]
looks like it is/will be in there http://docs.aws.amazon.com/lambda/latest/dg/env_variables.html
