### ISSUE TITLE
Apex not seeing the Golang vendor directory

### ISSUE THREAD

**Issue by mhemmings** [apex/apex#583]
- __Operating system__: OSX 10.11.6
  - __Apex Version__: 0.10.3
  - __Go Version__: 1.7.3

I have vendored 3rd party dependancies. I can build my functions no problem using `go build` or `go run`, but as soon as I use `apex build` it fails to see any of the deps in the vendor directory and the build fails.

**Comment by yarikbratashchuk** [comment]
@mhemmings so how do U fix this problem?
