### ISSUE TITLE
MissingRegion: could not find region configuration despite region set in project.json and .aws files

### ISSUE THREAD

**Issue by tomprogers** [apex/apex#585]
When I run `apex deploy`, I get a MissingRegion error. When I run `apex deploy -r us-west-2`, it's able to get past region-selection (I still get a NoCredentialProviders, but I assume that's a separate problem).

I've set my region in three places (just to be sure):
- project.json (`"region": "us-west-2"`)
- .aws/config (`region = us-west-2`)
- .aws/credentials (`region = us-west-2`)

I think this means I shouldn't have to provide the region on the command line.

Here's the output:

```
$ apex deploy -ldebug
   • loading functions in functions
   • open                      env= function=ballot-get
   • open                      env= function=game-get
   • deploying 2 functions
   • deploying                 env= function=game-get
   • creating build            env= function=game-get
   • injecting prelude         env= function=game-get
   • deploying                 env= function=ballot-get
   • creating build            env= function=ballot-get
   • injecting prelude         env= function=ballot-get
   • adding env                env=map[APEX_FUNCTION_NAME:game-get LAMBDA_FUNCTION_NAME:ml-game-get] function=game-get
   • adding env                env=map[APEX_FUNCTION_NAME:ballot-get LAMBDA_FUNCTION_NAME:ml-ballot-get] function=ballot-get
   • add file to zip           env= file=index.js function=game-get
   • add file to zip           env= file=index.js function=ballot-get
   • created build (1.6 kB)    env= function=game-get
   • fetching config           env= function=game-get
   ⨯ Error: function game-get: MissingRegion: could not find region configuration
```

MacOS 10.11.6 (15G31)
Apex version 0.10.3

What other configuration is necessary? I can't find anywhere else to put this stuff, except maybe creating a function.json for every single function, which... ugh.

**Comment by tj** [comment]
Hmm AWS_REGION, --region, or ~/.aws/config should do the trick

**Comment by tomprogers** [comment]
For reference:

```
// project.json
{
	"name": "ml",
	"description": "json api",
	"memory": 256,
	"timeout": 15,
	"environment": {},
	"nameTemplate": "ml-{{.Function.Name}}",
	"runtime": "nodejs4.3",
	"retainedVersions": 10,
	"profile": "default",
	"role": "arn:aws:iam::175019973242:role/lambda",
	"region": "us-west-2"
}
```

```
// .aws/config
[profile default]
output = json
region = us-west-2
```

```
//.aws/credentials
[default]
aws_access_key_id = such_password
aws_secret_access_key = many_securing
region = us-west-2
```

**Comment by tj** [comment]
I wonder if it's `default` that isn't set properly, I always name them personally since the project usually has a name, but that should still work. Maybe try `[profile ml]` etc to weed that out, and I'll flag as a bug

**Comment by tomprogers** [comment]
No luck. Neither `ml` nor `ml-prod` makes any difference.

**Comment by tj** [comment]
Damn, I'll try and reproduce

**Comment by tomprogers** [comment]
What's .envrc? I didn't see any mention of that when setting up apex.

**Comment by tj** [comment]
Ah this thing: http://direnv.net/ just loads .envrc in the current directory.

I'm not sure what to think though, it works for me:

```
   λ ldb (master): apex deploy
   ⨯ Error: function query: MissingRegion: could not find region configuration
   λ ldb (master): export AWS_PROFILE=logs-prod
   λ ldb (master): apex deploy
   • config unchanged          env= function=query
   • code unchanged            env= function=query
   λ ldb (master): cat ~/.aws/config 
[profile logs-prod]
output = json
region = us-west-2
```

**Comment by tomprogers** [comment]
I think your output might actually reproduce the problem: running `apex deploy` without specifying a region causes a MissingRegion error to be thrown, despite a region being defined for the profile. The only piece of info I still need to confirm the similarity is to see whether you have `profile` specified in your project.json. If you do have a profile specified, then it seems apex is misbehavior.

My understanding is that all of these things ought to be configurable via static files, including which profile (and region) is used by default.

**Comment by tj** [comment]
In that example there was no .profile, but I tried with .profile as well and it worked. Yeah there's a bit of a config-overload, but AWS_* and ~/.aws are very standard in the AWS tooling community so we're sort of stuck with that.

I'd welcome a PR for a "region" property though to match "profile", I prefer being explicit as well.

**Comment by tomprogers** [comment]
Solved. My `.aws` directory was in the project root, not in my home folder. I did that on purpose, thinking it would be supported.

> I always name them personally since the project usually has a name

> AWS_* and ~/.aws are very standard in the AWS tooling community

Those two statements in combination pointed me toward the right assumptions.

Thanks very much for your help.

P.S. Yeah, I'd love it if I could put `"profile": "ml"` into the project.json, and then apex would auto-select that from the global config. Not a Go dev myself. :shrug:

**Comment by tj** [comment]
Ah! That'll do :D

**Comment by ryantuck** [comment]
I encountered this same issue and realized it was due to having `AWS_DEFAULT_REGION` defined (legacy), as opposed to `AWS_REGION`. Updating which env var I was relying on fixed the issue.

**Comment by Saeven** [comment]
I'm experiencing the same issue.  My config is tucked into ~/.aws/config, and yet it still reports missing region.  Adding the -r flag works.

Apex version 1.0.0-rc2
OSX Mojave

**Comment by natesilva** [comment]
Similar issue. It works if I add the region to my `~/.aws/config`, but if I set it in `project.json` it’s ignored.
