### ISSUE TITLE
Define configuration shape and semantics

### ISSUE THREAD

**Issue by tj** [apex/apex#59]
## Problem:

- We haven't fully stabilized or future-proofed the config
- Function defaults are currently top-level properties

## Cases to consider:

- [ ] environment variables
- [ ] API gateway
- [ ] input sources
- [ ] function-level config (not just environment variables)
- [ ] project-level defaults and/or for all of the above
- [ ] environments specific config
  - tuning of function config (role, timeout, etc)
  - environment variables for functions

## Thoughts 

We could tackle this a few ways. One would be to just keep throwing config into package.json or function.json respectively. With this we have to use a lot of nesting for clarity.

Another would be to treat gateways and others as first-class things like functions, using their own dirs.

Another alternative might be to have a utility which basically lets you decompose project.json into directories of the same key names, as you wish. For example:

```json

{
  "functions": {
    "defaults": {
      "runtime": "node",
      "memory": 128
    }
  },
  "gateways": {
    "api": {
      "/pets/{name}": {}
    }
  }
}
```

Could be:

```
./config
  ./functions
    ./defaults.json
  ./gateways
    ./api.json
```

Or:

```
./config
  ./functions.json
  ./gateways.json
```

You can expand any object to dirs as-desired, while maintaining a well-known shape. I'd like a unifying concept like this if we can pull it off without hurting UX.

**Comment by mthenw** [comment]
> function-level environment variables that are auto-populated via process.env and os.Setenv() etc

not sure how to achieve it now, this function is not used anywhere https://github.com/apex/apex/blob/master/function/function.go#L104

> I'm generally not a fan of environment variables since they're pretty restrictive shape-wise, so I'd definitely prefer if those were not the primary configuration mechanism.

Heh, I think this should be default configuration mechanism because it's simple. 

I thinking about a object in `project.json` or `function.json` under `env` key. And of course --env support in `apex deploy`. That's all.

**Comment by tj** [comment]
I guess the problem I have with envs here is just that they're not great at describing more complex config. The use-case I have in mind is log-collector which will support dozens of providers each with a variety of config. Env is decent for setting db endpoints etc but beyond a few values it's a little crazy (unless we just assign json to the env var and let the user parse, that could work too). 

AWS ECS does similar with docker config, you just do `ECS_ENGINE_AUTH_DATA={username,password,blahblah}`, so I suppose we could do that with "env":

```json
{
  "env" {
    "ECS_ENGINE_AUTH_DATA": { "username" ... }
  }
}
```

**Comment by mthenw** [comment]
Yup, great idea.

**Comment by mthenw** [comment]
Also, how env vars can be defined currently?

**Comment by tj** [comment]
I didn't end up migrating the flag portion during the multi-function changes, but that was:

- https://github.com/apex/apex/commit/a6779a266518fa9d056acd74cac4d57e7bbab0c6#diff-dee44ad14b2a52ce794d49a38076d33fL155
- https://github.com/apex/apex/commit/a6779a266518fa9d056acd74cac4d57e7bbab0c6#diff-b731e2c7d07f4c9a90ccd47c8bf4ce3cL116

Zip() creates a .env.json file on the fly which in Go's case is loaded via https://github.com/apex/apex/blob/master/env.go

**Comment by mthenw** [comment]
Are you planning to finish that?

**Comment by tj** [comment]
Nah, hacking on some other stuff today, would be nice to get that back in and we can cut another release with the latest stuff

**Comment by tj** [comment]
Most cases need to handle:

- project level defaults
- environment specific defaults
- function level overrides
- function level environment specific overrides

Possibly more later with dependencies, but I haven't found any really good use-cases for deps yet, not worth complicating things unless there's a good reason.

**Comment by tj** [comment]
- with Terraform handling roles etc I think function.json is unnecessary
- we could have `functions: { defaults: ..., foo: ..., bar: ... } ` in project.json
- we could have `gateways: { api: { "/": { ... } }`
- all props could decompose into json files of the same name `./gateways.json`, `./functions.json`
- we could support optional yaml, which is much nicer for gateways

**Comment by tj** [comment]
Any opinions on `-e, --env` precedence? Should it override project.json/function.json (I'd think so)

**Comment by mthenw** [comment]
>I'd think so 

me too :)

**Comment by tj** [comment]
Env options:

A:
```json
{
  "name": "coffeescript",
  "description": "Coffeescript example using hooks",
  "role": "arn:aws:iam::293503197324:role/lambda",
  "runtime": "nodejs",
  "hooks": {
    "build": "coffee -cs < index.coffee > index.js",
    "clean": "rm index.js"
  },
  "environment": {
    "production": {
      "hooks": {
        "build": "coffee -cs --optimized-prod-awesome-flag"
      }
    }
  }
}
```

B:
Inherit from `./project.<env>.json`.

I kinda like A the most because we can use https://github.com/tj/go-decompose later to let people move it out if they want less nesting.

**Comment by tj** [comment]
For TF integration we could maybe have a command that initializes the boiler for them so it's ready to use out of the box. If we went with HCL we could start blurring the lines there even more but that would get pretty opinionated.

**Comment by rantav** [comment]
Hi guys, I wonder where this feature stands? I started using apex and terraform and I want to create a lambda with event source (for ex SNS). 
With TF I create the SNS topic. 
But how do I connect the SNS topic as an event source to the apex-defined function? I could do this manually through AWS console but that's not code...

Is there a current best practice to defining event sources (SNS in my case) to lambda functions? 
cheers.

**Comment by mthenw** [comment]
@rantav we pass lambda functions arns to TF when using `apex infra`. Please check https://medium.com/@tjholowaychuk/apex-v0-7-0-22db413ed898#434d for more info.

**Comment by tj** [comment]
Might close this one, too broad, we're just working around what we have config-wise. Just realized we also have no docs for `infra` but it populates `apex_function_<name>` as a var you can use. Note that you'll need `${var.apex_function_whatever}:current` in most cases.

**Comment by rantav** [comment]
Thanks a lot guys! @tj  @mthenw
