### ISSUE TITLE
Remove environment variable hacks

### ISSUE THREAD

**Issue by tj** [apex/apex#599]
Finally [natively supported](https://aws.amazon.com/about-aws/whats-new/2016/11/aws-lambda-supports-environment-variables/?sc_channel=sm&sc_campaign=launch_Mobile_65c130e1&sc_publisher=tw_go&sc_content=Lambda_Environment_Variables&sc_country=global&sc_geo=global&sc_outcome=launches)

---

- [x] remove hacks
- [x] QA
- [x] adjust documentation

**Comment by DaveBlooman** [comment]
Is this something that you would want help with, can contribute some time to this ticket

**Comment by tj** [comment]
@DaveBlooman I've got a branch up actually! Quick change, just waiting on the AWS SDK to add support then it should be good to go

**Comment by DaveBlooman** [comment]
@tj Looking at the 1.5.8 release, the code looks to be all there, https://github.com/aws/aws-sdk-go/pull/950, doesn't look like the main docs page has updated yet, godoc is good though https://godoc.org/github.com/aws/aws-sdk-go/service/lambda#Environment.SetVariables
