### ISSUE TITLE
permissions for VPC

### ISSUE THREAD

**Issue by outsideris** [apex/apex#602]
If you have a bug report please let us know the following:

  - __Operating system__: macOS
  - __Apex Version__: 0.11.0

When appropriate please also paste the debug log output using `-ldebug` or `--log-level debug`.

I tried to make lambda function in my VPC to access resources in the VPC. I made a user for apex with [minimum IAM policy](https://github.com/apex/apex/blob/master/docs/aws-credentials.md#minimum-iam-policy). VPC is set in `project.json`.

```
"vpc": {
  "securityGroups": ["sg-xxxx"],
  "subnets": ["subnet-xxxx", "subnet-xxx"]
},
```

When I tried to deploy lambda functions, I encountered permission error like below.

```
apex deploy
   • creating function         env= function=build-github-pages
   ⨯ Error: function build-github-pages: AccessDeniedException: Your access has been denied by EC2, please make sure your request credentials have permission to DescribeSecurityGroups for sg-46f42d23. EC2 Error Code: UnauthorizedOperation. EC2 Error Message: You are not authorized to perform this operation.
   status code: 403, request id: 945d9aba-b2d1-11e6-969c-913c9b7fc6b9
```

```
apex deploy
   • creating function         env= function=build-github-pages
   ⨯ Error: function build-github-pages: AccessDeniedException: Your access has been denied by EC2, please make sure your request credentials have permission to DescribeSubnets for subnet-9cda7feb,subnet-2d748b74. EC2 Error Code: UnauthorizedOperation. EC2 Error Message: You are not authorized to perform this operation.
   status code: 403, request id: d336edac-b2d1-11e6-8c8c-57cbe325c8d2
```

```
apex deploy
   • creating function         env= function=build-github-pages
   ⨯ Error: function build-github-pages: AccessDeniedException: Your access has been denied by EC2, please make sure your function execution role have permission to DescribeVpcsRequest. EC2 Error Code: UnauthorizedOperation. EC2 Error Message: You are not authorized to perform this operation.
   status code: 403, request id: d4b0207f-b2d1-11e6-add2-2f20855455ea
````

So, I added the permissions to the IAM user. **I think these permissions described in the docs**.

```
"ec2:DescribeSecurityGroups",
"ec2:DescribeSubnets",
"ec2:DescribeVpcs",
```

I tried to deploy the functions again, but I encountered `CreateNetworkInterface` permission error.

```
apex deploy
   • creating function         env= function=build-github-pages
   ⨯ Error: function build-github-pages: AccessDeniedException: Your access has been denied by EC2, please make sure your function execution role have permission to CreateNetworkInterface. EC2 Error Code: UnauthorizedOperation. EC2 Error Message: You are not authorized to perform this operation.
   status code: 403, request id: ef696721-b2d1-11e6-9dd9-dfa7f9741686
````

[As AWS docs](http://docs.aws.amazon.com/lambda/latest/dg/vpc.html), `AWSLambdaVPCAccessExecutionRole` policy is needed. As I tested it. The role that apex made for lambda functions should have the policy to set VPC subnets and security groups.

Now, the role has only [a policy for cloudwatch](https://github.com/outsideris/apex/blob/master/boot/boot.go#L137). So, I think **`AWSLambdaVPCAccessExecutionRole` policy should be attached to the role by default.** Otherwise, apex users should set the policy in web console or other tools when the users use VPC.

What do you think?

**Comment by tj** [comment]
Hmm if we populated the VPC in init I'd definitely agree, but since we don't have `init` support for VPC right now it might be best to leave that out

**Comment by outsideris** [comment]
I agree with everybody doesn't use lambda in VPC. 
But, the role that apex make for lambda during `init` has to be managed by apex. So, I don't want policies for the role manually. That's why I suggested it.

At least, policy for VPC is described in apex document. What do you think?

**Comment by tj** [comment]
It would definitely be great to have documented. I just think since Apex doesn't add that part for you, it would be best to manually edit the role, so you're aware of whatever you're permitting access to

**Comment by outsideris** [comment]
@tj I got it. I will try to document it. Thank you.

**Comment by dpurrington** [comment]
I want to add my vote for adding this execution policy to the role automatically, as @outsideris said. If not at init, you could check it and add if missing prior to configuring the VPC. 

Not a huge deal because I don't expect to be creating roles frequently, so I can live with it, but it would be a nice touch.
