### ISSUE TITLE
Using env.json file results in error: "cannot unmarshal object into Go value of type string"

### ISSUE THREAD

**Issue by cmpaul** [apex/apex#604]
- __Operating system__: Mac OS X Sierra 10.12.1
  - __Apex Version__: 0.11.0

I'm attempting to test out setting environment variables using a JSON file as described [here](https://github.com/apex/apex/blob/master/docs/env.md). Using the [sample env.json file](https://github.com/apex/apex/blob/master/docs/env.md#json-config), I try to deploy with the `-env-file` flag:

```bash
$ apex deploy --env-file ./env.json -ldebug
   • loading functions in functions
   • open                      env= function=main
   • inferring runtime         env= function=main
   • inferred runtime          env= function=main runtime=nodejs4.3
   • load env from file "./env.json"
   ⨯ Error: reading env file "./env.json": json: cannot unmarshal object into Go value of type string
```

Any help is greatly appreciated!

**Comment by cmpaul** [comment]
For reference, I'm copying and pasting the env.json file linked above:

```javascript
{
  "environment": {
    "LOGGLY_TOKEN": "12314212213123"
  }
}
```

**Comment by cmpaul** [comment]
Also, I'm able to set environment variables just fine using the command line `-s` arguments.

**Comment by DenisGorbachev** [comment]
env.json expects the top-level keys to be environment variables (no need for `environment` key):

```
{
  "LOGGLY_TOKEN": "12314212213123"
}
```

I've updated the docs in https://github.com/apex/apex/pull/606

**Comment by cmpaul** [comment]
@DenisGorbachev I've confirmed that works, thank you for the info and the doc update!
