### ISSUE TITLE
Dynamic Apex function names based on environment

### ISSUE THREAD

**Issue by harlow** [apex/apex#611]
Hi, i'm trying to get staging/production lambda functions running within the same AWS account.

Is it currently possible to append the env name to the function name? i.e. `name=go_my-app-staging`, and `name=go_my-app-production`.

Ideally it would look something like this:

```
apex -e staging deploy my-app
   // name=go_my-app-staging
```

Or maybe another flag where name could be overridden:

```
Flags:
   // ...
   -n, --name string      Function name  
```

**Comment by polds** [comment]
This would be best accomplished by using [Lambda Aliasing](http://docs.aws.amazon.com/lambda/latest/dg/versioning-aliases.html) and the Apex `-a, --alias` flag. 

When done the Lambda Context will include a `functionVersion` which will be set to the alias that's invoked that you can use to switch on logic. The default `functionVersion` is either `$LATEST` or `current` (it can change, but are essentially equal).

**Comment by polds** [comment]
One gotcha to note, though technically correct my example above will not work if no code has changed. Apex detects if there is code changed and aborts if no changes happen. In this instance the best route to take is to use the AWS Console for updating Lambda aliases. As they are actual aliases you can have more than one alias attached to a single function version.

**Comment by tj** [comment]
There's a `nameTemplate` project.json setting, defaults to `{{.Project.Name}}_{{.Function.Name}}` but I believe you could chuck `{{.Project.Environment}}` in there if you wanted, kind of hacky but hey!

**Comment by harlow** [comment]
> One gotcha to note, though technically correct my example above will not work if no code has changed. Apex detects if there is code changed and aborts if no changes happen. In this instance the best route to take is to use the AWS Console for updating Lambda aliases. As they are actual aliases you can have more than one alias attached to a single function version.

@polds Yep, correct. That is the issue I ran into while trying to deploy in prod mode:

```
my-app(master!) $ apex deploy -a staging my-app
   • config unchanged          env= function=my-app
   • updating function         env= function=my-app
   • created alias staging     env= function=my-app version=15
   • function updated          env= function=my-app name=go_my-app version=15
my-app(master!) $ apex deploy -a production my-app
   • config unchanged          env= function=my-app
   • code unchanged            env= function=my-app
```

@tj  works like a charm. Thanks!

Here's want I landed on for `project.production.json`:

```
{
  "name": "go",
  "description": "My App",
  "runtime": "golang",
  "memory": 128,
  "timeout": 300,
  "role": "[redacted]",
  "nameTemplate": "{{.Project.Name}}_{{.Function.Name}}-production"
}
```
