### ISSUE TITLE
Support for AWS lambda Function Streams

### ISSUE THREAD

**Issue by mohit-nyllabs** [apex/apex#615]
I was not able to find examples, support for providing event stream information for AWS Lambda functions in the function.json.

Please guide

**Comment by tj** [comment]
Do you mean with Kinesis? 

Currently Apex doesn't set that stuff up for you, so you have to use Terraform (or Cloudformation)

**Comment by mohit-nyllabs** [comment]
Yes, I wanted to DynamoDB Streams. Can you point the link that provides details on the same.

**Comment by tj** [comment]
I haven't used Dynamodb with Lambda but:

- https://www.terraform.io/docs/providers/aws/r/dynamodb_table.html
- http://apex.run/#managing-infrastructure

Somewhere in the Terraform stuff you should be able to pass the `${var.apex_function_<whatever-name>}` ARN

**Comment by tj** [comment]
That's about as much as I can help there haha :D closing, but anyone else can feel free to comment
