### ISSUE TITLE
Allow S3 upload when CreateFunction operation is too large

### ISSUE THREAD

**Issue by scaladen** [apex/apex#616]
- MacOSX Sierra:
  - 0.11.0:

When I try to deploy my function, I get the following:  

`Error: function lambda: RequestEntityTooLargeException: Request must be smaller than 69905067 bytes for the CreateFunction operation status code: 413, request id: 4efd2af6-c144-11e6-b31a-998a7c60e4bc`

There's an alternative upload via S3.  Could this be implemented?

**Comment by tj** [comment]
Hmm haha, I haven't hit that yet, how big is the func?

**Comment by hasPeterr** [comment]
I ran into the same issue deploying a java function that contains the entire AWS SDK. I slimmed it down from 60 or so MB down to 13 and it worked just fine, but I could see this becoming a problem in the future so it would be nice to add support. Whats strange is that my jar was under the size limit in the error message and I cant imagine theres that much additional overhead to push the request above the 67MB limit.

**Comment by mooyoul** [comment]
Actually there is a [some limitations](http://docs.aws.amazon.com/lambda/latest/dg/limits.html) on Lambda deployment.

> Lambda function deployment package size (.zip/.jar file) should be less then 50Mbytes.

but i just found interesting thing (maybe undocumented) - **There are no 50MByte (max) deployment package size limitation when uploading function via S3 URL!**

I'm testing other limitations (uncompressed package size limit, etc.) too.  I'll update further details soon... :)

**Comment by scaladen** [comment]
I looked at my jar size, and it was only 22MB, but then realized the zip file pulls in my target folder as well.  Adding it to the .apexignore solved the issue.  My functions deployed via apex are working well now.

**Comment by tj** [comment]
Ahh cool, closing for now!

**Comment by rodrigomaio** [comment]
I have the same issue. Will try to slim down the dependencies, but AWS SDK for Java is huge. This will probably just postpone the issue.
It would be nice to have the S3 upload alternative for deploy.

**Comment by guidiego** [comment]
@tj I think that the error on capture are related with this, only phantom binary has `67932064` byte :thinking:
