### ISSUE TITLE
Discussion: Is the Terraform usage model for Apex 'right'?

### ISSUE THREAD

**Issue by steve-gray** [apex/apex#619]
I've been trying to get a solid Terraform workflow running with Apex, but I'm hitting a few stumbling issues. It seems to me the prevalent way to use this is conjunction with something like API Gateway, but it feels like structurally the setup might be wrong. In short, because the terraform scripts live in-situ with the code it means that you need to either take on the overhead of TF modules or you have to repeatedly duplicate your Terraform files: this means stuff like state for API gateway definitions is a nightmare, and you've potentially got 3x set of scripts to keep in line - plus then how do you cleanly promote an API gateway definition across it's stages?

I think that having the Terraform scripts themselves be physically different is problematic: the per environment customisation can already be done pretty well with tokens and variables in a single set of scripts generally. There's also problems where the role ARN we use needs to be provisioned per-environment too, and we cant just use the as-is implementation. I basically run apex infra twice, once with a filter for specific assets, then again after an apex deploy.

_Proposed_: Drop Terraform specific support (deprecate, show a message on how to migrate with a link, then drop in 2-3 versions time), and have an environment variable passthrough function - so when you do:

- apex run -e env -dir workdir terraform tf-params-here

What happens is that it shells through, but setting various APEX_FUNCTION_name=ARN, APEX_ENV=blah variables as today - but *completely decoupled from Terraform* and its var models, so it can be used with other tools transparently. It means a shift from ${var} to ${env} - but then makes the whole process tool agnostic.

Then people like me can do effectively custom setups without needing Apex to support every permutation. I can just have a shell script that runs 3x Apex commands, so I can..

- apex run -e env -dir /infra/pre terraform apply
- apex deploy -e env
- apex run -e env -dir /infra/post terraform apply

Thoughts? Happy to do up the changes in a PR.

**Comment by tj** [comment]
I don't even really use `infra` personally, I just copy/paste the odd thing, I don't save much from the variables. That said I think it's kind of fine, since it's easy to ignore. It might be nicer to have apex dump out a .tfvars file so you can just refresh that periodically, not sure, I haven't wasted too many cycles thinking about it since I stopped using it

**Comment by steve-gray** [comment]
The .tfvars approach would still be Terraform-specific though - I'd love to be able to use the Apex function ARN's in other stuff besides Terraform and replace all the kludgey aws cli calls I'm doing in scripts.

**Comment by tj** [comment]
You could probably use `apex list --tfvars` as-is, that's not really coupled to TF, but judging from the stats there are a reasonable number of people using `apex infra`, so I doubt that'll go away, easy to avoid all together if you don't like/want it.

**Comment by steve-gray** [comment]
There's still one scenario I see it struggling with: I want to be be able to inject Terraform output ARNs and information (i.e. When I provision elasticsearch, how do I get that elasticsearch URL into my Apex config for the functions). Any ideas on how I might go about that? I'd like to ideally address that problem somehow too - though apex exec would be a very nice/clean approach for most things.

If you'e happy for me to take a swing at the apex exec stuff, I can try and smash that out in the next day or so - it should only be a few hours to turn it around. I did put an interim PR in for another issue with terraform to do with not passing vars to an operation that needed it, but it's unrelated.

**Comment by marioharper** [comment]
I dig this idea a lot. I've come across the same issue and really like the pass-through solution you came up with. 

For getting your elasticsearch URL into your apex functions. (If I'm understanding correctly)
You can output your elasticsearch URL from your Terraform, then when running `apex deploy` you can supply that Terraform output using the apex `-set` flag. Then the url would be accessible in your lambda via `process.env`

Example: assuming your terraform outputs a variable called `elasticsearch_url`
```sh
# in your deploy script
$ apex infra apply
$ apex deploy -s ELASTICSEARCH_URL=$(apex infra output elasticsearch_url)
```

Or, if you have a bunch of variables you want to pass to your apex lambda, pull them from Terraform and write them to a temporary file and pass that file to the `--env-file` apex flag

I'm sure you can hook that into the new `exec` command syntax specified above.
```sh
$ apex exec -e dev -dir  /infra/pre terraform apply
$ apex deploy -e dev -s ELASTICSEARCH_URL=$(apex exec -e dev -dir /infra/pre terraform output elasticsearch_url)
$ apex exec -e dev -dir /infra/post terraform apply
```

**Comment by tj** [comment]
@steve-gray sounds good to me! I like this pass-through thing. Originally I did plan on exposing the terraform outputs to apex, but haven't bothered for my own use-cases. It does become a cyclic issue as well, if you don't build things up organically, TF needs the funcs and the funcs need TF etc haha.

**Comment by heri16** [comment]
Very elegant indeed.
