### ISSUE TITLE
Lambda role does not have VPC permissions

### ISSUE THREAD

**Issue by dpurrington** [apex/apex#620]
If you have a bug report please let us know the following:

Linux vagrant 4.4.0-53-generic #74~14.04.1-Ubuntu SMP
Apex version 0.11.0

I added use of the vpc object to my config, but the role automatically created by Apex for my lambdas does not have permission to access my VPC. I get the following error when deploying:

> Error: function hello-world: AccessDeniedException: Your access has been denied by EC2, please make sure your function execution role have permission to CreateNetworkInterface. EC2
> Error Code: UnauthorizedOperation. EC2 Error Message: You are not authorized to perform this operation.

I am able to work around this issue by adding the AWSLambdaVPCAccessExecutionRole built-in policy to the role for the Lambda management.

**Comment by mooyoul** [comment]
Maybe duplicate issue (#602)?

Please read [this article](https://github.com/apex/apex/blob/master/docs/aws-credentials.md#additional-minimum-iam-policy-to-set-vpc-for-lambda). That article hasn't updated at website documentation. sorry for inconvenience.

@tj (FYI) That documentation hasn't updated at website. Should we update website doc?

**Comment by dpurrington** [comment]
Yes, it's a dup. Sorry for that, and sorry for missing that bit in the docs. I added a comment to that issue, so I'll close this one.

Thanks.

**Comment by tj** [comment]
updated :D
