### ISSUE TITLE
Lambda not created on the amazon dashboard

### ISSUE THREAD

**Issue by bussiere** [apex/apex#624]
If you have a bug report please let us know the following:

  - __Operating system__: ubuntu 16.04
  - __Apex Version__: Apex version 0.11.0

i've created my function and everything it seems working but when i log at my amazon lambda amazon console i don't see my lambda function : 

![lambda](https://cloud.githubusercontent.com/assets/24445/21414776/e5a28d50-c802-11e6-870c-bcb32ecd9230.png)

bussiere@kusanagi:~/Workspace/apex_example/test$ apex deploy -ldebug
   • loading functions in functions
   • open                      env= function=simple
   • inferring runtime         env= function=simple
   • inferred runtime          env= function=simple runtime=golang
   • deploying 1 functions    
   • deploying                 env= function=simple
   • creating build            env= function=simple
   • hook                      command=GOOS=linux GOARCH=amd64 go build -o main *.go env= function=simple hook=build
   • add shim                  env= function=simple
   • add file to zip           env= file=main function=simple
   • created build (828 kB)    env= function=simple
   • fetching config           env= function=simple
   • config unchanged          env= function=simple
   • code changed              env= function=simple local=oEG5aUvZw6m6MaTqWXtZEtW5smd2PGkAyryU+8pPs7o= remote=TSC9o3yBheVdE6K897QoZPTTcqhTysHEBRndJa6d0JE=
   • updating function         env= function=simple
   • updated alias current     env= function=simple version=2
   • function updated          env= function=simple name=test2_simple version=2
   • cleaning 1 functions     
   • hook                      command=rm -f main env= function=simple hook=clean
   • conditional flush         above_duration=24h0m0s above_size=500 age=2h23m2.169267486s size=107
   • close                    

apex invoke simple -ldebug < event.json 
   • loading functions in functions
   • open                      env= function=simple
   • inferring runtime         env= function=simple
   • inferred runtime          env= function=simple runtime=golang
{"hello":"world toto bis 2"}
   • conditional flush         above_duration=24h0m0s above_size=500 age=2h23m54.91734297s size=109
   • close                    

apex metrics -ldebug 
   • loading functions in functions
   • open                      env= function=simple
   • inferring runtime         env= function=simple
   • inferred runtime          env= function=simple runtime=golang

  simple
    total cost: $0.00
    invocations: 3 ($0.00)
    duration: 50ms ($0.00)
    throttles: 0
    errors: 0
    memory: 128

   • conditional flush         above_duration=24h0m0s above_size=500 age=2h24m27.649777209s size=110
   • close

**Comment by bussiere** [comment]
apex metrics -ldebug 
   • loading functions in functions
   • open                      env= function=simple
   • inferring runtime         env= function=simple
   • inferred runtime          env= function=simple runtime=golang

  simple
    total cost: $0.00
    invocations: 3 ($0.00)
    duration: 50ms ($0.00)
    throttles: 0
    errors: 0
    memory: 128

   • conditional flush         above_duration=24h0m0s above_size=500 age=2h24m27.649777209s size=110
   • close

**Comment by bussiere** [comment]
And i'am sure i'am at the good region : https://us-west-2.console.aws.amazon.com/lambda/home?region=us-west-2#/create/select-blueprint?firstrun=true

[profile bussiere]
output = json
region = us-west-2

**Comment by tj** [comment]
Make sure you remove the `#home` or whatever fragment from the page, I've done that a million times haha :D

**Comment by bussiere** [comment]
it's that sorry -_-

**Comment by tj** [comment]
wahoo, knew it :D
