### ISSUE TITLE
Unable to do apex init with existing role

### ISSUE THREAD

**Issue by AmitThakkar** [apex/apex#630]
I am trying to create Lambda function with `apex init` command and providing --profile <profile-name>, so apex is able to recognizing .aws/credentials but not able to recognize .aws/config file. So I am adding --region with aws init command as below:

apex init --profile <profile-name> --region us-east-1 -ldebug

And I am using
  - __Operating system__: Mac
  - __Apex Version__: 0.11.0

My credentials does not have access to create new IAM role, but there is already existing role, which I can use to create Lambda function. I am able to create Lambda function via AWS-Console, but not able to do it with apex init command. Please let me know If I am missing anything.

Here are the logs for more reference.

             _    ____  _______  __
            / \  |  _ \| ____\ \/ /
           / _ \ | |_) |  _|  \  /
          / ___ \|  __/| |___ /  \
         /_/   \_\_|   |_____/_/\_\

  Enter the name of your project. It should be machine-friendly, as this
  is used to prefix your functions in Lambda.

    Project name: test1

  Enter an optional description of your project.

    Project description: test1

  [+] creating IAM test1_lambda_function role
   ⨯ Error: creating role: AccessDenied: User: arn:aws:sts::174821928:assumed-role/myUser is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::17482928:role/test1_lambda_function
	status code: 403, request id: e6a3c-d178-11e6-925e-dfb7b74

**Comment by crafifar** [comment]
[profile yourProfileNameHere]
Us-west-2

Did you forget the word profile in your config?

Otherwise you can alias it for your terminal session....

alias aws='aws --region us-west-2'

**Comment by tj** [comment]
Hmm from ` is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::17482928:role/test1_lambda_function` it looks like you're just missing the `iam:CreateRole` permission on that profile

**Comment by tj** [comment]
LMK if still an issue
