### ISSUE TITLE
Error: function XXXX: MissingRegion: could not find region configuration

### ISSUE THREAD

**Issue by kaihendry** [apex/apex#631]
If you have a bug report please let us know the following:

  - travis
  - latest

apex doesn't seem to like either/or:
- the env `AWS_DEFAULT_REGION=ap-southeast-1`
- `aws configure set region ap-southeast-1`

Possibly related to #223 & #418

**Comment by voigt** [comment]
Hi,

I'm using Apex `0.13.0` on Windows 7, 64bit
```
C:\Users\christoph.voigt\Dropbox\Apps\ST3\ST3_Notes\inventory>C:\apex_windows_amd64.exe version
Apex version 0.13.0
```

My `.aws/config` file:
```
C:\Users\christoph.voigt\Dropbox\Apps\ST3\ST3_Notes\inventory>type C:\Users\christoph.voigt\.aws\config
[default]
region = eu-central-1
output = json

[profile testing]
region = eu-central-1
output = json
```

I'm experiencing this issue on windows. Invoke with profile settings does not seem to find the `.aws/config` file:
```
C:\Users\christoph.voigt\Dropbox\Apps\ST3\ST3_Notes\inventory>C:\apex_windows_amd64.exe -p testing invoke hello
←[31m   ?←[0m Error: function response: MissingRegion: could not find region configuration
```

Same when relying on default:
```
C:\Users\christoph.voigt\Dropbox\Apps\ST3\ST3_Notes\inventory>C:\apex_windows_amd64.exe invoke hello
←[31m   ?←[0m Error: function response: MissingRegion: could not find region configuration
```

Explicitly declaring the region works as expected:
```
C:\Users\christoph.voigt\Dropbox\Apps\ST3\ST3_Notes\inventory>C:\apex_windows_amd64.exe -p testing -r eu-central-1 invoke hello
{"hello":"world"}
```

The strange thing: I use exactly the same files `.aws/config`/`.aws/credentials` on OSX, also with Apex `0.13.0`, which works totally fine.

Is there any chance to log which config file apex is trying to read?

**Comment by kaihendry** [comment]
I get around this by passing `-r` nowadays https://github.com/kaihendry/apex-request-id/blob/master/Makefile
