### ISSUE TITLE
Deploy with dependencies

### ISSUE THREAD

**Issue by andizzle** [apex/apex#639]
Hi,

Just wondering if it's possible to have deploy process to build the function under a specific sub folder, and deploy the sub folder.

Currently the dependencies are build into the function source folder, which makes it a bit hard to source control the project when the project has multiple functions, and each has different dependencies.

Thanks.

Andy

**Comment by tj** [comment]
Hey! I'm not 100% sure what you're after, which language(s) are you using? Could you explain the setup a bit more?

**Comment by andizzle** [comment]
The language is Python, with dependencies listed in requirements.txt.

Before the build, the function folder only contains the source files:
```
├── functions
│   └── schedule_report
│       ├── config.yaml
│       ├── database.py
│       ├── envs
│       ├── function.json
│       ├── main.py
│       ├── report.py
│       ├── requirements.txt
```

But after build or deploy, all dependencies are placed in the same folder.
```
├── functions
│   └── schedule_report
│       ├── PyMySQL-0.7.9.dist-info
│       ├── config.yaml
│       ├── database.py
│       ├── envs
│       ├── et_xmlfile
│       ├── et_xmlfile-1.0.1.dist-info
│       ├── event.json
│       ├── function.json
│       ├── jdcal-1.3.dist-info
│       ├── jdcal.py
│       ├── jdcal.pyc
│       ├── main.py
│       ├── openpyxl
│       ├── openpyxl-2.4.1.dist-info
│       ├── pyexcel
│       ├── pyexcel-0.4.1.dist-info
│       ├── pyexcel_io
│       ├── pyexcel_io-0.3.0.dist-info
│       ├── pyexcel_xlsx
│       ├── pyexcel_xlsx-0.3.0.dist-info
│       ├── pymysql
│       ├── report.json
│       ├── report.py
│       ├── requirements.txt=
```

**Comment by tj** [comment]
ah I see. The build hooks are executed relative to the function's dir, but if necessary you can change dirs in the hook's script. Aside from that Apex doesn't do anything for Python deps

**Comment by andizzle** [comment]
I see, I'll give it a try, thanks very much :)

**Comment by hpgmiskin** [comment]
Hi @andizzle I know I am a little late to the party but this approach is an option

In `function.json`
```
{
  "hooks":{
    "build": "pip install -r requirements.txt -t ./env"
  }
}
```

In `main.py`
```
import os
import sys
file_path = os.path.dirname(__file__)
module_path = os.path.join(file_path, "env")
sys.path.append(module_path)
```

Then you can keep env in `.gitignore`
