### ISSUE TITLE
Cannot use apex logs or apex list without javascript

### ISSUE THREAD

**Issue by tobalsgithub** [apex/apex#641]
- OSX 10.12.2:
  - Apex version 0.11.0:

Not sure if this is a bug or not, but feels like one. I'm writing a lambda function in typescript. I've setup my local environment such that I don't have to compile to javascript for development or testing. When doing a deploy, I compile to javascript and deploy, and that works great. 

What's weird though, is that I have to compile to javascript for `apex list` or `apex logs` to work as well. It feels weird that I'd have to do anything with my code just to view the logs or list my functions.

Here's the output from `apex list`.

```
> apex list --log-level debug
   • loading functions in functions
   • open                      env= function=github
   • inferring runtime         env= function=github
   ⨯ Error: error opening function github: Runtime: zero value
```

Is there a reason the code needs to be compiled? Or is there something else I could do to view the logs without compiling to js?

**Comment by tj** [comment]
ah, the json errors are not great, but sounds like you're just missing the `"runtime": "node4.3"` or whatever. We can only infer js, go, python, and java etc not typescript

**Comment by tobalsgithub** [comment]
Ah, excellent. Adding `"runtime": "nodejs4.3",` to my `project.json` fixed the problem. Thanks!
