### ISSUE TITLE
Force deploy even when unchanged?

### ISSUE THREAD

**Issue by aneeshvaidya** [apex/apex#642]
Is there a way I can force deploy a Lambda even if code or config is unchanged? My current use case is that I'm using aliases to separate staging environments on API Gateway, so deploying from dev to production sometimes only means updating using an alias, even if the code is unchanged.

**Comment by tj** [comment]
Not at the moment, there was a discussion going here: #364

But personally I use separate environments instead of aliasing, for better isolation among services. Closing this one for now
