### ISSUE TITLE
How can I uninstall apex from my Mac?

### ISSUE THREAD

**Issue by ronpeled** [apex/apex#650]
The tool worked great however I only wanted to try it. How can I uninstall all files related to this tool? 

Note: I wish the package was managed by brew or npm.

Thank you!

**Comment by polds** [comment]
If you used the bash installer to install it just `rm -f /usr/local/bin/apex` and it'll be removed.

**Comment by tj** [comment]
yup ^ it's just a single bin. brew a bit too annoying since you have to update it all the time

**Comment by ronpeled** [comment]
that worked!

You may want to add this to your documentation somewhere. 

Thanks!
