### ISSUE TITLE
expose to Terraform function_name

### ISSUE THREAD

**Issue by visciang** [apex/apex#654]
### Feature proposal
expose to terraform (via "apex infra") the lambda function name

### Description
Apex compute the **AWS lambda function names** using the `nameTemplate` with default `{{.Project.Name}}_{{.Function.Name}}`.
For example in a project “api” with ./functions/users becomes `api_users`.

The new exposed variable could be `apex_function_name_NAME`.
In the example above we could then reference the function name in terraform as `${var.apex_function_name_users}`

If this feature is accepted I will open a pull request.

**Comment by tj** [comment]
Hmm we do `apex_function_%s` for the ARN, so I guess maybe `apex_function_%s_name`? Reads a little weird haha, feels redundant but it's not

**Comment by visciang** [comment]
Ok, it seems better!
I will open a pull request.

**Comment by tj** [comment]
Sounds good! I wonder if we should have `apex_function_%_arn` to slowly phase out the old one as well, not a build deal for this PR though

**Comment by visciang** [comment]
Yes, that could be a better naming convention now that we have more than one variable.

If you want I can open also one pull request to add `apex_function_%_arn` leaving there the old one (commenting it is deprecated)

**Comment by tj** [comment]
oops thought it was open
