### ISSUE TITLE
Public Go API

### ISSUE THREAD

**Issue by tj** [apex/apex#66]
Not a short-term thing but it would be nice to clean up Function / Project a little API-wise and advertise them as public-ish. I could see other apex related commands using these heavily later. More or less ready but I'm sure we could use some more utility functions.

**Comment by gelidus** [comment]
This would allow other applications to integrate apex. :+1:

**Comment by farazfazli** [comment]
:+1:

**Comment by tj** [comment]
closing, just not a concern for this project but some day it might be nice to move some of the internals elsewhere
