### ISSUE TITLE
Changing the region in ~/.aws/config

### ISSUE THREAD

**Issue by thejollyrogers** [apex/apex#662]
I use the AWS_PROFILE env var with apex, and I changed the region in my profile but apex is still deploying to the old region. Does it cache the profile after apex init? Is there a way to reset?

**Comment by tj** [comment]
All init does really is create the [role](https://github.com/apex/apex/blob/master/boot/boot.go#L46-L70), so you might have to copy that over to the new region.`init` was kind of a quick hack to get people started but it's not adequate for initializing from an existing repo

**Comment by thejollyrogers** [comment]
Well to be clear I'm running the command `apex deploy`, but it's not picking up the change in region in my ~/.aws/config file. If I do `apex deploy --region <region>` manually it works.

**Comment by tj** [comment]
Ah I see, hmm not sure why that would be, maybe you have an env var as well? It should try `--region -> env -> config file`

**Comment by thejollyrogers** [comment]
There's no AWS_REGION env set. I can also confirm that a brand new project also uses the old config value.

**Comment by thejollyrogers** [comment]
Actually, the AWS_PROFILE env was different in the environment I was using. This isn't a problem anymore, sorry!

**Comment by tj** [comment]
No worries! That's the main reason I don't like env vars haha, too easy to mess up
