### ISSUE TITLE
Stripping timestamps makes Clojure sad

### ISSUE THREAD

**Issue by Liath** [apex/apex#673]
Because of how jars are repackaged currently, timestamp data is omitted. (The files are streamed out of the jar into the destination upload package  ([java.go:l93](https://github.com/apex/apex/blob/master/plugins/java/java.go#L93) & [zip.go:l42](https://github.com/apex/apex/blob/master/archive/zip.go#L42)))
Unfortunately, Clojure cares about timestamps and if `.clj` and their compiled `.class`s have different timestamps it will try to recompile them. This leads to extra load time and memory usage in Lambda. 

**To reproduce:**
 - Create a lein project in an apex function folder
 - Set function.json to `runtime: java` and `build-hook: "lein uberjar && mv target/-*-standalone.jar target/apex.jar"`
 - `apex build > test.zip`
 - Run this zip how Lambda will (close enough for our uses): `java -XX:MaxHeapSize=222823k -XX:MaxMetaspaceSize=26214k -XX:ReservedCodeCacheSize=13107k -XX:+UseSerialGC -XX:-TieredCompilation -jar test.zip`
 - Load hander in resulting clojure shell `(ns test (:require [com.test.what.ever :as test]))`
 - Presumably will fail with a message like `CompilerException java.lang.OutOfMemoryError: Metaspace, compiling:(a.clj:102:3)`

**There's a few ways to fix this:**
 - Pass a lein uberjar through instead of repackaging. ([example](https://github.com/Liath/apex/tree/clojure-support))
 - Add time stamps back. ([example](https://github.com/Liath/apex/tree/set-timestamps-addbytes))
 - Strip any clojure files we can find in java.go/Build ([example](https://github.com/Liath/apex/tree/strip-clojure-sources))

Idk what's best, but the last one seems most brittle yet easiest.

References:
http://stackoverflow.com/questions/10759343/make-lein-uberjar-without-source-files - Might work for small projects, but unfortunately many of my dependencies don't use it so probably useless.
http://stackoverflow.com/questions/19594360/preserving-timestamps-on-clojure-clj-files-when-building-shaded-jar-via-maven-s - More info on clojure's timestamp shenanigans.

**Comment by tj** [comment]
Good to close this one now right?

**Comment by Liath** [comment]
Yup! Closed. :)
