### ISSUE TITLE
Hook support

### ISSUE THREAD

**Issue by tj** [apex/apex#68]
Might be nice to have some hooks for builds, linting, running tests, whatever. We could potentially move some things like the shimmed language build commands to this instead, as a default, and remove part of the `runtime.Runtime` interface.

We could then remove `runtime.Runtime` all together if we wanted, and just provide defaults for these properties. Shimmed() would be an option, Handler() an option, DefaultFile() an option, Build() would be a hook, Clean() would be a hook.

This would allow people to extend Apex without contributing Go code in core as well. For example you might even want to shim node code to act over stdio instead, just because it's nicer to work with.

We could also move the Go runtime portion to a different package then, just so they're not conflated, just apex/runtime. 

- [ ] remove runtime.Runtime
- [ ] define defaults
- [ ] refactor how inference works (define the default file detection stuff elsewhere)
- [ ] add "shim" (bool)
- [ ] add "handler" (string)
- [ ] add "hooks" (map of strings)
- [ ] add hooks for pre/post-deploy and others

Pretty sold on this I think. We shouldn't really focus on runtimes, they'll add Go support eventually and same with the others. These could also be inherited from the project level, which would be useful in most cases, for linting, pre-compiling with Babel etc.

**Comment by mthenw** [comment]
I was thinking about the same in terms of sources (especially API Gateway). There has to be some way to do some work pre-/post- function/project create/delete/update.

**Comment by pilwon** [comment]
:+1: for hook support. pre/post-deploy hooks should resolve some of my concerns in #100.

**Comment by tj** [comment]
oops thought I squashed that to a branch haha
