### ISSUE TITLE
Processing after callback

### ISSUE THREAD

**Issue by joshuarubin** [apex/apex#683]
I'm working with the Go shim right now.

I'd like to be able to response to a message very quickly but continue processing in the background. The API that is triggering this function will retry if it doesn't receive a response within `3s`, so it is critical to respond before background processes complete or else I have do find a way to dedup requests.

The way I have it set up is after `apex.HandleFunc` completes, I wait for a `sync.WaitGroup` to complete before `func main` returns.

The problem with this is that as soon as the handler returns a result, the callback is executed on the shim.

Because the shim has `ctx.callbackWaitsForEmptyEventLoop = false`, lambda kills the process before the waitgroup finishes.

Is there any way that we can update the shim to accommodate this desired behavior?

I think `ctx.callbackWaitsForEmptyEventLoop` would have to be `true`, but when I've tested with this, the function just times out and doesn't stop which is why it was set to `true` in the first place.

Do you have any suggestions?

**Comment by mooyoul** [comment]
First, That seems like job queue. You can build your own task queue using Lambda with SQS.
In this case, This article might be helpful: https://cloudonaut.io/integrate-sqs-and-lambda-serverless-architecture-for-asynchronous-workloads/

Second, Lifecycle of Lambda function.
In this case, It would be nice if you read article that describing lifecycle of Lambda functions.
I recommend reading these two links: 

1. Understanding Container Reuse in AWS Lambda - AWS Compute Blog
https://aws.amazon.com/ko/blogs/compute/container-reuse-in-lambda/

2. https://github.com/apex/apex/commit/1fe6e91a46e76c2d5c77877be9ce0c206e9ef9fb#commitcomment-20396626

**Comment by tj** [comment]
From AWS docs: "By default, the callback will wait until the Node.js runtime event loop is empty before freezing the process and returning the results to the caller".

The `callbackWaitsForEmptyEventLoop` flag doesn't work as you have in mind, it simply allows you to write "sloppy" JavaScript which does not call `callback()` properly. So if you used `wg.Wait()` in the Go case it that would be fine, but there's no way to do background work in Lambda, you have to delegate to SNS/SQS/Kinesis etc as @mooyoul mentioned.

**Comment by tj** [comment]
I should mention that you could also use https://github.com/apex/invoke to `invoke.Async()` another function to do the 'background' work. Async invokes appear to be powered by SNS, and will retry automatically (3 times) on error.

**Comment by joshuarubin** [comment]
Thanks for all the answers. I addressed my issue by just invoking another lambda func asynchronously. However, it still seems like there should be _some_ way to respond quickly to a request but still do a minimal amount of work after the response.

**Comment by tj** [comment]
Definitely leave a note if you find anything, but I don't think that's possible now by-design, since it would have no way to report potential timeouts etc.
