### ISSUE TITLE
Support chat

### ISSUE THREAD

**Issue by hneiva** [apex/apex#684]
Would be nice to bounce ideas off of other users, so I feel like this repo deserves a channel on gitter.im
Either that or a channel on freenode IRC

Ideas? Recommendations? Anything against this?

**Comment by polds** [comment]
I wouldn't mind sitting in a gitter. I'm already in quite a few :)

**Comment by tj** [comment]
We have a Slack: https://apex-dev.azurewebsites.net/

**Comment by polds** [comment]
Haha, good to know.

**Comment by tj** [comment]
closing :D
