### ISSUE TITLE
Apply --alias even if code is unchanged

### ISSUE THREAD

**Issue by clark-pan** [apex/apex#686]
I was wondering if you could consider taking a PR for this use case. Let me describe what I'm doing first and maybe you can see an obvious solution that I'm derping on:

- We have a set of lambda functions running our application.
- We have multiple environments, each with their own set of dbs/infrastructure etc.
- We have partitioned lambda functions via aliases. So theres a 'production' alias for production, 'staging' for staging, and individually named ones for each developer's environment.
- The event source for the lambda functions are through API gateway. They are separated by different stages in API Gateway, with each staging pointing to their respective alias.
- The problem comes in trying to setup a CD pipeline to bring an environment to a version.
    - We could use `apex deploy --alias {environment}`, but an alias is not deployed if the code is unchanged. This means that, in the scenario that you're deploying to production after a successful staging deploy, production won't move since the latest lambda version is the same.
    - We were thinking about using `apex alias {environment}` but that takes the environment to the latest code, which is not what we want, since each developer could be deploying their own stuff, pushing the latest version forward.
    - We also considered just having a different lambda function per environment, but that doesn't seem to really gel with what AWS recommend in their docs: http://docs.aws.amazon.com/lambda/latest/dg/versioning-aliases.html

What I want to do is change the `apex deploy` to still move the alias if the latest version of the lambda function is the same as the code being deployed. What do you think? Am I missing something obvious?

**Comment by clark-pan** [comment]
My colleague @llun just pointed me to https://github.com/apex/apex/issues/364, which is an identical problem to ours.

While the `alias` command is helpful, since in our case, you may not know from which alias you want the version to come from.

The use case that `alias` solves is the move from `[staging] -> [production]`. This would work, with staging running `apex deploy --alias staging`, and once you decide you can promote to production, you'll run `apex alias -v staging production`. That works great.

But the use case we can't seem to solve is from the many development environments to staging, since, if staging code thats being deployed is the same as whats already latest in lambda, the alias won't move. We also can't know which version/alias to promote staging from, so we can't automate `apex alias`.

**Comment by llun** [comment]
The ideal solution for me would be when deploy, `current` alias is always move to that deploy version and when adding --alias option, that alias apply to that specific version.

**Comment by tj** [comment]
How come a combo of the following doesn't work?

```
$ apex deploy && apex alias ENV
```

I don't really have a great reason not to allow it to simply alias an existing func, but it seems like a separate concern than deploying. I'd almost rather remove `--alias` all together.

**Comment by llun** [comment]
The issue is when we have two people deploy at the same time (or near to each other) we want to separate those deploy set and we tried to do it in one function structure (which probably should separate for each developer and each environment.) however after deploy command is finished, there's no guarantee for alias command to alias the deployed version.

`apex deploy && apex alias X` is what we're using now. Another way, I probably should grab the output of deploy and alias base on that.

**Comment by tj** [comment]
Ah good point I was thinking about the potential race, it's all easy with one person haha.

With that in mind, maybe what you suggest with output makes sense anyway. My biggest gripe with Lambda versions is you have no clue what they refer to, was that TJ's deploy, or Matt's deploy, what GIT sha was it, was it a tag blah blah.

That renders `apex alias` useless basically for any teams I guess. Maybe `apex deploy` outputting the functions and versions makes sense regardless, and then `apex alias prod $(apex deploy)` like you mention.

**Comment by clark-pan** [comment]
@tj Ah that solution wasn't exactly what I was going to do. I was going to go update `apex deploy -a alias` to create/update alias if the local hash is the same as the remote hash.

Like instead of logging and returning `nil` [here](https://github.com/apex/apex/blob/master/function/function.go#L269), I was going to modify it to update the alias regardless.

Would you prefer `apex deploy` outputs the versions and functions? that might be a bit harder to get things working, as you'll probably need to pipe the output to xargs or something to get apex alias working.

We've been using `apex alias` as a convenient manual way to promote a set of aliases from 1 environment to another, i.e "[staging] => [prod]".

Anyways, I'll try to get something in PR form sometime this weekend.

**Comment by tj** [comment]
I think outputting is cleaner in some ways, but after this discussion I think I'm find with `--alias` change.

I do think there's a huge gap with managing Lambda functions in regards to who deployed what, when, and what code does it correlate to, but that's a different issue.

**Comment by clark-pan** [comment]
misclick :(
