### ISSUE TITLE
Add support for excluding files from the zip

### ISSUE THREAD

**Issue by tj** [apex/apex#69]
Just causes bloat if there are extra files. A .gitignore style file would be great, inclusive might be nice as well. Needs more thought as to what this would be and where it would live. If it's in JSON we can use the project.json inheritance etc instead of maintaining it per-function.

**Comment by mthenw** [comment]
Both ways are fine, because both supports inheritance in some way (you can add `*.log` to `.apexignore` in root project dir and any log file under function's dir will be ignored).

But I lean towards ignorefile as excluding files reminds me big ugly Gruntfile configs :D

**Comment by pilwon** [comment]
:+1: for `.apexignore` with inclusion support

**Comment by mthenw** [comment]
@tj what do you think? I would take care of that if we can agree on `.apexignore`.

**Comment by tj** [comment]
.apexignore sounds good to me!
