### ISSUE TITLE
Aliases

### ISSUE THREAD

**Issue by tj** [apex/apex#7]
Provide commands for manually working with aliases. We don't recommend using aliases for environments, however they may still be useful in some cases, such as per-person aliases in a staging environment.

- [x] deploys
- [x] rollback
- [x] invoke
- [x] test
- [x] update tests so they pass
- [x] add tests
- [ ] maybe default flags to CurrentAlias so people can see that

**Comment by mthenw** [comment]
Is it still valid?

**Comment by tj** [comment]
Haven't decided yet, but I should put a description at least hahah

**Comment by tj** [comment]
- `apex deploy --alias canary`

**Comment by joshrtay** [comment]
What do you think of support for multiple aliases? Been thinking about aliasing commit hash and branch. 

    apex deploy --alias master e4ff8cb

**Comment by tj** [comment]
@joshrtay hmm possibly, I guess it would have to be `--alias master,foo,bar` or `--alias master --alias foo --alias bar`

**Comment by lhulet** [comment]
@tj did multiple aliases ever happen?
