### ISSUE TITLE
Apex invoke throws Cannot find module '/var/task/index'

### ISSUE THREAD

**Issue by santhoshdaivajna** [apex/apex#700]
- __Operating system__: Amazon Linux
  - __Apex Version__: 0.13.0

# apex deploy asg --log-level debug
   • couldn't read role from infrastructure: chdir infrastructure: no such file or directory
   • loading functions in functions
   • open                      env= function=asg
   • loaded config             config=function.json env= function=asg
   • deploying 1 functions
   • deploying                 env= function=asg
   • creating build            env= function=asg
   • add file to zip           env= file=.function.json.swp function=asg
   • add file to zip           env= file=main.go function=asg
   • created build (3.6 kB)    env= function=asg
   • fetching config           env= function=asg
   • config unchanged          env= function=asg
   • code unchanged            env= function=asg
   • cleaning 1 functions
   • conditional flush         above_duration=24h0m0s above_size=500 age=2h3m10.51732342s size=53
   • close
# apex invoke asg < event.json
   ⨯ Error: function response: Cannot find module '/var/task/index'
# apex invoke asg --log-level debug < event.json
   • couldn't read role from infrastructure: chdir infrastructure: no such file or directory
   • loading functions in functions
   • open                      env= function=asg
   • loaded config             config=function.json env= function=asg
   ⨯ Error: function response: Cannot find module '/var/task/index'

and when I invoke the deployed lambda function  I see the following error in cloudwatch logs.

```
START RequestId: afcb6446-0589-11e7-9d7a-fd7ebb470fdd Version: 5
Unable to import module 'index': Error at Module.require (module.js:353:17) at require (internal/module.js:12:17)
END RequestId: afcb6446-0589-11e7-9d7a-fd7ebb470fdd
REPORT RequestId: afcb6446-0589-11e7-9d7a-fd7ebb470fdd	Duration: 0.54 ms	Billed Duration: 100 ms Memory Size: 128 MB	Max Memory Used: 16 MB
START RequestId: c709f186-058b-11e7-bdff-4de5a10a11bc Version: 5
Unable to import module 'index': Error at require (internal/module.js:12:17)
END RequestId: c709f186-058b-11e7-bdff-4de5a10a11bc
```
```.

**Comment by tj** [comment]
hmm very weird, it might be worth trying `apex build asg > /tmp/test.zip` and making sure that index.js is being added there

**Comment by tj** [comment]
ah you should see https://github.com/apex/apex/blob/master/plugins/shim/shim.go#L21, are you maybe setting the `runtime` to something else? I need some better logging in there

**Comment by santhoshdaivajna** [comment]
```
apex build asg --log-level debug > out.zip
   • couldn't read role from infrastructure: exec: "sh": executable file not found in %PATH%
   • loading functions in functions
   • open                      env= function=asg
   • loaded config             config=function.json env= function=asg
   • creating build            env= function=asg
   • add file to zip           env= file=main.go function=asg
   • conditional flush         above_duration=24h0m0s above_size=500 age=10h36m34.7334832s size=16
   • close
```

The out.zip does not contain a index.js file.

The folder structure of source code is as below
cloudformation
      event.json
      project.json
      functions
            asg
                 main.go
                 function.json

**Comment by tj** [comment]
Any luck figuring out the issue?

**Comment by alialamine** [comment]
I just had the same problem but with python. Turned out that the default environment in my project is in nodejs but I'm creating a python module. So aws lambda was looking for js files and not the python files. 

Should we put a check before uploading that if the directory doesn't include the the correct extensions for selected environment we throw a clear error while uploading? This would save some unnecessary headakes for ppl just starting to use apex, or them thinking that the module itself doesn't work correctly.

**Comment by tj** [comment]
Hmm I think Lambda should error at the api level, it would be looking for `index.handle` if it were defaulted to node. Seems odd if it lets you upload a missing handler, I swear it used to error nicely.

**Comment by tleunen** [comment]
Got something very similar on mac after a deploy.
```
{
  "errorMessage": "Cannot find module '/var/task/lib'",
  "errorType": "Error",
  "stackTrace": [
    "Function.Module._load (module.js:276:25)",
    "Module.require (module.js:353:17)",
    "require (internal/module.js:12:17)"
  ]
}
```

**Comment by tleunen** [comment]
Looks like apex create a zip in a way that will hide the real errors.

In my case, after creating the zip and uploading the zip myself, I was able to see the real error:
```
{
  "errorMessage": "Twit config must include `consumer_key` when using user auth.",
  "errorType": "Error",
  "stackTrace": [
    "/var/task/lib/index.js:57800:13",
    "Array.forEach (native)",
    "Twitter.module.exports.Twitter._validateConfigOrThrow (/var/task/lib/index.js:57797:17)",
    "new Twitter (/var/task/lib/index.js:57371:8)",
    "new NPMTwit (/var/task/lib/index.js:49388:17)",
    "getCacheObject.then.cacheObject (/var/task/lib/index.js:18738:21)",
    "process._tickDomainCallback (internal/process/next_tick.js:135:7)"
  ]
}
```

Any reason why we cannot see the real error when deploying with apex?

**Comment by tj** [comment]
wtf, weirddd I have not run into that. If the AWS SDK checks for `>= 400` the error should be bubbling in apex(1)
