### ISSUE TITLE
Running apex deploy twice in a row causes redeploy (Apex 0.13.0 / OSX Sierra)

### ISSUE THREAD

**Issue by marcejohnson** [apex/apex#701]
`Apex version 0.13.0`
`OSX Sierra  10.12.3`

* Running apex deploy twice in a row causes redeploy.  No env changes, no function changes between deploys.  
* It does it for all my python functions **only**, not my javascript functions.
* Folks have brought this up in previous releases, such as mentioned here #454, but I didn't want to comment on closed or inactive threads.  

I'll provide detail below if helpful.  

When I do a dry-run it says there is nothing to update as shown:
```
$ apex deploy slackCommand-post --dry-run

  + alias rambl-slackCommand-post
    alias: current
    version: $LATEST
```

Then I run it fully and it thinks something changed:
```
$ apex deploy slackCommand-post --log-level debug
   • couldn't read role from infrastructure: chdir infrastructure: no such file or directory
   • loading functions in functions
   • open                      env= function=slackCommand-post
   • loaded config             config=function.json env= function=slackCommand-post
   • deploying 1 functions    
   • deploying                 env= function=slackCommand-post
   • creating build            env= function=slackCommand-post
   • add file to zip           env= file=main.py function=slackCommand-post
   • created build (1.4 kB)    env= function=slackCommand-post
   • fetching config           env= function=slackCommand-post
   • config changed            env= function=slackCommand-post
   • updating config           env= function=slackCommand-post
   • updating function         env= function=slackCommand-post
   • updated alias current     env= function=slackCommand-post version=18
   • function updated          env= function=slackCommand-post name=rambl-slackCommand-post version=18
   • cleaning 1 functions     
   • conditional flush         above_duration=24h0m0s above_size=500 age=1h35m15.225320016s size=116
   • close    
```

It says "config changed" but I did not change anything.

Here is my project.json:
```
{
  "name": "rambl-aws",
  "description": "rambl lambda function",
  "memory": 256,
  "timeout": 30,
  "environment": {},
  "nameTemplate": "rambl-{{.Function.Name}}",
  "retainedVersions": 100
}
```

Here is the function.json:
```
{
  "description": "This function handles a Slack slash command for Rambl",
  "runtime": "python",
  "timeout": 10,
  "memory": 128,
  "role": "XXXYYYCommentedOUT"
}
```

The associated function directory just contains `main.py` and `function.json`.

Just running apex deploy twice in a row, with no changes, causes redeploy.

What may I do to prevent redeploy of unchanged python when I run `apex deploy`?

**Comment by tj** [comment]
Hmm sounds like a bug, I'll try and check it out sometime soonish

**Comment by tchia04** [comment]
I have the same issue too.

**Comment by tj** [comment]
I remembered to check today, I'll try and look into it soon

**Comment by marcejohnson** [comment]
Did something change between releases that might cause redeploy for python code but not javascript?  Thanks for looking into it.

**Comment by clark-pan** [comment]
@tj I ran into this while I was fixing #686 
The issue is the diff detection for the config always detects a change in the DeadLetterARN if you haven't specified a config value for DeadLetterARN
