### ISSUE TITLE
Functions are not added to Lambda (no errors)

### ISSUE THREAD

**Issue by mo-mueller** [apex/apex#702]
If you have a bug report please let us know the following:

  - __Operating system__: Windows 10
  - __Apex Version__: 0.13.0

In AWS IAM I have created a new user with AWSLambdaFullAccess and IAMFullAccess. I ran "aws configure" and inserted the access key and the secret access key and also the region. Then I have started a new apex project with "apex init". And then I ran "apex deploy". There are no error messages, everything seems to be okay. But the functions are not added in AWS Lambda. In IAM I can see the generated role for my project. And "apex invoke hello" is also working.

I just started with AWS today, so it is possible that I missed something and its not an apex related issue. But do you have an idea what could be the reason for that?

**Comment by tj** [comment]
Ah, you probably still have `#home` or whatever in the console URL. I've done that a lot :D try removing that from the URL or re-navigating to Lambda's page, it should show the functions then instead of the "splash" page.

**Comment by mo-mueller** [comment]
Thanks for the fast answer. But I think my mistake was an other. I have set "eu-west-1" as the region but in my dashboard I was on "eu-central-1". I thaught the functions are on each region the same. Now I have set "eu-central-1" as the region and now it works.
