### ISSUE TITLE
apex infra and a circular reference problem

### ISSUE THREAD

**Issue by aweiland** [apex/apex#706]
I'm looking at using terraform and apex to manage my infrastructure and I'm running in to a problem:

- Deploy apex managed lambdas
- Use "apex infra" to deploy the rest of the infrastructure including IAM roles for the lambdas

Each of these are dependent on each other.  I need the roles in place to deploy the lambdas, but I need references to the lambdas for the rest of the infrastructure (e.g. as API gateway endpoints).

Any ideas on how to get around this?

**Comment by tj** [comment]
Ah dup of #377. TL;DR no solution at the moment
