### ISSUE TITLE
Add apex-dev Slack to documentation

### ISSUE THREAD

**Issue by tj** [apex/apex#71]

**Comment by tmaiaroto** [comment]
+1 or simply channel on Gophers slack. or even gitter if Slack is $$.

**Comment by mthenw** [comment]
I've deployed it on Azure (hopefully it will be free but I need to ask support :)) https://apex-dev.azurewebsites.net/ 

Added slackin badge https://github.com/apex/apex/commit/f794c26c7761f96971e03d7b29768cb14247ebfe

**Comment by tj** [comment]
:+1:
