### ISSUE TITLE
Doubt: why does LoadFiles() function doesn't return anything?

### ISSUE THREAD

**Issue by boddumanohar** [apex/apex#716]
Hey Guys, I am having a small doubt. I don't know whether this is the proper place to ask such doubts. 
In https://github.com/apex/apex/blob/master/utils/utils.go#L64 of package utils, the format of the `LoadFiles` function is 
```
func LoadFiles(root string, ignoreFile []byte) (files []string, err error)
```

That means the function should return `files`  and `err` variables. But the line 64 returns nothing.

**Comment by tj** [comment]
Go allows you to have "naked returns", if you don't explicitly return variables there it will simply return the `files` and `err` vars. It's typically considered bad practice but in some cases I think it reads fine.
