### ISSUE TITLE
Add runtime support for Node 6.10

### ISSUE THREAD

**Issue by gurre** [apex/apex#717]
Lambda now supports Node 6.10 it would be awesome to have that option in function.json.

http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html

**Comment by tj** [comment]
the latest version has it, `apex upgrade` and you should be good to go!

**Comment by gurre** [comment]
Suppose the docs are missing then.

**Comment by tj** [comment]
oops yeah just pushed that, forgot to update them

**Comment by gurre** [comment]
Cheers! Good job.
