### ISSUE TITLE
Apex Installed, Getting 'Not: command not found'

### ISSUE THREAD

**Issue by wontwon** [apex/apex#721]
- __Operating system__: Mac OSX Sierra, 10.12.4
  - __Apex Version__: v0.14.0

Hi all, I'm just going through the process of installing apex, but upon doing install, I cannot run apex at all. This is what I am currently getting:

<img width="501" alt="screen shot 2017-04-16 at 10 46 36 pm" src="https://cloud.githubusercontent.com/assets/3239936/25080126/fd6e3962-22f6-11e7-9d5b-d66cfc6ae2d9.png">

Any ideas?

**Comment by polds** [comment]
Two ideas come to mind, double check `/usr/local/bin` is in your PATH and double check apex has been chmod to an executable state such as `+x`

**Comment by wontwon** [comment]
@polds, /usr/local/bin is in my path and chmod'd apex to executable state, but no luck still. Followed another thread #474 , and tried to troubleshoot based off of conversation as well without success. 

Any other thoughts?

**Comment by wontwon** [comment]
Anything wrong with the install script?

**Comment by wontwon** [comment]
Bumping this, really would like Apex to work on my machine. If there's anything additional to troubleshoot, I am happy to provide more info. Thanks.

**Comment by wontwon** [comment]
I ended up trying to hit the path to the binary that was generated by the script
```
https://github.com/apex/apex/releases/download/v0.14.0zipball_url/apex_darwin_amd64
```
and was taken to a 404, so I ended up removed 'zipball_url' from the path:

```
https://github.com/apex/apex/releases/download/v0.14.0/apex_darwin_amd64
```
 downloaded the binary into my /usr/local/bin and turned it into an executable file. Apex is now working for me.

**Comment by wontwon** [comment]
This needs to be changed in the install shell script.

From:
```
LATEST=$(curl -s https://api.github.com/repos/apex/apex/tags | grep -Eo '"name":.*[^\\]",'  | head -n 1 | sed 's/[," ]//g' | cut -d ':' -f 2)
```

To:
```
LATEST=$(curl -s https://api.github.com/repos/apex/apex/tags | grep -Eo '"name":.*?[^\\]",'  | head -n 1 | sed 's/[," ]//g' | cut -d ':' -f 2)
```

**Comment by wontwon** [comment]
@tj

**Comment by tj** [comment]
hmm weird works fine to me on osx
