### ISSUE TITLE
`apex dev` runs a serverless app locally

### ISSUE THREAD

**Issue by samalba** [apex/apex#722]
This is an idea for a new feature.

# Context

Running your serverless app locally, and in a fast and repetitive way is key
for development productivity.

However being tied to AWS Lambda environment makes it challenging as the app
relies on proprietary services such as the API Gateway, the Lambda runtime
libraries and (the Lambda service itself).

While it's not possible to entirely replicate the Production environment, it's
possible to emulate a local environment close to Production.

# Proposal

A new command `apex dev` spawns a local environment that the user can hit for
testing the app without deploying it to AWS Lambda.

Once you run `apex dev`, apex builds the app into a container (the container
image contains both the result of `apex build` and the same runtime than AWS
Lambda. After the containers are created and running, the CLI blocks on the
app logs (similar output than `apex logs -f`).

Once the user interrupts the CLI (SIGINT), the containers are stopped.

# Implementation

This is not exhaustive, just ideas on how to implement and what dependency can
be leveraged.

## Container runtime

[Docker for Desktop (Mac or Windows)](https://docs.docker.com/docker-for-mac/)
can be the containers runtime, it has the advantage of having an easy
installer, is actively and maintained and support upgrades.

It's important the the container image itself is similar to the environment
used on production. [docker-lambda is a public container image](https://github.com/lambci/docker-lambda)
which is actively maintained. It is built from the real AWS Lambda environment
and can be used as a base image to build the dev app.

The first the user runs `apex dev`, the command will check that dependencies
are satisfied (container runtime up and running, container images pulled, apex
build hook is configured).

## API Gateway

It's important to have an easy way to configure the API gateway, in the same
way the user would do it on the AWS Gateway service.

The API server can be configured from a YAML file named api-dev.yml, that
should be place in the root directory.

Example:

```yaml
/api/hello:
    method: GET
    function: hello
```

When the user runs `apex dev`, apex (or an apex build hook) parses the Yaml
file and generates a corresponding nginx configuration.

An nginx container is then spawned on the local container runtime with the
above generated config.

For trying the local app, all connections should be directed to the API Gateway
container.

## Possible future improvements

 * IDE integration
 * Emulate IAM role configuration and enforcement
 * Web UI for configuring the API Server and introspect the functions

**Comment by tj** [comment]
I personally only use API Gateway with a single function (per api, not per endpoint), and I use a regular Go net/http server so local testing isn't an issue there.

I think even if someone where to contribute this as a feature I'd have to respectfully decline, just because it would be a large maintenance burden, and I'm effectively the only dev now. Given time and money I'd agree though!

cheers
