### ISSUE TITLE
Python 3.6 Runtime

### ISSUE THREAD

**Issue by jasonamyers** [apex/apex#723]
I'd like to have the Python 3.6 runtime available in Apex.

https://aws.amazon.com/releasenotes/5198208415517126

I'd be happy to take a stab at a PR for it.

**Comment by jasonamyers** [comment]
@tj thank you so very much!!! Gonna deploy a 3.6 function now.

**Comment by tj** [comment]
hope it works :D I should really add some tests but it should be fine

**Comment by q** [comment]
any chance we can get a release on this?

**Comment by shirakia** [comment]
Dose this really work?

When I do `apex deploy`, it says
```
⨯ Error: error opening function form: Handler: zero value
```

My project.json is like this.
```
{
   "name": "foobar",
   "description": "",
   "runtime": "python3.6",
   "memory": 128,
   "timeout": 5,
   "role": "arm:aws:iam......."
}
```
The version is v0.14.0.

**Comment by tj** [comment]
@shirakia pushing a new release with this stuff

**Comment by shirakia** [comment]
@tj thanks!!! it works well
