### ISSUE TITLE
Why does Apex use a forked version of Cobra?

### ISSUE THREAD

**Issue by jtstuar1994** [apex/apex#724]
I'm using the up-to-date version of Cobra from spf13 and just was curious as to why it was forked for this project? So if I were to try to utilize some of Apex's functionality into another project that is based on spf13's version of Cobra, will they still be compatible?

**Comment by tj** [comment]
I wouldn't rely on any of this repo's packages, I should move them into ./internal at some point they're all private basically. I forked cobra just to improve the output whitespace a bit (subjectively)
