### ISSUE TITLE
Request for PHP Support

### ISSUE THREAD

**Issue by jonee** [apex/apex#725]
This link might help
https://aws.amazon.com/blogs/compute/scripting-languages-for-aws-lambda-running-php-ruby-and-go/

**Comment by tj** [comment]
Happy to check out a pull-request but it's not something I'd use personally!

**Comment by DavidTPate** [comment]
Yeah, definitely agree. @jonee I'm not sure that any of us working on Apex use PHP in our day-to-day or personal projects. Definitely interested in a PR if you (or someone else) wants to take a stab at it.

**Comment by jonee** [comment]
PHP and Ruby is similar in that you need to bring your own binary.

PHP has to be statically compiled in- Public Amazon Linux AMI version (AMI name: amzn-ami-hvm-2016.03.3.x86_64-gp2) in order for it to work. Did not work when I compiled in Ubuntu and Fedora 25.

For Ruby you can use travelling ruby binaries. 

But instead of having runtimes for PHP and Ruby- why not a Custom Runtime- where you just zip everything in a folder before deploying ? Let the user bring their own binaries. And it is likely to also work for possibly more languages. 

I got some working code examples for both language (which I also most likely adapted from somewhere) I can share. 

ps The lamdba run time is not so good for both PHP and Ruby as compared to Golang but some people might have a need for it. Maybe because it is interpreted and not run directly.

**Comment by DavidTPate** [comment]
We'd definitely be willing to check out a pull-request if someone is willing to take this on. I don't believe any of us use PHP or even possibly Ruby in our day-to-day currently.

**Comment by jonee** [comment]
Apologies for not getting back earlier. 

Here are sample codes for working in PHP and Ruby if anyone could make a good use for it
https://github.com/jonee/apex_php_ruby

I am afraid there is really no need to add those languages directly into Apex as you can already work on it right now like what I did. Unfortunately, the ping or execution duration is quite high for PHP and Ruby (as compared to Golang)- so I would not recommend people to use it for Aws Lambda. 

Issue maybe closed already. Thanks a lot!
