### ISSUE TITLE
Deploying Golang Function Error: no build hook ... no buildable Go source files in

### ISSUE THREAD

**Issue by siegesmund** [apex/apex#750]
I'm trying to deploy a Go function that depends on the xml parsing package Gokogiri. It works well locally, but when I try to deploy it, I get the following error: 

loading functions in functions
   • open                      env= function=process_filing
   • inferring runtime         env= function=process_filing
   • inferred runtime          env= function=process_filing runtime=golang
   • deploying 1 functions    
   • deploying                 env= function=process_filing
   • building zip              env= function=process_filing
   • creating build            env= function=process_filing
   • hook                      command=GOOS=linux GOARCH=amd64 go build -o main *.go env= function=process_filing hook=build
   ⨯ Error: function process_filing: build hook: ../../vendor/github.com/jbowtie/gokogiri/xml/document.go:12:2: no buildable Go source files in /Users/peter/Documents/Programming/Go/src/Apex/vendor/github.com/jbowtie/gokogiri/help
../../vendor/github.com/jbowtie/gokogiri/gokogiri.go:11:2: no buildable Go source files in /Users/peter/Documents/Programming/Go/src/Apex/vendor/github.com/jbowtie/gokogiri/html
../../vendor/github.com/jbowtie/gokogiri/xml/document.go:14:2: no buildable Go source files in /Users/peter/Documents/Programming/Go/src/Apex/vendor/github.com/jbowtie/gokogiri/xpath

Gokogiri depends on libxml, so I'm guessing that's one possible culprit. Anyone else encounter this error? Any ideas would be much appreciated!

OS is macOS Sierra. Go version is 1.8.1. Apex version is 0.14.0.

**Comment by tj** [comment]
hey!

You might have issues cross-compiling with native dependencies like libxml, but check out this [blog post](https://medium.com/apex-serverless/docker-builds-for-apex-1-62493e56ad8f) for an example of compiling via Docker

**Comment by tj** [comment]
closing for now but that should work!

**Comment by siegesmund** [comment]
That blog post solved my problem. Many thanks!
