### ISSUE TITLE
Including node_module dependencies to lambda deployment.

### ISSUE THREAD

**Issue by javaherian** [apex/apex#753]
Hi all,

We have a few `.js` scripts which we deploy to AWS Lambda in the traditional way, however, those scripts rely on dependencies in `node_modules`. How does Apex deal with dependencies? Is there any way/documentation to upload the scripts with the dependencies? 

Thanks

**Comment by maxbeatty** [comment]
Apex does not automatically include your dependencies. I'm solving this by using the [babel-wepback2 example](https://github.com/apex/apex/tree/3d9c49697021a02cbdab98b98e07dbbe7ce1c75b/_examples/babel-webpack2).

**Comment by tj** [comment]
^ is correct, Apex doesn't do anything specific per-language, it just deploys what is in the function's directory. Webpack / browserify can be handy to pull them in, alternatively you kind of need a `build` hook to copy the modules in (slow).

I believe Serverless has a nicer structure for scripted languages with shared dependencies, I'm primarily using Apex with Go so it's not really tailored to that

**Comment by javaherian** [comment]
fantastic, thank you guys
