### ISSUE TITLE
Fix -C chdir flag

### ISSUE THREAD

**Issue by tj** [apex/apex#757]
Last I checked this is too low in the execution to work properly, thus it will not pick up the functions properly etc

**Comment by ianrtracey** [comment]
Interested in working on this. Not quite sure what the specific bug is.

**Comment by tj** [comment]
it's just in the wrong spot :D, if we move it before any other work it should effectively be `(cd DIR && apex ...)`

**Comment by ianrtracey** [comment]
on it.
