### ISSUE TITLE
Guide to Adding a Runtime

### ISSUE THREAD

**Issue by jasonzoladz** [apex/apex#760]
I'd love to submit a PR adding Haskell as a runtime via the shim.  Would you accept such a PR?  (I'm aware that, like rust, it'd be linux only, and that it would need to statically-link the executable or build against Amazon Linux.)

Also, any chance you'd consider putting together a short guide (or perhaps even just a brief list of potential gotchas) regarding apex plugin creation?

**Comment by DavidTPate** [comment]
@jasonzoladz we'd definitely love to see a PR.

I personally don't have plans to create such a guide (but I don't speak for everyone). If one came up in a PR would definitely consider it.
