### ISSUE TITLE
Latest v0.15.0 executable is not found

### ISSUE THREAD

**Issue by touchdown** [apex/apex#764]
Can't find an executable to install using 
`curl https://raw.githubusercontent.com/apex/apex/master/install.sh | sh`

perhaps it should be version controlled and not always downloading the latest?

**Comment by juanqui** [comment]
Simple to work around, but just in case, something like this will work.
`wget https://github.com/apex/apex/releases/download/v0.14.0/apex_darwin_386 -O /usr/local/bin/apex`
Replace with correct build for your arch/os.

**Comment by tj** [comment]
sorry about that, I had a bad connection so I couldn't upload the bins. They'll be up in a minute or two
