### ISSUE TITLE
Apex Deploy does not deploy lambda functions

### ISSUE THREAD

**Issue by prakashsanker** [apex/apex#765]
I might be using `deploy` wrong.

I run `apex deploy`, everything seems to be fine. I invoke the function, and the correct version runs.

However, when I go to my lambda dashboard page in AWS console, I see that none of my functions are updated (their last modified is the date of creation). When I try integrating with API Gateway, an old version of the function runs.

Do I need to do something else to deploy my lambda functions?

If you have a bug report please let us know the following:

  OSX 10.12.1
  Apex v0.15.0

**Comment by tj** [comment]
Hmm possibly deploying to a different region? Or maybe you need to re-deploy the API (Gateway)

**Comment by prakashsanker** [comment]
nope I'm on the right region. Not sure why I'd redeploy API Gateway - shouldn't `apex deploy` either create or update a lambda function?

**Comment by prakashsanker** [comment]
region was it! That was stupid of me. (New to AWS)

**Comment by tj** [comment]
woot :D
