### ISSUE TITLE
Question: How to share code between functions?

### ISSUE THREAD

**Issue by luebken** [apex/apex#772]
I couldn't find an answer to a rather obvious newbie question. So I thought it's worthwhile posting.

I have two nodejs functions in separate folders. How would I share utility functions between those?

**Comment by DavidTPate** [comment]
I'm not sure what language you're using, I'm guessing it is Node.

There's a number of ways to go about doing this and it really depends on what you are trying to accomplish. As pointed out [here](https://stackoverflow.com/a/21491889/1076683) you could create a module or event just reference another file.

For example:
`lib/index.js`
```
const utilities = require('./utilities');
module.exports = {
  someFunction: () => {
    return utilities.doSomeUtility();
  }
}
```

`lib/utilities.js`
```
module.exports = {
  doSomeUtility: () => {
    // do something
  }
};
```

**Comment by luebken** [comment]
Thanks for the answer but my problem is the following:

Let's say the `lib/` lives under `function/`. Is it possible to refer to  `lib/utilities.js` from a different function? e.g. if I have `function/foo/index.js` could I do something like:

```
const utilities = require('../lib/utilities');
module.exports = {
  someFunction: () => {
    return utilities.doSomeUtility();
  }
}
```

**Comment by DavidTPate** [comment]
Yeah, give it a try and you'll see that it is indeed possible.

**Comment by luebken** [comment]
For now I have symlinked a folder with the utilities into the two functions folder. Seems to work. But would be interested if that is the canonical apex way. ;-)

**Comment by tj** [comment]
`npm link`ing them might be a tiny bit nicer, it's definitely a bit awkward for scripted languages

**Comment by luklss** [comment]
I have the same question, but for python. Don't want to duplicate my utility.py since it becomes hell to maintain.

Any ideas?

**Comment by luklss** [comment]
I actually solved by adding this to my hook:
```"build": "pip install -r requirements.txt -t .; cp -a ../../libs/ ."```
