### ISSUE TITLE
Passing in IAM role to project.json programmatically?

### ISSUE THREAD

**Issue by damacus** [apex/apex#775]
Currently it seems to be only possible to set roles in project.json or project.[prod,dev,foo].json

And it's required to set the IAM role with an account name hardcoded e.g. 
```json
  "role": "arn:aws:iam::1234567890:role/lambda_role-foo-prod",
```

What would be nice is to:
- pass in a role from the command line (the current --iamrole flag makes the user assume a role)
- give it a role name without a full arn (it should/does know which account/region etc it's in anyway as it complains when accounts don't match)  

disclaimer: I'm coming from a terraform deployment model where I don't need to hard code any variables, and I might be asking for too much from a json config file...

**Comment by damacus** [comment]
Looks like #532 would probably make this work. 

Relates to #628

**Comment by tj** [comment]
Definitely would be nice to have, just not something I've needed personally yet. #532 would be pretty good but this one probably deserves its own flag

**Comment by damacus** [comment]
👍 Cool. Thanks for updating. I'm not really sure how we'd even go about this using the project.json (even if I did program in Go).
