### ISSUE TITLE
Feature request: Function alias

### ISSUE THREAD

**Issue by kyanh-huynh** [apex/apex#778]
Can `apex` allow me to change the name of deployed function? 

For the project `foo` and the function `<foo>/functions/bar/`, `apex` tries to deploy new function `foo_bar` on AWS lambda. However, I want to change `foo_bar` to something else. Any option to support this would be great.

**Comment by tj** [comment]
Originally there was .name in the function.json config, but I didn't like having that indirection, just makes things confusing for anyone reading the app.

__However__ there is `nameTemplate` if you want to get rid of the project prefix, if you search for that on http://apex.run/

**Comment by kyanh-huynh** [comment]
That's great.

Does the template change for every function in my project? What if I just want to have some a custom template for a specific function?

Thanks again,

**Comment by tj** [comment]
I believe it's global right now, I actually forget haha. Personally I don't really want to allow overriding individual names, it's misleading to have say ./functions/hello and name it "world" in Lambda, just confuses anyone else on the team IMHO.

**Comment by kyanh-huynh** [comment]
That makes sense.

`apex` ignores symlink (I have tested.) However, `apex` still works fine with a real function directory whose files are symlink.

```
functions/foo/index.js
functions/foo-alias/index.js -> ../foo/index.js
```

That's not perfect, but at least it's a work around ;)

PS: The design is good. However, sometimes it's great to have an option to work with legacy systems and/or migration. This is the reason I use Terraform instead of Cloudformation: I have a lot of freedom when handling legacy systems with Terraform, while CF gives me no choice ;)
