### ISSUE TITLE
Add GraphQL example

### ISSUE THREAD

**Issue by sbussard** [apex/apex#779]
GraphQL is hot right now.
If there's interest, I'll make a PR with this code.

https://github.com/sbussard/lambda-graphql-apex

**Comment by maxbeatty** [comment]
This would be a good example for [apex/up](https://github.com/apex/up) when it is ready since this example will most likely want an API Gateway 👍

**Comment by tj** [comment]
Ahh yep! I've got a graphql example for Up ready to go. Up so basically the app-centric equivalent of Apex, since I personally never really want to split my APIs or apps into dozens of functions, one is fine for me haha, or maybe a few that are mounted together at paths.

**Comment by sbussard** [comment]
I look forward to it!

**Comment by bradennapier** [comment]
Hey Guys!  I use graphql, lambda, and apex quite a bit... whlie this isnt a complete example - it is the base of what is used in my lambda app with amazing results!  My queries are like 10-20x faster than before as well with the addition of data loader.

https://github.com/Dash-OS/graphql-dataloader-example
