### ISSUE TITLE
Autocompletion for function names

### ISSUE THREAD

**Issue by tj** [apex/apex#78]
And document install so people know where to put the script, possibly add a `make install` target. Later on I think we'll be utilizing dynamic autocomplete quite a bit more so it would be cool to get it started.

**Comment by tj** [comment]
Might need a replacement for #89 anyway

**Comment by SmilingNavern** [comment]
Hello, i want to try this. Could you please explain a bit more. We need bash autocompletion script or it should be inside of go code? 

As i see in master you are already using cobra for cmd parsing?

**Comment by tj** [comment]
- https://github.com/spf13/cobra#generating-bash-completions-for-your-command

**Comment by JohnAllen** [comment]
@tj Would you want this Cobra autocomplete stuff in ````main.go````, like [Cobra suggests](https://github.com/spf13/cobra#example)?  I imagine you would want this stuff in a separate file, but I'm not sure.  I'm working on this and would like to have the Cobra stuff where it will end up so let me know.

**Comment by tj** [comment]
Hmm from the readme I'm not super clear on what their autocompletion stuff looks like haha. Hopefully we can augment it to support the dynamic function names as well.

**Comment by JohnAllen** [comment]
Nevermind, I see this is for lambda function names, not Apex functions...

**Comment by JohnAllen** [comment]
Right, ok.  The apex function autocompletes have been implemented right?  You're only looking for user-specific lambda function name autocompletes, now?

**Comment by tj** [comment]
Nah it's for both! We removed the old stuff since it was generated from Docopt, but even getting back apex's would be cool for now, we can add functions later

**Comment by JohnAllen** [comment]
Ok, the reason I asked that is I see the cobra imports in the `command.go` files and cobra command stuff in seemingly all of apex functions, [like in `delete.go`](https://github.com/apex/apex/blob/master/cmd/apex/delete/delete.go).

````var Command = &cobra.Command{
	Use:     "delete [<name>...]",
	Short:   "Delete functions",
	Example: example,
	RunE:    run,
}````

So that doesn't work?  Obviously I haven't actually used apex yet - working on getting the binary installed now so I can see what works and what doesn't.
