### ISSUE TITLE
Support of disabling implicit environment variables on functions?

### ISSUE THREAD

**Issue by sorah** [apex/apex#792]
Lambda@Edge doesn't support environment variables on functions at all, and CloudFront returns an error when setting Lambda function with any environment variables on a CF behavior.

Apex sets `LAMBDA_FUNCTION_NAME` and `APEX_FUNCTION_NAME` implicitly onto functions (and this cannot be disabled), so manual modification on functions is required to make functions available for Lambda@Edge.

**Comment by tj** [comment]
Ahh interesting, good to know. It takes a special `"runtime"` as well right? Happy to check out a pull-request if anyone wants to check for edge and set `SkipEnvironment` == true or something similar

**Comment by sorah** [comment]
According to the today's GA release, runtime is now generic `"nodejs6.10"`

**Comment by deybhayden** [comment]
Given this ☝️, would it be preferred to have Apex keep a `edge` specific runtime like `"nodejs6.10-edge"` or introduce an `"edge"` bool in the function config to skip setting environment variables?
