### ISSUE TITLE
Support for altassian localstack

### ISSUE THREAD

**Issue by andybar2** [apex/apex#794]
Is it possibly to customize the AWS endpoints' URLs that apex uses and make it deploy functions on an altassian localstack (https://github.com/localstack/localstack) instead of the real AWS service?

I couldn't find a way of doing that with the available config options, but if that's possible I think it would be a very interesting setup for developers because it provides a way of doing local testing of the lambda functions without an active connection to AWS, and will also avoid paying AWS fees while developing.

**Comment by tj** [comment]
Ah interesting, not at the moment but sounds like a good thing to throw in there!

**Comment by andybar2** [comment]
Yes, I agree with you. From my research, localstack seems to be a very good option because it supports a lot of AWS services, and it's being actively maintained. They also provide a cli tool wrapper in order to use with the localstack without the need of a dummy profile setup: https://github.com/localstack/awscli-local

**Comment by rv-rsouza** [comment]
This would be an awesome feature.
Localstack is a really good toolset and is backed by Atlassian devs.
Please consider adding this feature in next release.

**Comment by theogravity** [comment]
Anyone manage to get this to work?

I tried:

`apex init --endpoint http://localhost:4574`

but, get 

```
   ⨯ Error: creating role: SerializationError: failed to decode query XML error response
caused by: expected element type <ErrorResponse> but have <title>
```

on the latest localstack
