### ISSUE TITLE
Which is the best way to add npm dependencies? 

### ISSUE THREAD

**Issue by rafaeh1** [apex/apex#797]
I'm trying to add npm dependencies to my apex functions but I don't know which is the way to add them.

**Comment by tj** [comment]
Apex doesn't do anything specific for Node, so the node_modules just have to end up in the function's directory, ensuring they'll be added to the zip.

**Comment by tj** [comment]
We have Slack too if you're ever wondering about questions https://apex-dev.azurewebsites.net/
