### ISSUE TITLE
Error: function web-app: InvalidParameterValueException: The role defined for the function cannot be assumed by Lambda.

### ISSUE THREAD

**Issue by ramitsurana** [apex/apex#799]
Operating system: Ubuntu 16.04
Apex Version: v0.15.0

My json file:

````
{
  "name": "sample-go",
  "description": "sample2",
  "timeout": 5,
  "memory": 512,
  "runtime": "golang",
  "role": "arn:aws:iam::<act-id>:role/sample-go_lambda_function",
  "environment": {}
}
{
  "name": "web-app",
  "description": "sample1",
  "timeout": 5,
  "memory": 512,
  "runtime": "golang",  
  "role": "arn:aws:iam::<act-id>:role/web-app_lambda_function",
  "environment": {}
}
````

On running apex list:
````
$ apex list

  sample-go (not deployed) 
    runtime: nodejs4.3
    memory: 512mb
    timeout: 5s
    role: arn:aws:iam::<act-id>:role/sample-go_lambda_function
    handler: index.handle

  web-app (not deployed) 
    runtime: nodejs4.3
    memory: 512mb
    timeout: 5s
    role: arn:aws:iam::<act-id>:role/sample-go_lambda_function
    handler: index.handle
````

Hi everyone, I have a 2 part problem. I am trying to run some lambda functions in go and unfortunately it is not running well.I see that functions are getting created but the functions are unable to deploy.I have tried apex with nodejs before and it worked fine but not on go. My error received is as follows

````
⨯ Error: function web-app: InvalidParameterValueException: The role defined for the function cannot be assumed by Lambda.
	status code: 400, request id: 9780cb6e-7e6b-11e7-a0cf-adee28f18767
````

Also when I try running apex list it does not change my runtime function value that I added in my json file. Any thoughts ?

**Comment by tj** [comment]
The runtime will still mention Node.js, since it uses a shim to send events to Golang's binary. 

As far as the error goes, did you change the IAM role at all in AWS? The one Apex creates should be fine, but otherwise that just sounds like a regular IAM permission issue (unrelated to Apex itself)

**Comment by ramitsurana** [comment]
Okay.I checked it by creating another apex init command. Somehow it runs fine with nodejs. Does the go code always require go-apex as shown in the _examples dir  ? Saw some similar issue [Ref](https://github.com/apex/apex/issues/478).

**Comment by tj** [comment]
@ramitsurana yep, currently since Lambda doesn't support Go natively go-apex is required. Depending on what you're doing you might be interested in github.com/apex/up, it's designed for applications instead of functions

**Comment by ramitsurana** [comment]
Thanks @tj .Hopefully after golang lambda support we won't require shim in apex and the apex list cmd will be able to show golang runtime.Will be closing this issue now.Thanks for your support.
