### ISSUE TITLE
Version listing command

### ISSUE THREAD

**Issue by tj** [apex/apex#80]
It would be nice to have a version listing command, especially for performing rollbacks. Maybe display the time of deployment etc. Something like:

- `apex list --versions`
- `apex list --versions <name>`

TODO: decide on output

**Comment by tj** [comment]
we should output the ARNs as well, critical for TF integration

**Comment by mthenw** [comment]
Currently it looks like

```
➜  apextest  AWS_REGION=eu-west-1 apex list

  - test (nodejs)

```

Proposition: 

```
➜  apextest  AWS_REGION=eu-west-1 apex list

  - test (nodejs)
    - 50
    - 49
    - 48

```

imho no need to output ARN if we have separate command mode for tfvars.

**Comment by tj** [comment]
yea leaving ARN out of the regular output sounds good! the `apex list` output as-is is pretty useless, it would be nice to have some more info and make it look more like the other output (blue name blah blah)

**Comment by mthenw** [comment]
OK, will work on that.

**Comment by mthenw** [comment]
I guess you fix that :) Anything else needed here?

**Comment by tj** [comment]
think we're probably good for now, I guess versions wouldn't be super useful without some kind of changelog data

**Comment by tj** [comment]
Which I do think would be helpful some day haha. especially since lambda is so run-and-gun, I don't see people keeping a changelog really. It might be nice if we store a git sha somewhere or similar for reference
