### ISSUE TITLE
What is the future of apex? 

### ISSUE THREAD

**Issue by c-weiss-simplicity-ag** [apex/apex#807]
Wil AWS SAM (Serverless Application Model) and AWS SAM Local (a CLI / docker based local lambda) be integrated in apex or should i switch from apex to AWS SAM and AWS SAM Local ?

**Comment by tj** [comment]
Apex is just OSS for the time being, with no monetization, so it'll likely remain as-is for now. I'm personally not fond of these "emulate lambda locally" things, I think generally just testing properly with automated tests negates the need for testing at the Lambda level, especially since Lambda is designed to act like functions, functions are reasonably easy to test! But if that's what you're looking for you may want to switch.

cheers

**Comment by alias1** [comment]
I just came here wondering a similar thing, but my thinking was more that SAM could make a good local tester, rather than 'testing in production' directly on lambda. Admittedly I haven't read too deeply into it's features yet though.

**Comment by tj** [comment]
There's also https://bitbucket.org/atlassian/localstack, I haven't tried it though, but theoretically the "ideal" solution would be to just point the AWS SDK calls to localhost and emulate everything that way. 

But the whole point of Lambda is to simulate functions, so I think just testing them as functions makes sense too.

**Comment by c-weiss-simplicity-ag** [comment]
Thanks tj for all your efforts in implementing apex. You are the first vendor that brings code and project level meta data to a single repo with a good command line tool. "Lambda as code".

While i was one of the first apex users i now realized that Amazon released a very good replacement for apex. It also allows you to have a meta level project description (SAM yaml) and source code in a single repo. The SAM Local CLI allows to package and deploy, too. Furthermore it provides a full local (or remote) runtime environment incl. debugging support. This runtime environment can be used by a developer and a CI server. CLI supports development, build, test and release process automation (CI / CD server).

AWS SAM Local CLI is the way to go. Amazon is known for fast releasing of new increments - a thing that a one person project could not beat. 

The only drawback (at the moment) is, a missing multi-environment-support (DEV, STAGE, PROD) in AWS SAM Local. But you can make a sam_DEV.yaml, sam_STAGE.yaml and a sam_PROD.yaml to reach the goal (difference between these files is mainly prefixing lambda functions), with a single aws account. Using multiple accounts, each dedicated for a specific environment type, the above files do not differ or only a bit. I guess multi-environment-support will be added to the CLI soon...

Again, thanks for your tool and good bye.

**Comment by regnatarajan** [comment]
I realize I'm late to this but I just wanted to comment that there are those of us (my guess is a lot of us) who totally agree with the vision of Apex not trying to emulate Lambda locally.  Speaking for myself, I really have no interest in that at all.  Apex as it currently exists is fast, reliable, and it works on Windows which is a big deal to me.  I hope you keep it going with the current vision and let those who want local Lambda find another option.  Apex is a great project and I appreciate everyone's effort very much.

**Comment by catamphetamine** [comment]
I thought that I'd drop by and also leave my personal opinion that localhost HTTP lambda testing is a must.

**Comment by tj** [comment]
@catamphetamine yeah I don't use API Gateway with a ton of Lambdas right now, I just use https://github.com/apex/up so it's portable to other platforms or solutions (AWS Fargate for example).
