### ISSUE TITLE
deploy --zip does not work for java and clojure

### ISSUE THREAD

**Issue by mariokostelac** [apex/apex#821]
- __Operating system__: maxOS Sierra 10.12.6 (16G29)
  - __Apex Version__: 0.15.0

Deploying java and clojure functions with `--zip` does not translate apex runtime to lambda runtime so it tries to deploy `java` and `clojure` as a runtime, instead of `java8` in both cases.

**Comment by mariokostelac** [comment]
This is fixed by merging PR referenced. Do we want to close the issue now or wait until the new version is released?

**Comment by tj** [comment]
cool yea we should close it now, I'll try and do a release today

**Comment by tj** [comment]
uploading v0.16.0
