### ISSUE TITLE
Support at least Lambda@Edge requirements

### ISSUE THREAD

**Issue by tilfin** [apex/apex#828]
- Lambda@Edge must be to be excluded  environment variables. #792
- It must be deployed on `us-east-1` region. (We are generally using `ap-northeast-1` so cannot deploy all functions for a project.)

- It needs some resource limitations #610. (But they can be applied by the function settings apex has already supported.)

**Comment by tilfin** [comment]
I'm sorry I have already submitted PR #824 ahead of this issue.

**Comment by tilfin** [comment]
@tj I kindly ask you to review this feature the others need.  https://github.com/apex/apex/pull/824#issuecomment-341686043

**Comment by tj** [comment]
hey sorry for the delay! I'll try and get to these soon
