### ISSUE TITLE
Apex deploy gives "stream error: stream ID 7; PROTOCOL_ERROR"

### ISSUE THREAD

**Issue by stib** [apex/apex#837]
Hi,

I have been using `apex deploy` to deploy Lambda functions for over an year and it has worked without any problems till recently. However, when I tried to deploy a new function or update an existing function today I started getting the error below (with -ldebug command) -- I have left out a bunch of "add file to zip output" before it hits this error.

```
 fetching config           env= function=genSMS
   ⨯ Error: function genSMS: RequestError: send request failed
caused by: Get https://lambda.us-west-2.amazonaws.com/<path to function>: stream error: stream ID 7; PROTOCOL_ERROR
```

I have searched around and couldn't find any info on this error.

Apex version is 0.10.3
Operating System is OS X El Capitan version 10.11.6
"aws-sdk": "^2.145.0"

I tried a few other commands and `apex list` works fine - lists all the functions but `apex metrics` gives the same error.

Appreciate any help or pointer to resolve this.

Thanks,
Sanjay.

**Comment by alexjohnporter** [comment]
Also getting the same error

**Comment by stib** [comment]
I resolved the issue by doing an `apex update`. Hope that helps.

**Comment by tj** [comment]
ah yep the new release should be ok
