### ISSUE TITLE
[shim] unexpected line - do not use stdout: ` {} `

### ISSUE THREAD

**Issue by mrichman** [apex/apex#844]
I see this in my CloudWatch logs, and don't understand what it means:

```
2017-11-13T18:54:57.670Z	248ad7bf-c8a4-11e7-a47a-8d1cf176c5ea	[shim] unexpected line - do not use stdout: `
{}
`
```

Could someone clarify please?

**Comment by tj** [comment]
ah see #840, make sure to update apex/go-apex

**Comment by mrichman** [comment]
Thanks! That did the trick. I keep forgetting that even though I updated the `apex` binary, my application still needs to be rebuilt with latest libs. Note to future self when I screw this up again in a few months :)
