### ISSUE TITLE
Setting retained versions to anything more than 49 causes problems

### ISSUE THREAD

**Issue by clark-pan** [apex/apex#846]
If you have a bug report please let us know the following:

  - __Operating system__: All
  - __Apex Version__: Latest

When appropriate please also paste the debug log output using `-ldebug` or `--log-level debug`.

This one is a bit hard to explain, so bear with me.

Theres a hidden hard limit (50) on the number of versions that comes back from the ListVersionsByFunction. This applies even if you set `max-items` to be above 50.

Currently, the expectation for the `versions` method in `functions.go` is to return all function versions. Because theres a hard limit, it causes problems:

- If retained versions is set to anything above 49, `versions` returns 49 items (it tries to remove the last version, making the assumption that its `$LATEST`). This means no versions will be deleted.
- After this happens, when you try to deploy functions where neither the config nor code changes, the code will set the alias to the last version + 50, which is probably not the actual latest version. (apologies cause I wrote that code).

Steps to reproduce:

- Create a function.
- Set retained versions to 49.
- Deploy 49 versions.
- Deploy a few more and notice that no versions are deleted.
- Try to run `deploy` without any config or code change
- Notice that the `current` alias is now set to oldest version + 50

I think we can fix this by making the `versions` function use the 'next' marker that aws gives back to get the total number of functions.

**Comment by marcejohnson** [comment]
Thanks for capturing this.   We are seeing this in our environment.  
This bug should be marked as high-severity because it results in deploying the wrong code, which could be catastrophic in some scenarios.

**Comment by kcolemangt** [comment]
@clark-pan @marcejohnson Please confirm if https://github.com/apex/apex/pull/882 fixes your issue.

**Comment by marcejohnson** [comment]
@kcolemangt thank you!  Upgraded and so far so good!  We'll report back if we see otherwise.
