### ISSUE TITLE
How to build a zip file that Apex can deploy?

### ISSUE THREAD

**Issue by creativexp** [apex/apex#848]
- __Operating system__: Windows
  - __Apex Version__: 0.16.0

I am using a make-file to build a zip file of my python lambda and all its dependencies. 

When i try to use "apex deploy --zip myzip.zip" to deploy it, the zip will upload to aws but will not run. I get "module main cannot not be found" error. 

When i deploy my lambda using apex deploy, my lambda uploads and runs fine. 

Does Apex do something special other than copy everything in the functions/hello folder, zip it up and upload? 

I even downloaded the uploaded lambda zip files for both scenarios and they where identical.  

Does Apex upload something else in a hidden way that i need to replicate?

**Comment by tj** [comment]
It does set the “handler” field correctly for the shim (index.handle I believe) so you’d have to make sure that matches! That’s about it though :D
