### ISSUE TITLE
Remove/rename detection

### ISSUE THREAD

**Issue by mthenw** [apex/apex#85]
I'm thinking about scanning all functions names in AWS account and looking for those that might have been deployed before and then deleted from folder or renamed. 

As we suggest stage/env per account it shouldn't be perf problem. 

Thoughts?

**Comment by tj** [comment]
Yeah agreed, sounds related to #65, you'll get an error if it was manually deleted like you mentioned. I don't think we need it in other spots yet though, just delete and `apex list` which needs some love haha
