### ISSUE TITLE
Error: TooManyRequestsException

### ISSUE THREAD

**Issue by Prefinem** [apex/apex#857]
- __Operating system__: Ubuntu
  - __Apex Version__: v0.16.0

We have a large project that we are trying to deploy and keep getting the error TooManyRequestsException.  AWS has told us to do a retry with exponential back off but the issue is we are trying to deploy the whole project.  Could this be something apex does when deploying a project on a per function basis?

**Comment by Liath** [comment]
You're hitting this limit on deploy? How many functions are your trying to push? 
I only API limit I know of for sure on Lambda is the concurrent execution safety limit.

**Comment by Prefinem** [comment]
We have around 100 functions per stage.  When we rolled out an infrastructure change (upgrading a package for each function) it would require a deployment of all the functions

It's an AWS SDK API Limit.  We contacted AWS Support and essentially they limit the number of API calls you can make.  We fixed this by versioning each function and deploying only the functions that changed.  In the case of deploying all the functions, we would just retry the deployment each time until it was successfully deployed.  

We have since then moved to serverless for less of a homegrown system but this is something that would be pretty beneficial for apex if you want to deploy 100+ functions

**Comment by Liath** [comment]
Yeah it would be helpful to handle this better. Probably with retry/backoff since that's pretty easy.

Out of curiosity, did you have the default execution limit on your account? I feel like we would have seen this too but ours is well over the default 1000.

**Comment by Prefinem** [comment]
Execution limit for Lambda?  We are 3000 for our limit. 

This isn’t that. The limit for the AWS SDK API is something else. I can try and get a copy of the support ticket from Amazon if that would help.

**Comment by Liath** [comment]
I would appreciate that. I can't really find any docs for this limit.

Seems like we'll either need to make some kind of backoff (like you said) or add throttling on api calls. I'm willing to bet we repeat some work unnecessarily and could cache call results to help this.

I just noticed apex has a `concurrency` field in project.json that's basically undocumented (and I can't see how it's actually used). I wonder if it would help here?

**Comment by Prefinem** [comment]
Concurrency is probably the new implemented concurrency limit you can apply to each function. 

Here is the response I received 

“Hello,

Thank you for contacting AWS Premium Support. I am ——- and will be assisting you with your issue today.

I understand that your deployment pipeline is getting "TooManyRequestsException" when deploying your functions.

There are specific throttles set on certain Lambda API calls and if you perform too many of these API calls at a time, you may hit this error. May I ask what API call you are performing that leads to this exception? The limits on these API calls vary by region and based on the specific API call. These service limits are set in place to ensure the quality of AWS Services for customers.

Please take a look at [1] which talks about EC2 API limits. The API behavior is common for most AWS services.

AWS API actions are divided into action types such as: 

->   Describe actions, such as ListAliases, ListFunctions etc - these functions simply retrieve cached data, so they have the highest retry limits
->   Modify actions, such as CreateFunction, CreateAlias, etc - these functions create or modify resources so they have a lower request limit than describe actions

To prevent these errors from occurring, I would request you to implement retries with exponential back off. The exponential back off approach implements retry logic which uses progressively longer waits between retries for consecutive error responses. When using this response you can specify a maximum delay interval as well as a maximum number of retries. 
The pseudo-code for this approach looks something like this:

Do some asynchronous operation.

retries = 0

DO
    wait for (2^retries * 100) milliseconds

    status = Get the result of the asynchronous operation.

    IF status = SUCCESS
        retry = false
    ELSE IF status = NOT_READY
        retry = true
    ELSE IF status = THROTTLED
        retry = true
    ELSE
        Some other error occurred, so stop calling the API.
        retry = false
    END IF

    retries = retries + 1

WHILE (retry AND (retries < MAX_RETRIES))

Please see [2] to know more about API retries.

I would request you to implement retries with exponential back off for your API calls to see if you are able to overcome the problem. However if you still face issues, please provide the full error trace and the API call that results in this exception along with your use case. 

Also feel free to get back to us if you have any other questions.

[1] : https://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html#api-request-rate

[2] : https://docs.aws.amazon.com/general/latest/gr/api-retries.html”
