### ISSUE TITLE
 Remove Node.js shim in favour of native Go support

### ISSUE THREAD

**Issue by kaihendry** [apex/apex#862]
Same as https://github.com/apex/up/issues/450

**Comment by rv-zjohnson** [comment]
added a PR for this - not highly familiar with the project so I'm not sure if there are other locations that also need to be updated as well.

**Comment by tj** [comment]
@rv-zjohnson tried it out, looks fine to me! 

I'll probably push a major since this requires the use of aws/aws-lambda-go, so keep that in mind everyone if you upgrade `apex(1)` :D
