### ISSUE TITLE
Adding support for runtime "node 8.10"

### ISSUE THREAD

**Issue by rafaeldrs** [apex/apex#876]
This is not a bug, but an enhancement. Since last night, AWS lambda now supports node 8.10 runtime, so it would be cool if you could add support for it.

**Comment by rafaeldrs** [comment]
I get the following error when setting runtime "nodejs8.10" in project.json (it works fine with runtime "nodejs4.3" or "nodejs6.10"):

Error: error opening function function_name: Handler: zero value

**Comment by rafaeldrs** [comment]
I know some time has passed but if someone is having my same problem, just update apex to latest version.

You can close this issue =)

**Comment by tj** [comment]
:D

**Comment by gugu** [comment]
@tj probably you want to update runtime list here: http://apex.run/#runtime

**Comment by sheerun** [comment]
@tj Apex returns Error: function mailer: ValidationException: 1 validation error detected: Value 'node8.10' at 'runtime' failed to satisfy constraint: Member must satisfy enum value set: [java8, nodejs, nodejs4.3, nodejs6.10, python2.7, python3.6, dotnetcore1.0]

Plus it seems the deployed v1.0.0-rc3 is actuall v1.0.0-rc2 if you download darwin 64 executable

**Comment by ojizero** [comment]
@sheerun did you try it runtime value `nodejs8.10` (the _js_ suffix to node)?
