### ISSUE TITLE
Feature request: `region` field in project.json

### ISSUE THREAD

**Issue by astj** [apex/apex#883]
I use multiple regions in a same AWS account to separate environments. (ex: ap-northeast-1 for production, us-east-1 for testing), and I'd like to handle those environments in apex's `--env` feature.

I can switch AWS _profiles_ using `profile` field in project.ENV.json, but `region` is not configurable in the JSON.

Currently I know some workarounds:
- Configure 2 AWS profiles for same account but different two regions, and specify the profile in project.ENV.json
  - like: `myaccount-tokyo` and `myaccount-virginia`
- Always set `apex --region` option carefully

But it's happy if I can set `region` field in project.ENV.json, like `profile`.

If this feature request is approved, I can open a p-r to implement this feature. (Ref: https://github.com/apex/apex/compare/master...astj:add-region-config?expand=1)

**Comment by Liath** [comment]
Go ahead and create the PR. It seems reasonable enough to me and you're not the first to ask for this.

**Comment by astj** [comment]
@Liath Okay. I opened #889.

**Comment by astj** [comment]
I've just found #824.  Though project-wide region configuration is better in my project, but that can be an alternative, by specifying region in function.ENV.json of each functions.

**Comment by tj** [comment]
merged, thanks guys!
