### ISSUE TITLE
Switch CLI library to cobra

### ISSUE THREAD

**Issue by pilwon** [apex/apex#89]
Many of the most widely used Go projects are built using [Cobra](https://github.com/spf13/cobra) including `Kubernetes`, `etcd`, `Docker`, and `CockroachDB`.

Though it is not necessarily the best CLI library of all, switching to `cobra` helps `apex` remove quite a bit of boilerplate code it currently has with `docopt`. It can arguably scale better too when the number of sub-commands and options grows over time.

**Comment by tj** [comment]
Nice yea sounds good to me. Part of me prefers docopt since you get the arguments for each command right there, but you don't get the command description which does kinda suck. We'd have to rename `apex help` to `apex wiki` but that's totally cool with me, more appropriate name anyway

**Comment by pilwon** [comment]
@tj Just submitted PR #89.

Not sure what to do with autocompletion. I know `Cobra` has autocompletion feature built in but I haven't explored it yet.

**Comment by tj** [comment]
no worries about autocomplete for now, we need to support dynamic generation there for function names anyway, we can remove the current stuff in the PR or a separate request

**Comment by pilwon** [comment]
@tj Alrighty, let's keep it together with this PR.
