### ISSUE TITLE
Medium Blog Link -> 404

### ISSUE THREAD

**Issue by Jolg42** [apex/apex#895]
Hi there!

The link to Mediun in the README
https://github.com/apex/apex#links 

And on the website return a 404
http://apex.run/

![screenshot 2018-07-26 at 12 42 15](https://user-images.githubusercontent.com/1328733/43257979-8b521188-90d1-11e8-98f6-dc805f8eea61.png)

**Comment by tj** [comment]
oh nice thanks! missed that
