### ISSUE TITLE
Local execution

### ISSUE THREAD

**Issue by tj** [apex/apex#9]
Something like:

```
$ apex invoke local <name> < some.json
```

Alternatively a local Lambda simulator thing so you can just use `apex invoke --url localhost:3000 < some.json` or similar.

**Comment by mthenw** [comment]
Not sure if this is what you meant by "Lambda simulator" but I was thinking about something that you run in project directory and than you can make `apex invoke --url localhost:3000 < some.json`.

So it would implement only runtime, not any other stuff like function creation etc.

**Comment by tj** [comment]
yep! I'm on the same page. It's kinda nice using Go you can just do `go run main.go < some.json` for pretty much the same effect haha, but having something like `apex serve` and then invoke like you mentioned would be handy. Definitely need to nail workflow, that's my main concern with Lambda but I'm still hacking on front-end right now

**Comment by tj** [comment]
closing since it'll likely be a separate program that you install, since it wont have the same level of polish (whole thing is basically a hack) I don't want it in core.
