### ISSUE TITLE
Releasing a new rc version of apex?

### ISSUE THREAD

**Issue by bnoguchi** [apex/apex#900]
Hi TJ, when are you planning on a new rc release of apex? We're relying on support of this [PR](https://github.com/apex/apex/commit/8b0e46ddb807f67236aa926df9fdb004ce891859) from May. Thanks!

**Comment by bnoguchi** [comment]
Closed by 7c1d44b04d0de6807484c167484e65773ecd55cb . Thanks!

**Comment by bnoguchi** [comment]
Nevermind, not published to https://github.com/apex/apex/releases

**Comment by tj** [comment]
v1.0.0-rc4 should be ok now sorry for the delay there!

**Comment by bnoguchi** [comment]
Hi TJ, I'm not sure if you pushed the latest version to the GitHub releases, as the latest version is still v1.0.0-rc3.
