### ISSUE TITLE
The `edge` option in the function.json is not working.

### ISSUE THREAD

**Issue by nauxliu** [apex/apex#909]
- __Operating system__: MacOS 10.14
  - __Apex Version__: Apex version 1.0.0-rc3

I have set the `edge` to `true` in the `function.json` and there is still have two env. (APEX_FUNCTION_NAME, LAMBDA_FUNCTION_NAME)

project structure.
```
.
├── functions
│   └── azure_auth
│       ├── function.json
│       └── index.js
└── project.json
```

function.json content
```
{
  "edge": true
}
```

**Comment by rluisr** [comment]
If you want to try using `edge: true` clone this repo and install with `go install ./...`.
