### ISSUE TITLE
Is there plans for a init project option for the CLI?

### ISSUE THREAD

**Issue by wolfeidau** [apex/apex#91]
Just trying this tool out at the moment and i am correct in thinking i need to create the project.json and related folders?

Cheers

**Comment by tj** [comment]
yup that's correct. I was going to add a scaffolding command, but you only need:

```
touch project.json
mkdir -p functions/{foo,bar,baz}
touch functions/{foo,bar,baz}/index.js
```

Was #44, might re-open if/when things get more complicated.

**Comment by wolfeidau** [comment]
Maybe just add that tidbit to the Readme? 

Just makes it clearer for those just getting started.

Thanks

**Comment by tj** [comment]
will do!

**Comment by tj** [comment]
opened #92 as well, at very least we'll have some repos that people can clone

**Comment by wolfeidau** [comment]
Thanks a lot, sounds fantastic, making easy for people to get started makes a big difference :smile:
