### ISSUE TITLE
Boilerplate repo(s) & project scaffolding

### ISSUE THREAD

**Issue by tj** [apex/apex#92]
If we do maintain scaffolding it might be best to maintain outside this repo.

We could have apex(1) pulls it down for you, though. Say we create `apex/boilerplate` that contains `./{nodejs,golang,java}`, and then something like `apex create myproject --runtime golang` (or require the runtime, whatever :D).

**Comment by mthenw** [comment]
Loose idea: `apex create project` could also create IAM role for functions.

**Comment by tj** [comment]
@mthenw ah yea true could be a good point to bootstrap. I suppose we could have some init command or make it idempotent like the others as well. I'm not 100% sure on which route to go there. I could see deploy getting pretty slow over time haha so probably best to keep it out of `deploy` I suppose

**Comment by tj** [comment]
added the one, good enough for me
