### ISSUE TITLE
Actively maintained?

### ISSUE THREAD

**Issue by franciscolourenco** [apex/apex#932]
Support for lambda@edge has been committed to master almost a year ago, but never released. Is this project still being maintained?

Thank you!

**Comment by tj** [comment]
check out #894

**Comment by franciscolourenco** [comment]
That means that this feature won't be released in 1.x?

**Comment by tj** [comment]
Unlikely, it takes too much time to properly QA everything

**Comment by franciscolourenco** [comment]
Ok, thanks for the quick answer. Good luck with 2.0!

**Comment by tj** [comment]
thanks :D hopefully I can figure out a way to make it work
