### ISSUE TITLE
Installing using the .sh file fails (linux, docker, mac)

### ISSUE THREAD

**Issue by nicwise** [apex/apex#942]
If you have a bug report please let us know the following:

  - osx and linux:
  - 1.0.0.rc3:

When appropriate please also paste the debug log output using `-ldebug` or `--log-level debug`.

```
Step 9/19 : RUN curl https://raw.githubusercontent.com/apex/apex/master/install.sh | sh
 ---> Running in 7d125e029246
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8016  100  8016    0     0  34897      0 --:--:-- --:--:-- --:--:-- 35004
apex/apex: checking GitHub for latest version
curl: (22) The requested URL returned error: 403 Forbidden
The command '/bin/sh -c curl https://raw.githubusercontent.com/apex/apex/master/install.sh | sh' returned a non-zero code: 22
```

I get this on both macOS and in a linux container (ubuntu 16). 

I've unrolled the installer enough to make it work, but it's not ideal.

**Comment by tj** [comment]
I think you're hitting a Github API rate-limit, may have to wait a bit and try again or create a personal application token and set GITHUB_TOKEN=xxxxx in your terminal

**Comment by nicwise** [comment]
Makes sense why a co-worker was able to do it at another time. Oh, well. I ended up doing it manually.
