### ISSUE TITLE
Metrics support

### ISSUE THREAD

**Issue by johannesboyne** [apex/apex#96]
I could offer to implement CloudWatch Metrics for Lambda functions. Sometimes it is quite nice to check:
* Invocations
* Errors
* Duration
* Throttles

e.g.:

```shell
$ master: apex metrics foo --today
Invocations: 	3
Errors: 		1
Duration: 		123 ms
Throttles: 		0
```

```shell
$ master: apex metrics foo --today --invocations --timeline
{ "Datapoints": [{
  "Sum": 1,
  "Timestamp": "2016-01-18 15:00:00 +0000 UTC",
  "Unit": "Count"
},{
  "Sum": 2,
  "Timestamp": "2016-01-18 16:00:00 +0000 UTC",
  "Unit": "Count"
}]
```

**Comment by mthenw** [comment]
+1 from me. not sure about cli param though.

**Comment by tj** [comment]
Sounds handy, wonder how nuts we should get with that, displaying timeseries in the term or just averages for the timeperiod etc. I could see that getting out of hand unless we define what that would be. I'd probably skip the json output at least.

**Comment by johannesboyne** [comment]
Yep! Definitely handy but as you said it, one has to think a bit about the output.
My proposal would be: I'll start with a working draft, keeping it _simple and stupid_ in the first run. Adding more complex output scenarios later should be easy ;-)

**Comment by johannesboyne** [comment]
I've started a first draft (t.b.c.): https://github.com/johannesboyne/apex/commit/fae6e8622db1a925cded8ea1c8313c0182367f82

Returns:

```shell
$ master: apex metrics foo --today
Invocations: 3
Errors: 1
Duration: 123
Throttles: 0
```
